/*
 * AUTOGENERATED by mrustc
 */
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>
#include <assert.h>
#include <stdatomic.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <setjmp.h>
typedef uint32_t RUST_CHAR;
typedef uint8_t RUST_BOOL;
typedef struct { void* PTR; size_t META; } SLICE_PTR;
typedef struct { void* PTR; void* META; } TRAITOBJ_PTR;
typedef struct { void (*drop)(void*); size_t size; size_t align; } VTABLE_HDR;
typedef struct { char _d; } tUNIT;
typedef char tBANG;
typedef struct { char _d; } tTYPEID;
static inline size_t ALIGN_TO(size_t s, size_t a) { return (s + a-1) / a * a; }

extern void _Unwind_Resume(void) __attribute__((noreturn));
#define ALIGNOF(t) __alignof__(t)
extern __thread jmp_buf*    mrustc_panic_target;
extern __thread void* mrustc_panic_value;
static inline uint64_t __builtin_clz64(uint64_t v) {
	return ( (v >> 32) != 0 ? __builtin_clz(v>>32) : 32 + __builtin_clz(v));
}
static inline uint64_t __builtin_ctz64(uint64_t v) {
	return ((v&0xFFFFFFFF) == 0 ? __builtin_ctz(v>>32) + 32 : __builtin_ctz(v));
}
static inline uint8_t __mrustc_atomicloop8(volatile uint8_t* slot, uint8_t param, int ordering, uint8_t (*cb)(uint8_t, uint8_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint8_t v = atomic_load_explicit((_Atomic uint8_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint8_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint16_t __mrustc_atomicloop16(volatile uint16_t* slot, uint16_t param, int ordering, uint16_t (*cb)(uint16_t, uint16_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint16_t v = atomic_load_explicit((_Atomic uint16_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint16_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint32_t __mrustc_atomicloop32(volatile uint32_t* slot, uint32_t param, int ordering, uint32_t (*cb)(uint32_t, uint32_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint32_t v = atomic_load_explicit((_Atomic uint32_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint32_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint64_t __mrustc_atomicloop64(volatile uint64_t* slot, uint64_t param, int ordering, uint64_t (*cb)(uint64_t, uint64_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint64_t v = atomic_load_explicit((_Atomic uint64_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint64_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
typedef unsigned __int128 uint128_t;
typedef signed __int128 int128_t;
static inline uint128_t __builtin_bswap128(uint128_t v) {
	uint64_t lo = __builtin_bswap64((uint64_t)v);
	uint64_t hi = __builtin_bswap64((uint64_t)(v>>64));
	return ((uint128_t)lo << 64) | (uint128_t)hi;
}
static inline uint128_t intrinsic_ctlz_u128(uint128_t v) {
	return (v == 0 ? 128 : (v >> 64 != 0 ? __builtin_clz64(v>>64) : 64 + __builtin_clz64(v)));
}
static inline uint128_t intrinsic_cttz_u128(uint128_t v) {
	return (v == 0 ? 128 : ((v&0xFFFFFFFFFFFFFFFF) == 0 ? __builtin_ctz64(v>>64) + 64 : __builtin_ctz64(v)));
}

static inline int slice_cmp(SLICE_PTR l, SLICE_PTR r) {
	int rv = memcmp(l.PTR, r.PTR, l.META < r.META ? l.META : r.META);
	if(rv != 0) return rv;
	if(l.META < r.META) return -1;
	if(l.META > r.META) return 1;
	return 0;
}
static inline SLICE_PTR make_sliceptr(void* ptr, size_t s) { SLICE_PTR rv = { ptr, s }; return rv; }
static inline TRAITOBJ_PTR make_traitobjptr(void* ptr, void* vt) { TRAITOBJ_PTR rv = { ptr, vt }; return rv; }

static inline size_t mrustc_max(size_t a, size_t b) { return a < b ? b : a; }
static inline void noop_drop(tUNIT *p) { }

static inline size_t mrustc_string_search_linear(SLICE_PTR val, size_t count, SLICE_PTR* options) {
	for(size_t i = 0; i < count; i ++) {
		int cmp = slice_cmp(val, options[i]);
		if(cmp < 0) break;
		if(cmp == 0) return i;
	}
	return SIZE_MAX;
}
static const uint8_t __mrustc_revmap[16] = { 0, 8, 4,12, 2,10, 6,14,  1, 9, 5,13, 3, 7,15};
static inline uint8_t __mrustc_bitrev8(uint8_t v) { if(v==0||v==0xFF) return v; return __mrustc_revmap[v>>4]|(__mrustc_revmap[v&15]<<4); }
static inline uint16_t __mrustc_bitrev16(uint16_t v) { if(v==0) return 0; return ((uint16_t)__mrustc_bitrev8(v>>8))|((uint16_t)__mrustc_bitrev8(v)<<8); }
static inline uint32_t __mrustc_bitrev32(uint32_t v) { if(v==0) return 0; return ((uint32_t)__mrustc_bitrev16(v>>16))|((uint32_t)__mrustc_bitrev16(v)<<16); }
static inline uint64_t __mrustc_bitrev64(uint64_t v) { if(v==0) return 0; return ((uint64_t)__mrustc_bitrev32(v>>32))|((uint64_t)__mrustc_bitrev32(v)<<32); }
static inline uint128_t __mrustc_bitrev128(uint128_t v) { if(v==0) return 0; uint128_t rv = ((uint128_t)__mrustc_bitrev64(v>>64))|((uint128_t)__mrustc_bitrev64(v)<<64); return rv; }
static inline uint8_t __mrustc_op_umax8(uint8_t a, uint8_t b) { return (a > b ? a : b); }
static inline uint8_t __mrustc_op_umin8(uint8_t a, uint8_t b) { return (a < b ? a : b); }
static inline uint8_t __mrustc_op_imax8(uint8_t a, uint8_t b) { return ((int8_t)a > (int8_t)b ? a : b); }
static inline uint8_t __mrustc_op_imin8(uint8_t a, uint8_t b) { return ((int8_t)a < (int8_t)b ? a : b); }
static inline uint8_t __mrustc_op_and_not8(uint8_t a, uint8_t b) { return ~(a & b); }
static inline uint16_t __mrustc_op_umax16(uint16_t a, uint16_t b) { return (a > b ? a : b); }
static inline uint16_t __mrustc_op_umin16(uint16_t a, uint16_t b) { return (a < b ? a : b); }
static inline uint16_t __mrustc_op_imax16(uint16_t a, uint16_t b) { return ((int16_t)a > (int16_t)b ? a : b); }
static inline uint16_t __mrustc_op_imin16(uint16_t a, uint16_t b) { return ((int16_t)a < (int16_t)b ? a : b); }
static inline uint16_t __mrustc_op_and_not16(uint16_t a, uint16_t b) { return ~(a & b); }
static inline uint32_t __mrustc_op_umax32(uint32_t a, uint32_t b) { return (a > b ? a : b); }
static inline uint32_t __mrustc_op_umin32(uint32_t a, uint32_t b) { return (a < b ? a : b); }
static inline uint32_t __mrustc_op_imax32(uint32_t a, uint32_t b) { return ((int32_t)a > (int32_t)b ? a : b); }
static inline uint32_t __mrustc_op_imin32(uint32_t a, uint32_t b) { return ((int32_t)a < (int32_t)b ? a : b); }
static inline uint32_t __mrustc_op_and_not32(uint32_t a, uint32_t b) { return ~(a & b); }
static inline uint64_t __mrustc_op_umax64(uint64_t a, uint64_t b) { return (a > b ? a : b); }
static inline uint64_t __mrustc_op_umin64(uint64_t a, uint64_t b) { return (a < b ? a : b); }
static inline uint64_t __mrustc_op_imax64(uint64_t a, uint64_t b) { return ((int64_t)a > (int64_t)b ? a : b); }
static inline uint64_t __mrustc_op_imin64(uint64_t a, uint64_t b) { return ((int64_t)a < (int64_t)b ? a : b); }
static inline uint64_t __mrustc_op_and_not64(uint64_t a, uint64_t b) { return ~(a & b); }
struct e_ZRG1cE12libc0_0_0_H46c_void0g;
 // (usize, usize, )
typedef struct TUP_2_ZRTCu_ZRTCu  {
	/*@0*/uintptr_t _0; // usize
	/*@8*/uintptr_t _1; // usize
} TUP_2_ZRTCu_ZRTCu ;
typedef char sizeof_assert_TUP_2_ZRTCu_ZRTCu [ (sizeof(TUP_2_ZRTCu_ZRTCu ) == 16) ? 1 : -1 ];
struct s_ZRG1cM17alloc_system0_0_06System0g;
struct s_ZRG2cE9core0_0_05alloc6Layout0g;
// struct ::"core-0_0_0"::nonzero::NonZero<usize,>
struct s_ZRG2cE9core0_0_07nonzero7NonZero1gCu  {
	/*@0*/uintptr_t _0; // usize
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_07nonzero7NonZero1gCu[ (sizeof(struct s_ZRG2cE9core0_0_07nonzero7NonZero1gCu) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_07nonzero7NonZero1gCu[ (ALIGNOF(struct s_ZRG2cE9core0_0_07nonzero7NonZero1gCu) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::num::NonZeroUsize
struct s_ZRG2cE9core0_0_03num12NonZeroUsize0g  {
	/*@0*/struct s_ZRG2cE9core0_0_07nonzero7NonZero1gCu _0; // ::"core-0_0_0"::nonzero::NonZero<usize,>/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03num12NonZeroUsize0g[ (sizeof(struct s_ZRG2cE9core0_0_03num12NonZeroUsize0g) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03num12NonZeroUsize0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03num12NonZeroUsize0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::alloc::Layout
struct s_ZRG2cE9core0_0_05alloc6Layout0g  {
	/*@0*/uintptr_t _0; // usize
	/*@8*/struct s_ZRG2cE9core0_0_03num12NonZeroUsize0g _1; // ::"core-0_0_0"::num::NonZeroUsize/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_05alloc6Layout0g[ (sizeof(struct s_ZRG2cE9core0_0_05alloc6Layout0g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_05alloc6Layout0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05alloc6Layout0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::nonzero::NonZero<*const u8,>
struct s_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa  {
	/*@0*/uint8_t *_0; // *const u8
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa[ (sizeof(struct s_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa[ (ALIGNOF(struct s_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::ptr::NonNull<u8,>
struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa  {
	/*@0*/struct s_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa _0; // ::"core-0_0_0"::nonzero::NonZero<*const u8,>/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03ptr7NonNull1gCa[ (sizeof(struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03ptr7NonNull1gCa[ (ALIGNOF(struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::alloc::Excess
struct s_ZRG2cE9core0_0_05alloc6Excess0g  {
	/*@0*/struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa _0; // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
	/*@8*/uintptr_t _1; // usize
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_05alloc6Excess0g[ (sizeof(struct s_ZRG2cE9core0_0_05alloc6Excess0g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_05alloc6Excess0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05alloc6Excess0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Ok<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>
struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  {
	/*@0*/struct s_ZRG2cE9core0_0_05alloc6Excess0g _0; // ::"core-0_0_0"::alloc::Excess/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::alloc::AllocErr
struct s_ZRG2cE9core0_0_05alloc8AllocErr0g  {
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG2cE9core0_0_05alloc8AllocErr0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05alloc8AllocErr0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Err<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>
struct s_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  {
	/*@0*/// ZST; // ::"core-0_0_0"::alloc::AllocErr/*S*/
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g) == 1) ? 1 : -1 ];
// enum ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g {
	struct {
		struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g var_0;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g[ (sizeof(struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g) == 16) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Ok<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>
struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  {
	/*@0*/struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa _0; // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Err<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>
struct s_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  {
	/*@0*/// ZST; // ::"core-0_0_0"::alloc::AllocErr/*S*/
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g) == 1) ? 1 : -1 ];
// enum ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g {
	struct {
		struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g var_0;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g[ (sizeof(struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::alloc::closure#alloc_excess_1<'#local1,>
struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_10g  {
	/*@0*/TUP_2_ZRTCu_ZRTCu *_0; // &'#local1 (usize, usize, )
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_05allocH21closurealloc_excess_10g[ (sizeof(struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_10g) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_05allocH21closurealloc_excess_10g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_10g) == 8) ? 1 : -1 ];
// struct ::"alloc_system-0_0_0"::System
struct s_ZRG1cM17alloc_system0_0_06System0g  {
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG1cM17alloc_system0_0_06System0g[ (ALIGNOF(struct s_ZRG1cM17alloc_system0_0_06System0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::alloc::closure#realloc_excess_0<'#local2,>
struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_00g  {
	/*@0*/TUP_2_ZRTCu_ZRTCu *_0; // &'#local2 (usize, usize, )
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_05allocH23closurerealloc_excess_00g[ (sizeof(struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_00g) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_05allocH23closurerealloc_excess_00g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_00g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::option::Option#Some<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>
struct s_ZRG2cE9core0_0_06optionG10OptionSome1gG2c_A3ptr7NonNull1gCa  {
	/*@0*/struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa _0; // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gG2c_A3ptr7NonNull1gCa[ (sizeof(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gG2c_A3ptr7NonNull1gCa) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gG2c_A3ptr7NonNull1gCa[ (ALIGNOF(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gG2c_A3ptr7NonNull1gCa) == 8) ? 1 : -1 ];
// enum ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>
struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa {
	struct {
		struct s_ZRG2cE9core0_0_06optionG10OptionSome1gG2c_A3ptr7NonNull1gCa var_1;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa[ (sizeof(struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Ok<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>
struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A5alloc20CannotReallocInPlace0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ()
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A5alloc20CannotReallocInPlace0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A5alloc20CannotReallocInPlace0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A5alloc20CannotReallocInPlace0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A5alloc20CannotReallocInPlace0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::alloc::CannotReallocInPlace
struct s_ZRG2cE9core0_0_05alloc20CannotReallocInPlace0g  {
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG2cE9core0_0_05alloc20CannotReallocInPlace0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05alloc20CannotReallocInPlace0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Err<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>
struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A5alloc20CannotReallocInPlace0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A5alloc20CannotReallocInPlace0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A5alloc20CannotReallocInPlace0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A5alloc20CannotReallocInPlace0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A5alloc20CannotReallocInPlace0g) == 1) ? 1 : -1 ];
// enum ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>
struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g {
	union {
		struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A5alloc20CannotReallocInPlace0g var_0;
		struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A5alloc20CannotReallocInPlace0g var_1;
		uint8_t TAG;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g[ (sizeof(struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g) == 1) ? 1 : -1 ];
typedef struct t_ZRTfQBsCy2cE9core0_0_03fmt7Display0g_B0g  { char _unused; } t_ZRTfQBsCy2cE9core0_0_03fmt7Display0g_B0g ;
struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g;
struct s_ZRG2cE9core0_0_03fmt9Formatter0g;
typedef struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  (*t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g )( SLICE_PTR *, struct s_ZRG2cE9core0_0_03fmt9Formatter0g * ); // for<'elided#0,'elided#1,> extern "Rust" fn(&'static &'static str, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
struct s_ZRG2cE9core0_0_03fmt4Void0g;
typedef struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  (*t_ZRTF2BsG2cE9core0_0_03fmt4Void0gBuG2c_A_B9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g )( struct s_ZRG2cE9core0_0_03fmt4Void0g *, struct s_ZRG2cE9core0_0_03fmt9Formatter0g * ); // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 ::"core-0_0_0"::fmt::Void/*S*/, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
// struct ::"core-0_0_0"::fmt::ArgumentV1<'static,>
struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  {
	/*@0*/struct s_ZRG2cE9core0_0_03fmt4Void0g *_0; // &'static ::"core-0_0_0"::fmt::Void/*S*/
	/*@8*/t_ZRTF2BsG2cE9core0_0_03fmt4Void0gBuG2c_A_B9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g _1; // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 ::"core-0_0_0"::fmt::Void/*S*/, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03fmt10ArgumentV10g[ (sizeof(struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03fmt10ArgumentV10g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g) == 8) ? 1 : -1 ];
typedef struct t_ZRTA1G2cE9core0_0_03fmt10ArgumentV10g  { struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  DATA[1]; } t_ZRTA1G2cE9core0_0_03fmt10ArgumentV10g ; // [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/; 1]
// struct ::"core-0_0_0"::option::Option#Some<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>
struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g  {
	/*@0*/SLICE_PTR _0; // &'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/]
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g[ (sizeof(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g) == 8) ? 1 : -1 ];
// enum ::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>
struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g {
	struct {
		struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g var_1;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g[ (sizeof(struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g) == 16) ? 1 : -1 ];
struct s_ZRG2cE9core0_0_03fmt9Arguments0g;
// struct ::"core-0_0_0"::option::Option#Some<&'#local2 ::"core-0_0_0"::fmt::Arguments<'#local2,>/*S*/,>
struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsG2c_A3fmt9Arguments0g  {
	/*@0*/struct s_ZRG2cE9core0_0_03fmt9Arguments0g *_0; // &'#local2 ::"core-0_0_0"::fmt::Arguments<'#local2,>/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gBsG2c_A3fmt9Arguments0g[ (sizeof(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsG2c_A3fmt9Arguments0g) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gBsG2c_A3fmt9Arguments0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsG2c_A3fmt9Arguments0g) == 8) ? 1 : -1 ];
// enum ::"core-0_0_0"::option::Option<&'#local2 ::"core-0_0_0"::fmt::Arguments<'#local2,>/*S*/,>
struct e_ZRG2cE9core0_0_06option6Option1gBsG2c_A3fmt9Arguments0g {
	struct {
		struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsG2c_A3fmt9Arguments0g var_1;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06option6Option1gBsG2c_A3fmt9Arguments0g[ (sizeof(struct e_ZRG2cE9core0_0_06option6Option1gBsG2c_A3fmt9Arguments0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::panic::Location<'#local2,>
struct s_ZRG2cE9core0_0_05panic8Location0g  {
	/*@0*/uint32_t _1; // u32
	/*@4*/uint32_t _2; // u32
	/*@8*/SLICE_PTR _0; // &'#local2 str
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_05panic8Location0g[ (sizeof(struct s_ZRG2cE9core0_0_05panic8Location0g) == 24) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_05panic8Location0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05panic8Location0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::panic::PanicInfo<'#local2,>
struct s_ZRG2cE9core0_0_05panic9PanicInfo0g  {
	/*@0*/struct e_ZRG2cE9core0_0_06option6Option1gBsG2c_A3fmt9Arguments0g _1; // ::"core-0_0_0"::option::Option<&'#local2 ::"core-0_0_0"::fmt::Arguments<'#local2,>/*S*/,>/*E*/
	/*@8*/TRAITOBJ_PTR _0; // &'#local2 dyn (::"core-0_0_0"::any::Any+::"core-0_0_0"::marker::Send)
	/*@24*/struct s_ZRG2cE9core0_0_05panic8Location0g _2; // ::"core-0_0_0"::panic::Location<'#local2,>/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_05panic9PanicInfo0g[ (sizeof(struct s_ZRG2cE9core0_0_05panic9PanicInfo0g) == 48) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_05panic9PanicInfo0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05panic9PanicInfo0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::fmt::Arguments<'#local1,>
struct s_ZRG2cE9core0_0_03fmt9Arguments0g  {
	/*@0*/SLICE_PTR _0; // &'#local1 [&'#local1 str]
	/*@16*/struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g _1; // ::"core-0_0_0"::option::Option<&'#local1 [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>/*E*/
	/*@32*/SLICE_PTR _2; // &'#local1 [::"core-0_0_0"::fmt::ArgumentV1<'#local1,>/*S*/]
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03fmt9Arguments0g[ (sizeof(struct s_ZRG2cE9core0_0_03fmt9Arguments0g) == 48) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03fmt9Arguments0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03fmt9Arguments0g) == 8) ? 1 : -1 ];
 // (::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, )
typedef struct TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa  {
	/*@0*/struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa _0; // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
} TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa ;
typedef char sizeof_assert_TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa [ (sizeof(TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa ) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Ok<(),::"core-0_0_0"::fmt::Error/*S*/,>
struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ()
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::fmt::Error
struct s_ZRG2cE9core0_0_03fmt5Error0g  {
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG2cE9core0_0_03fmt5Error0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03fmt5Error0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Err<(),::"core-0_0_0"::fmt::Error/*S*/,>
struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ::"core-0_0_0"::fmt::Error/*S*/
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
// enum ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>
struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g {
	union {
		struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g var_0;
		struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g var_1;
		uint8_t TAG;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g[ (sizeof(struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::any::TypeId
struct s_ZRG2cE9core0_0_03any6TypeId0g  {
	/*@0*/uint64_t _0; // u64
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03any6TypeId0g[ (sizeof(struct s_ZRG2cE9core0_0_03any6TypeId0g) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03any6TypeId0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03any6TypeId0g) == 8) ? 1 : -1 ];
struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g;
// struct ::"core-0_0_0"::panic::#0::NoPayload
struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g  {
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG3cE9core0_0_05panicB_09NoPayload0g[ (ALIGNOF(struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g) == 1) ? 1 : -1 ];
typedef struct t_ZRTA2BsCy  { SLICE_PTR  DATA[2]; } t_ZRTA2BsCy ; // [&'static str; 2]
 // (&'static str, u32, u32, )
typedef struct TUP_3_ZRTBsCy_ZRTCe_ZRTCe  {
	/*@0*/uint32_t _1; // u32
	/*@4*/uint32_t _2; // u32
	/*@8*/SLICE_PTR _0; // &'static str
} TUP_3_ZRTBsCy_ZRTCe_ZRTCe ;
typedef char sizeof_assert_TUP_3_ZRTBsCy_ZRTCe_ZRTCe [ (sizeof(TUP_3_ZRTBsCy_ZRTCe_ZRTCe ) == 24) ? 1 : -1 ];
typedef void (*t_ZRTF1PoT0T0 )( tUNIT * ); // extern "Rust" fn(*move (), ) -> ()
typedef struct s_ZRG2cE9core0_0_03any6TypeId0g  (*t_ZRTF1BsT0G2cE9core0_0_03any6TypeId0g )( tUNIT * ); // for<'elided#0,> extern "Rust" fn(&'H0 (), ) -> ::"core-0_0_0"::any::TypeId/*S*/
// struct ::"core-0_0_0"::any::Any#vtable
struct s_ZRG2cE9core0_0_03anyD9Anyvtable0g  {
	/*@0*/t_ZRTF1PoT0T0 _0; // extern "Rust" fn(*move (), ) -> ()
	/*@8*/uintptr_t _1; // usize
	/*@16*/uintptr_t _2; // usize
	/*@24*/t_ZRTF1BsT0G2cE9core0_0_03any6TypeId0g _3; // for<'elided#0,> extern "Rust" fn(&'H0 (), ) -> ::"core-0_0_0"::any::TypeId/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03anyD9Anyvtable0g[ (sizeof(struct s_ZRG2cE9core0_0_03anyD9Anyvtable0g) == 32) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03anyD9Anyvtable0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03anyD9Anyvtable0g) == 8) ? 1 : -1 ];
tTYPEID __typeid_ZRTG3cE9core0_0_05panicB_09NoPayload0g __attribute__((weak));
// PROTO extern "Rust" ::"alloc_system-0_0_0"::platform::aligned_malloc<'#local5,>
uint8_t * ZRG2cM17alloc_system0_0_08platform14aligned_malloc0g(
		struct s_ZRG2cE9core0_0_05alloc6Layout0g *arg0 // &'#local5 ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> *mut u8
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ /*- */>::realloc_fallback<'#omitted,>
uint8_t * ZRIG1cM17alloc_system0_0_06System0g16realloc_fallback0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		uint8_t *arg1, // *mut u8
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> *mut u8
;
// PROTO extern "Rust" <::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/ /*- <'static,>*/>::new<'static,&'static str,>
static struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  ZRIG2cE9core0_0_03fmt10ArgumentV10g3new1gBsCy(
		SLICE_PTR *arg0, // &'static &'static str
		t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g arg1 // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 &'static str, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
		) // -> ::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/
;
// PROTO extern "Rust" <::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>*/>::ok_or<::"core-0_0_0"::alloc::AllocErr/*S*/,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRIG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa5ok_or1gG2c_A5alloc8AllocErr0g(
		struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa arg0, // ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/
		struct s_ZRG2cE9core0_0_05alloc8AllocErr0g arg1 // ::"core-0_0_0"::alloc::AllocErr/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"core-0_0_0"::panic::#0::NoPayload/*S*/ /*- */>::#drop_glue
static void  ZRIG3cE9core0_0_05panicB_09NoPayload0gA9drop_glue0g(
		struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g *arg0 // &'#omitted move ::"core-0_0_0"::panic::#0::NoPayload/*S*/
		) // -> ()
;
// PROTO extern "Rust" <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/ /*- <u8,>*/>::new
static struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa  ZRIG2cE9core0_0_03ptr7NonNull1gCa3new0g(
		uint8_t *arg0 // *mut u8
		) // -> ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>*/>::map<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::closure#alloc_excess_1<'#local1,>/*S*/,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRIG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g3map2gG2c_A_F6Excess0gG2c_A_FH21closureallo$6899d3f07f58b0c8(
		struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g arg0, // ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
		struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_10g arg1 // ::"core-0_0_0"::alloc::closure#alloc_excess_1<'#local1,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>*/>::map<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::closure#realloc_excess_0<'#local2,>/*S*/,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRIG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g3map2gG2c_A_F6Excess0gG2c_A_FH23closurereal$83ff099e8a2adbb(
		struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g arg0, // ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
		struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_00g arg1 // ::"core-0_0_0"::alloc::closure#realloc_excess_0<'#local2,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <usize as ::"core-0_0_0"::cmp::Ord>::min
static uintptr_t  ZRQCu2cE9core0_0_03cmp3Ord0g3min0g(
		uintptr_t arg0, // usize
		uintptr_t arg1 // usize
		) // -> usize
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc<'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g_D0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc_excess<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g12alloc_excess0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc_zeroed<'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g12alloc_zeroed0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::dealloc<'#omitted,>
void  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g7dealloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ()
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::grow_in_place<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g13grow_in_place0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::realloc<'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g7realloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::realloc_excess<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g14realloc_excess0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::shrink_in_place<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g15shrink_in_place0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::usable_size<'#omitted,'#omitted,>
static TUP_2_ZRTCu_ZRTCu  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g11usable_size0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g *arg1 // &'#omitted ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> (usize, usize, )
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc<'#omitted,>
uint8_t * ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g_D0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> *mut u8
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc_zeroed<'#omitted,>
uint8_t * ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g12alloc_zeroed0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> *mut u8
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::dealloc<'#omitted,>
void  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g7dealloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		uint8_t *arg1, // *mut u8
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ()
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::realloc<'#omitted,>
uint8_t * ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g7realloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		uint8_t *arg1, // *mut u8
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> *mut u8
;
// PROTO extern "Rust" <::"core-0_0_0"::panic::#0::NoPayload/*S*/ as ::"core-0_0_0"::any::Any>::get_type_id<'#omitted,>
static struct s_ZRG2cE9core0_0_03any6TypeId0g  ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0g11get_type_id0g(
		struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g *arg0 // &'#omitted ::"core-0_0_0"::panic::#0::NoPayload/*S*/
		) // -> ::"core-0_0_0"::any::TypeId/*S*/
;
// PROTO extern "Rust" <&'static str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  ZRQBsCy2cE9core0_0_03fmt7Display0g_B0g(
		SLICE_PTR *arg0, // &'static &'static str
		struct s_ZRG2cE9core0_0_03fmt9Formatter0g *arg1 // &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
;
// EXTERN extern "Rust" ::"core-0_0_0"::panicking::#0::panic_impl<'#local3,>
extern tBANG  ZRG3cE9core0_0_09panickingB_010panic_impl0g(
		struct s_ZRG2cE9core0_0_05panic9PanicInfo0g *arg0 // &'#local3 ::"core-0_0_0"::panic::PanicInfo<'#local3,>/*S*/
		) // -> !
 asm("_panic_impl");
// EXTERN extern "C" ::"libc-0_0_0_H4"::calloc
extern struct e_ZRG1cE12libc0_0_0_H46c_void0g * ZRG1cE12libc0_0_0_H46calloc0g(
		uintptr_t arg0, // usize
		uintptr_t arg1 // usize
		) // -> *mut ::"libc-0_0_0_H4"::c_void/*E*/
 asm("_calloc");
// EXTERN extern "C" ::"libc-0_0_0_H4"::free
extern void  ZRG1cE12libc0_0_0_H44free0g(
		struct e_ZRG1cE12libc0_0_0_H46c_void0g *arg0 // *mut ::"libc-0_0_0_H4"::c_void/*E*/
		) // -> ()
 asm("_free");
// EXTERN extern "C" ::"libc-0_0_0_H4"::malloc
extern struct e_ZRG1cE12libc0_0_0_H46c_void0g * ZRG1cE12libc0_0_0_H46malloc0g(
		uintptr_t arg0 // usize
		) // -> *mut ::"libc-0_0_0_H4"::c_void/*E*/
 asm("_malloc");
// EXTERN extern "C" ::"libc-0_0_0_H4"::realloc
extern struct e_ZRG1cE12libc0_0_0_H46c_void0g * ZRG1cE12libc0_0_0_H47realloc0g(
		struct e_ZRG1cE12libc0_0_0_H46c_void0g *arg0, // *mut ::"libc-0_0_0_H4"::c_void/*E*/
		uintptr_t arg1 // usize
		) // -> *mut ::"libc-0_0_0_H4"::c_void/*E*/
 asm("_realloc");
// EXTERN extern "C" ::"libc-0_0_0_H4"::unix::posix_memalign
extern int32_t  ZRG2cE12libc0_0_0_H44unix14posix_memalign0g(
		struct e_ZRG1cE12libc0_0_0_H46c_void0g **arg0, // *mut *mut ::"libc-0_0_0_H4"::c_void/*E*/
		uintptr_t arg1, // usize
		uintptr_t arg2 // usize
		) // -> i32
 asm("_posix_memalign");
// EXTERN extern "Rust" <str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>
extern struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  ZRQCy2cE9core0_0_03fmt7Display0g_B0g(
		SLICE_PTR arg0, // &'static str
		struct s_ZRG2cE9core0_0_03fmt9Formatter0g *arg1 // &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
;
// EXTERN extern "Rust" <::"core-0_0_0"::alloc::Layout/*S*/ as ::"core-0_0_0"::clone::Clone>::clone<'#local4,>
extern struct s_ZRG2cE9core0_0_05alloc6Layout0g  ZRQG2cE9core0_0_05alloc6Layout0g2c_A5clone5Clone0g_D0g(
		struct s_ZRG2cE9core0_0_05alloc6Layout0g *arg0 // &'#local4 ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::alloc::Layout/*S*/
;
// EXTERN extern "Rust" <::"core-0_0_0"::alloc::closure#alloc_excess_1<'#local1,>/*S*/ as ::"core-0_0_0"::ops::function::FnOnce<(::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, ),>>::call_once
extern struct s_ZRG2cE9core0_0_05alloc6Excess0g  ZRQG2cE9core0_0_05allocH21closurealloc_excess_10g3c_A3ops8function6FnOnce1gT1G2c_A3ptr7NonNull1gCa9call_once0g(
		struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_10g arg0, // ::"core-0_0_0"::alloc::closure#alloc_excess_1<'#local1,>/*S*/
		TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa arg1 // (::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, )
		) // -> ::"core-0_0_0"::alloc::Excess/*S*/
;
// EXTERN extern "Rust" <::"core-0_0_0"::alloc::closure#realloc_excess_0<'#local2,>/*S*/ as ::"core-0_0_0"::ops::function::FnOnce<(::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, ),>>::call_once
extern struct s_ZRG2cE9core0_0_05alloc6Excess0g  ZRQG2cE9core0_0_05allocH23closurerealloc_excess_00g3c_A3ops8function6FnOnce1gT1G2c_A3ptr7NonNull1gCa9call_once0g(
		struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_00g arg0, // ::"core-0_0_0"::alloc::closure#realloc_excess_0<'#local2,>/*S*/
		TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa arg1 // (::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, )
		) // -> ::"core-0_0_0"::alloc::Excess/*S*/
;
extern union u_static_ZRG3cE9core0_0_05allocB_49FRAGMENTS0g{ t_ZRTA2BsCy val; uintptr_t raw[4]; } ZRG3cE9core0_0_05allocB_49FRAGMENTS0g;	// static ::"core-0_0_0"::alloc::#4::FRAGMENTS : [&'static str; 2]
extern union u_static_ZRG3cE9core0_0_05allocB_59FRAGMENTS0g{ t_ZRTA2BsCy val; uintptr_t raw[4]; } ZRG3cE9core0_0_05allocB_59FRAGMENTS0g;	// static ::"core-0_0_0"::alloc::#5::FRAGMENTS : [&'static str; 2]
extern union u_static_ZRG2cE9core0_0_05allocF6const20g{ SLICE_PTR val; uintptr_t raw[2]; } ZRG2cE9core0_0_05allocF6const20g;	// static ::"core-0_0_0"::alloc::const#2 : &'static str
extern union u_static_ZRG2cE9core0_0_05allocF6const30g{ TUP_3_ZRTBsCy_ZRTCe_ZRTCe val; uintptr_t raw[3]; } ZRG2cE9core0_0_05allocF6const30g;	// static ::"core-0_0_0"::alloc::const#3 : (&'static str, u32, u32, )
extern union u_static_ZRG2cE9core0_0_05allocF6const40g{ SLICE_PTR val; uintptr_t raw[2]; } ZRG2cE9core0_0_05allocF6const40g;	// static ::"core-0_0_0"::alloc::const#4 : &'static str
extern union u_static_ZRG2cE9core0_0_05allocF6const50g{ TUP_3_ZRTBsCy_ZRTCe_ZRTCe val; uintptr_t raw[3]; } ZRG2cE9core0_0_05allocF6const50g;	// static ::"core-0_0_0"::alloc::const#5 : (&'static str, u32, u32, )
extern union u_static_ZRG2cE9core0_0_05panicF6const00g{ struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g val; uint8_t raw[0]; } ZRG2cE9core0_0_05panicF6const00g;	// static ::"core-0_0_0"::panic::const#0 : ::"core-0_0_0"::panic::#0::NoPayload/*S*/
__attribute__((weak)) union u_static_ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0gG6vtable0g{ struct s_ZRG2cE9core0_0_03anyD9Anyvtable0g val; uintptr_t raw[4]; } ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0gG6vtable0g;	// static <::"core-0_0_0"::panic::#0::NoPayload/*S*/ as ::"core-0_0_0"::any::Any>::vtable# : ::"core-0_0_0"::any::Any#vtable/*S*/
union u_static_ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0gG6vtable0g ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0gG6vtable0g = { .raw = {(uintptr_t)&ZRIG3cE9core0_0_05panicB_09NoPayload0gA9drop_glue0g,0x0ull,0x1ull,(uintptr_t)&ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0g11get_type_id0g} };	// static <::"core-0_0_0"::panic::#0::NoPayload/*S*/ as ::"core-0_0_0"::any::Any>::vtable# : ::"core-0_0_0"::any::Any#vtable/*S*/ = 0010000000000000 0000000000000000 0100000000000000 0010000000000000{@0x0+8 = &<::"core-0_0_0"::panic::#0::NoPayload/*S*/ /*- */>::#drop_glue, @0x18+8 = &<::"core-0_0_0"::panic::#0::NoPayload/*S*/ as ::"core-0_0_0"::any::Any>::get_type_id}
// ::"alloc_system-0_0_0"::platform::aligned_malloc<'#local5,>
uint8_t * ZRG2cM17alloc_system0_0_08platform14aligned_malloc0g(
		struct s_ZRG2cE9core0_0_05alloc6Layout0g *arg0 // &'#local5 ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> *mut u8

{
	uint8_t *rv;
	struct e_ZRG1cE12libc0_0_0_H46c_void0g *var0;	// *mut ::"libc-0_0_0_H4"::c_void/*E*/
	RUST_BOOL var1;	// bool
	struct e_ZRG1cE12libc0_0_0_H46c_void0g **var2;	// &'#local0 mut *mut ::"libc-0_0_0_H4"::c_void/*E*/
	struct e_ZRG1cE12libc0_0_0_H46c_void0g **var3;	// *mut *mut ::"libc-0_0_0_H4"::c_void/*E*/
	int32_t var4;	// i32
	uintptr_t var5;	// usize
	struct s_ZRG2cE9core0_0_03num12NonZeroUsize0g var6;	// ::"core-0_0_0"::num::NonZeroUsize/*S*/
	uintptr_t var7;	// usize
	var5 = 0x0ull;	// _5 = Constant(0x0 usize)
	var0 = (struct e_ZRG1cE12libc0_0_0_H46c_void0g *)var5;	// _0 = Cast(_5 as *mut ::"libc-0_0_0_H4"::c_void/*E*/)
	var2 = & var0;	// _2 = Borrow(Unique, _0)
	var3 = (struct e_ZRG1cE12libc0_0_0_H46c_void0g **)var2;	// _3 = Cast(_2 as *mut *mut ::"libc-0_0_0_H4"::c_void/*E*/)
	var6 = arg0->_1;	// _6 = Use(a0*.1)
	var4 = ZRG2cE12libc0_0_0_H44unix14posix_memalign0g( var3, var6._0._0, arg0->_0 );
	// ^ Call( _4 = ::"libc-0_0_0_H4"::unix::posix_memalign( _3, _6.0.0, a0*.0, ), bb1, bb2)
	var1 = var4 != 0;	// _1 = BinOp(_4 NE +0 i32)
	if(var1) goto bb3; else goto bb4;
	// ^ If( _1 : 3, 4)
bb2: _Unwind_Resume(); // Diverge
bb3:
	var7 = 0x0ull;	// _7 = Constant(0x0 usize)
	rv = (uint8_t *)var7;	// retval = Cast(_7 as *mut u8)
	return rv;
	// ^ Return
bb4:
	rv = (uint8_t *)var0;	// retval = Cast(_0 as *mut u8)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ /*- */>::realloc_fallback<'#omitted,>
uint8_t * ZRIG1cM17alloc_system0_0_06System0g16realloc_fallback0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		uint8_t *arg1, // *mut u8
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> *mut u8

{
	uint8_t *rv;
	uint8_t *var0;	// *mut u8
	RUST_BOOL var1;	// bool
	uint8_t *var2;	// *const u8
	tUNIT var3 = {0};	// ()
	tUNIT var4 = {0};	// ()
	struct s_ZRG2cE9core0_0_05alloc6Layout0g var5;	// ::"core-0_0_0"::alloc::Layout/*S*/
	struct s_ZRG2cE9core0_0_03num12NonZeroUsize0g var6;	// ::"core-0_0_0"::num::NonZeroUsize/*S*/
	struct s_ZRG2cE9core0_0_07nonzero7NonZero1gCu var7;	// ::"core-0_0_0"::nonzero::NonZero<usize,>/*S*/
	uint8_t *var8;	// *mut u8
	uintptr_t var9;	// usize
	uintptr_t var10;	// usize
	struct e_ZRG1cE12libc0_0_0_H46c_void0g *var11;	// *mut ::"libc-0_0_0_H4"::c_void/*E*/
	var7._0 = arg2._1._0._0;	// _7 = Struct(::"core-0_0_0"::nonzero::NonZero<usize,>, {a2.1.0.0})
	var6._0 = var7;	// _6 = Struct(::"core-0_0_0"::num::NonZeroUsize, {_7})
	var5._0 = arg3;
	var5._1 = var6;	// _5 = Struct(::"core-0_0_0"::alloc::Layout, {a3, _6})
	var0 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g_D0g( arg0, var5 );
	// ^ Call( _0 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc<'M0,>( a0, _5, ), bb1, bb2)
	var9 = 0x0ull;	// _9 = Constant(0x0 usize)
	var8 = (uint8_t *)var9;	// _8 = Cast(_9 as *mut u8)
	var1 = var0 == var8;	// _1 = BinOp(_0 EQ _8)
	if(var1) goto bb6; else goto bb3;
	// ^ If( _1 : 6, 3)
bb2: _Unwind_Resume(); // Diverge
bb3:
	var10 = ZRQCu2cE9core0_0_03cmp3Ord0g3min0g( arg2._0, arg3 );
	// ^ Call( _10 = <usize as ::"core-0_0_0"::cmp::Ord>::min( a2.0, a3, ), bb4, bb2)
	var2 = (uint8_t *)arg1;	// _2 = Cast(a1 as *const u8)
	memcpy( var0, var2, var10 * sizeof(uint8_t ));
	// ^ Call( _3 = "copy_nonoverlapping"::<u8,>( _2, _0, _10, ), bb5, bb2)
	var11 = (struct e_ZRG1cE12libc0_0_0_H46c_void0g *)arg1;	// _11 = Cast(a1 as *mut ::"libc-0_0_0_H4"::c_void/*E*/)
	ZRG1cE12libc0_0_0_H44free0g( var11 );
	// ^ Call( _4 = ::"libc-0_0_0_H4"::free( _11, ), bb6, bb2)
bb6:
	rv = var0;	// retval = Use(_0)
	return rv;
	// ^ Return
}
// <::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/ /*- <'static,>*/>::new<'static,&'static str,>
static struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  ZRIG2cE9core0_0_03fmt10ArgumentV10g3new1gBsCy(
		SLICE_PTR *arg0, // &'static &'static str
		t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g arg1 // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 &'static str, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
		) // -> ::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/

{
	struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g rv;
	t_ZRTF2BsG2cE9core0_0_03fmt4Void0gBuG2c_A_B9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g var0;	// for<'elided#0,'elided#1,> extern "Rust" fn(&'static ::"core-0_0_0"::fmt::Void/*S*/, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_03fmt4Void0g *var1;	// &'static ::"core-0_0_0"::fmt::Void/*S*/
	memcpy( &var0, &arg1, sizeof(t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g ));
	// ^ Call( _0 = "transmute"::<for<'elided#0,'elided#1,> extern "Rust" fn(&'static &'static str, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/,for<'elided#0,'elided#1,> extern "Rust" fn(&'static ::"core-0_0_0"::fmt::Void/*S*/, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/,>( a1, ), bb1, bb3)
	var1 = (void*)arg0;
	// ^ Call( _1 = "transmute"::<&'static &'static str,&'static ::"core-0_0_0"::fmt::Void/*S*/,>( a0, ), bb2, bb3)
	rv._0 = var1;
	rv._1 = var0;	// retval = Struct(::"core-0_0_0"::fmt::ArgumentV1<'static,>, {_1, _0})
	return rv;
	// ^ Return
bb3: _Unwind_Resume(); // Diverge
}
// <::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>*/>::ok_or<::"core-0_0_0"::alloc::AllocErr/*S*/,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRIG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa5ok_or1gG2c_A5alloc8AllocErr0g(
		struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa arg0, // ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/
		struct s_ZRG2cE9core0_0_05alloc8AllocErr0g arg1 // ::"core-0_0_0"::alloc::AllocErr/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g rv;
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g var0;	// ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
	bool df0 = 1;
	if( arg0.DATA.var_1._0._0._0 != 0 )
		goto bb2;
	else
		goto bb1;
	// ^ Switch( a0 : 0 => bb1, 1 => bb2, )
bb1:
	memset(&var0, 0, sizeof(struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g ));	// _0 = Variant(::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,> #1, {a1})
	df0 = 0;
	goto bb3;
	// ^ Goto(3)
bb2:
	var0.DATA.var_0._0 = arg0.DATA.var_1._0;	// _0 = Variant(::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,> #0, {a0#1.0})
	// ^ Goto(3)
bb3:
	rv = var0;	// retval = Use(_0)
	if( df0 ) {
	}
	// ^ drop(a1 IF df$0)
	return rv;
	// ^ Return
}
// <::"core-0_0_0"::panic::#0::NoPayload/*S*/ /*- */>::#drop_glue
static void  ZRIG3cE9core0_0_05panicB_09NoPayload0gA9drop_glue0g(
		struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g *arg0 // &'#omitted move ::"core-0_0_0"::panic::#0::NoPayload/*S*/
		) // -> ()

{
	tUNIT rv;
	/* ZST assign */
	return ;
	// ^ Return
}
// <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/ /*- <u8,>*/>::new
static struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa  ZRIG2cE9core0_0_03ptr7NonNull1gCa3new0g(
		uint8_t *arg0 // *mut u8
		) // -> ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa rv;
	RUST_BOOL var0;	// bool
	uint8_t *var1;	// *const u8
	struct s_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa var2;	// ::"core-0_0_0"::nonzero::NonZero<*const u8,>/*S*/
	struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa var3;	// ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
	uint8_t *var4;	// *mut u8
	uintptr_t var5;	// usize
	var5 = 0x0ull;	// _5 = Constant(0x0 usize)
	var4 = (uint8_t *)var5;	// _4 = Cast(_5 as *mut u8)
	var0 = arg0 == var4;	// _0 = BinOp(a0 EQ _4)
	if(var0) goto bb1; else goto bb2;
	// ^ If( _0 : 1, 2)
bb1:
	memset(&rv, 0, sizeof(struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa ));	// retval = Variant(::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,> #0, {})
	return rv;
	// ^ Return
bb2:
	var1 = (uint8_t *)arg0;	// _1 = Cast(a0 as *const u8)
	var2._0 = var1;	// _2 = Struct(::"core-0_0_0"::nonzero::NonZero<*const u8,>, {_1})
	var3._0 = var2;	// _3 = Struct(::"core-0_0_0"::ptr::NonNull<u8,>, {_2})
	rv.DATA.var_1._0 = var3;	// retval = Variant(::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,> #1, {_3})
	return rv;
	// ^ Return
}
// <::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>*/>::map<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::closure#alloc_excess_1<'#local1,>/*S*/,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRIG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g3map2gG2c_A_F6Excess0gG2c_A_FH21closureallo$6899d3f07f58b0c8(
		struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g arg0, // ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
		struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_10g arg1 // ::"core-0_0_0"::alloc::closure#alloc_excess_1<'#local1,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g rv;
	TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa var0;	// (::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, )
	struct s_ZRG2cE9core0_0_05alloc6Excess0g var1;	// ::"core-0_0_0"::alloc::Excess/*S*/
	if( arg0.DATA.var_0._0._0._0 != 0 )
		goto bb1;
	else
		goto bb3;
	// ^ Switch( a0 : 0 => bb1, 1 => bb3, )
bb1:
	;
	var0._0 = arg0.DATA.var_0._0;	// _0 = Tuple(a0#0.0)
	var1 = ZRQG2cE9core0_0_05allocH21closurealloc_excess_10g3c_A3ops8function6FnOnce1gT1G2c_A3ptr7NonNull1gCa9call_once0g( arg1, var0 );
	// ^ Call( _1 = <::"core-0_0_0"::alloc::closure#alloc_excess_1<'#local1,>/*S*/ as ::"core-0_0_0"::ops::function::FnOnce<(::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, ),>>::call_once( a1, _0, ), bb2, bb4)
	rv.DATA.var_0._0 = var1;	// retval = Variant(::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,> #0, {_1})
	return rv;
	// ^ Return
bb3:
	memset(&rv, 0, sizeof(struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g ));	// retval = Variant(::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,> #1, {a0#1.0})
	return rv;
	// ^ Return
bb4: _Unwind_Resume(); // Diverge
}
// <::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>*/>::map<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::closure#realloc_excess_0<'#local2,>/*S*/,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRIG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g3map2gG2c_A_F6Excess0gG2c_A_FH23closurereal$83ff099e8a2adbb(
		struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g arg0, // ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
		struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_00g arg1 // ::"core-0_0_0"::alloc::closure#realloc_excess_0<'#local2,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g rv;
	TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa var0;	// (::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, )
	struct s_ZRG2cE9core0_0_05alloc6Excess0g var1;	// ::"core-0_0_0"::alloc::Excess/*S*/
	if( arg0.DATA.var_0._0._0._0 != 0 )
		goto bb1;
	else
		goto bb3;
	// ^ Switch( a0 : 0 => bb1, 1 => bb3, )
bb1:
	;
	var0._0 = arg0.DATA.var_0._0;	// _0 = Tuple(a0#0.0)
	var1 = ZRQG2cE9core0_0_05allocH23closurerealloc_excess_00g3c_A3ops8function6FnOnce1gT1G2c_A3ptr7NonNull1gCa9call_once0g( arg1, var0 );
	// ^ Call( _1 = <::"core-0_0_0"::alloc::closure#realloc_excess_0<'#local2,>/*S*/ as ::"core-0_0_0"::ops::function::FnOnce<(::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, ),>>::call_once( a1, _0, ), bb2, bb4)
	rv.DATA.var_0._0 = var1;	// retval = Variant(::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,> #0, {_1})
	return rv;
	// ^ Return
bb3:
	memset(&rv, 0, sizeof(struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g ));	// retval = Variant(::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,> #1, {a0#1.0})
	return rv;
	// ^ Return
bb4: _Unwind_Resume(); // Diverge
}
// <usize as ::"core-0_0_0"::cmp::Ord>::min
static uintptr_t  ZRQCu2cE9core0_0_03cmp3Ord0g3min0g(
		uintptr_t arg0, // usize
		uintptr_t arg1 // usize
		) // -> usize

{
	uintptr_t rv;
	RUST_BOOL var0;	// bool
	var0 = arg0 <= arg1;	// _0 = BinOp(a0 LE a1)
	if(var0) goto bb1; else goto bb2;
	// ^ If( _0 : 1, 2)
bb1:
	rv = arg0;	// retval = Use(a0)
	return rv;
	// ^ Return
bb2:
	rv = arg1;	// retval = Use(a1)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc<'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g_D0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g rv;
	struct s_ZRG1cM17alloc_system0_0_06System0g *var0;	// &'M0 ::"alloc_system-0_0_0"::System/*S*/
	uint8_t *var1;	// *mut u8
	struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa var2;	// ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_05alloc8AllocErr0g var3 = {0};	// ::"core-0_0_0"::alloc::AllocErr/*S*/
	var0 = arg0;	// _0 = Borrow(Shared, a0*)
	var1 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g_D0g( var0, arg1 );
	// ^ Call( _1 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc<'M0,>( _0, a1, ), bb1, bb4)
	var2 = ZRIG2cE9core0_0_03ptr7NonNull1gCa3new0g( var1 );
	// ^ Call( _2 = <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/ /*- <u8,>*/>::new( _1, ), bb2, bb4)
	/* ZST assign */
	{
		struct s_ZRG2cE9core0_0_05alloc8AllocErr0g zarg1 = {0};
		rv = ZRIG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa5ok_or1gG2c_A5alloc8AllocErr0g( var2, zarg1 );
	}
	// ^ Call( retval = <::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>*/>::ok_or<::"core-0_0_0"::alloc::AllocErr/*S*/,>( _2, _3, ), bb3, bb4)
	// ^ drop(a0)
	return rv;
	// ^ Return
bb4: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc_excess<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g12alloc_excess0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g rv;
	TUP_2_ZRTCu_ZRTCu var0;	// (usize, usize, )
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g var1;	// ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
	TUP_2_ZRTCu_ZRTCu *var2;	// &'#ivar1 (usize, usize, )
	struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_10g var3;	// ::"core-0_0_0"::alloc::closure#alloc_excess_1<'#local1,>/*S*/
	;
	var0._0 = arg1._0;
	var0._1 = arg1._0;	// _0 = Tuple(a1.0, a1.0)
	var1 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g_D0g( arg0, arg1 );
	// ^ Call( _1 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc<'#omitted,>( a0, a1, ), bb1, bb3)
	var2 = & var0;	// _2 = Borrow(Shared, _0)
	var3._0 = var2;	// _3 = Struct(::"core-0_0_0"::alloc::closure#alloc_excess_1<'#local1,>, {_2})
	rv = ZRIG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g3map2gG2c_A_F6Excess0gG2c_A_FH21closureallo$6899d3f07f58b0c8( var1, var3 );
	// ^ Call( retval = <::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>*/>::map<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::closure#alloc_excess_1<'#local1,>/*S*/,>( _1, _3, ), bb2, bb3)
	return rv;
	// ^ Return
bb3: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc_zeroed<'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g12alloc_zeroed0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g rv;
	struct s_ZRG1cM17alloc_system0_0_06System0g *var0;	// &'M0 ::"alloc_system-0_0_0"::System/*S*/
	uint8_t *var1;	// *mut u8
	struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa var2;	// ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_05alloc8AllocErr0g var3 = {0};	// ::"core-0_0_0"::alloc::AllocErr/*S*/
	var0 = arg0;	// _0 = Borrow(Shared, a0*)
	var1 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g12alloc_zeroed0g( var0, arg1 );
	// ^ Call( _1 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc_zeroed<'M0,>( _0, a1, ), bb1, bb4)
	var2 = ZRIG2cE9core0_0_03ptr7NonNull1gCa3new0g( var1 );
	// ^ Call( _2 = <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/ /*- <u8,>*/>::new( _1, ), bb2, bb4)
	/* ZST assign */
	{
		struct s_ZRG2cE9core0_0_05alloc8AllocErr0g zarg1 = {0};
		rv = ZRIG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa5ok_or1gG2c_A5alloc8AllocErr0g( var2, zarg1 );
	}
	// ^ Call( retval = <::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>*/>::ok_or<::"core-0_0_0"::alloc::AllocErr/*S*/,>( _2, _3, ), bb3, bb4)
	// ^ drop(a0)
	return rv;
	// ^ Return
bb4: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::dealloc<'#omitted,>
void  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g7dealloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ()

{
	tUNIT rv;
	struct e_ZRG1cE12libc0_0_0_H46c_void0g *var0;	// *mut ::"libc-0_0_0_H4"::c_void/*E*/
	uint8_t *var1;	// *mut u8
	var1 = (uint8_t *)arg1._0._0;	// _1 = Cast(a1.0.0 as *mut u8)
	var0 = (struct e_ZRG1cE12libc0_0_0_H46c_void0g *)var1;	// _0 = Cast(_1 as *mut ::"libc-0_0_0_H4"::c_void/*E*/)
	ZRG1cE12libc0_0_0_H44free0g( var0 );
	// ^ Call( retval = ::"libc-0_0_0_H4"::free( _0, ), bb1, bb2)
	// ^ drop(a0)
	return ;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::grow_in_place<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g13grow_in_place0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g rv;
	RUST_BOOL var0;	// bool
	t_ZRTfQBsCy2cE9core0_0_03fmt7Display0g_B0g var1 = {0};	// fn{<&'static str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>}
	t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g var2;	// for<'elided#0,'elided#1,> extern "Rust" fn(&'static &'static str, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g var3;	// ::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/
	t_ZRTA1G2cE9core0_0_03fmt10ArgumentV10g var4;	// [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/; 1]
	t_ZRTA1G2cE9core0_0_03fmt10ArgumentV10g *var5;	// &'#local1 [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/; 1]
	tUNIT var6 = {0};	// ()
	struct s_ZRG2cE9core0_0_05alloc20CannotReallocInPlace0g var7 = {0};	// ::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/
	struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g var8;	// ::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>/*E*/
	SLICE_PTR var9;	// &'static [&'static str]
	SLICE_PTR var10;	// &'#local1 [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/]
	struct s_ZRG2cE9core0_0_05panic9PanicInfo0g var11;	// ::"core-0_0_0"::panic::PanicInfo<'#local2,>/*S*/
	struct s_ZRG2cE9core0_0_03fmt9Arguments0g *var12;	// &'#local0 ::"core-0_0_0"::fmt::Arguments<'#local1,>/*S*/
	struct s_ZRG2cE9core0_0_05panic9PanicInfo0g *var13;	// &'#local1 ::"core-0_0_0"::panic::PanicInfo<'#local2,>/*S*/
	tBANG var14 = {0};	// !
	TRAITOBJ_PTR var15;	// &'#local2 dyn (::"core-0_0_0"::any::Any+::"core-0_0_0"::marker::Send)
	struct s_ZRG2cE9core0_0_05panic8Location0g var16;	// ::"core-0_0_0"::panic::Location<'static,>/*S*/
	struct e_ZRG2cE9core0_0_06option6Option1gBsG2c_A3fmt9Arguments0g var17;	// ::"core-0_0_0"::option::Option<&'#local0 ::"core-0_0_0"::fmt::Arguments<'#local1,>/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_03fmt9Arguments0g var18;	// ::"core-0_0_0"::fmt::Arguments<'#local1,>/*S*/
	var0 = arg3 >= arg2._0;	// _0 = BinOp(a3 GE a2.0)
	if(var0) goto bb1; else goto bb2;
	// ^ If( _0 : 1, 2)
bb1:
	var0 = arg3 <= arg2._0;	// _0 = BinOp(a3 LE a2.0)
	if(var0) goto bb5; else goto bb6;
	// ^ If( _0 : 5, 6)
bb2:
	var9 = make_sliceptr(&ZRG3cE9core0_0_05allocB_49FRAGMENTS0g.val, 0x2ull);	// _9 = MakeDst(&::"core-0_0_0"::alloc::#4::FRAGMENTS, 0x2 usize)
	/* ZST assign */
	var2 = ZRQBsCy2cE9core0_0_03fmt7Display0g_B0g;	// _2 = Cast(_1 as for<'elided#0,'elided#1,> extern "Rust" fn(&'static &'static str, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/)
	var3 = ZRIG2cE9core0_0_03fmt10ArgumentV10g3new1gBsCy( &ZRG2cE9core0_0_05allocF6const40g.val, var2 );
	// ^ Call( _3 = <::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/ /*- <'static,>*/>::new<'static,&'static str,>( &::"core-0_0_0"::alloc::const#4, _2, ), bb3, bb4)
	var4.DATA[0] = var3;	// _4 = Array(_3)
	var5 = & var4;	// _5 = Borrow(Shared, _4)
	var10 = make_sliceptr(var5, 0x1ull);	// _10 = MakeDst(_5, 0x1 usize)
	memset(&var8, 0, sizeof(struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g ));	// _8 = Variant(::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],> #0, {})
	var18._0 = var9;
	var18._1 = var8;
	var18._2 = var10;	// _18 = Struct(::"core-0_0_0"::fmt::Arguments<'#local1,>, {_9, _8, _10})
	var12 = & var18;	// _12 = Borrow(Shared, _18)
	var17.DATA.var_1._0 = var12;	// _17 = Variant(::"core-0_0_0"::option::Option<&'#local0 ::"core-0_0_0"::fmt::Arguments<'#local1,>/*S*/,> #1, {_12})
	var16._0 = ZRG2cE9core0_0_05allocF6const50g.val._0;
	var16._1 = ZRG2cE9core0_0_05allocF6const50g.val._1;
	var16._2 = ZRG2cE9core0_0_05allocF6const50g.val._2;	// _16 = Struct(::"core-0_0_0"::panic::Location<'static,>, {(::"core-0_0_0"::alloc::const#5).0, (::"core-0_0_0"::alloc::const#5).1, (::"core-0_0_0"::alloc::const#5).2})
	var15 = make_traitobjptr(&ZRG2cE9core0_0_05panicF6const00g.val, &ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0gG6vtable0g.val);	// _15 = MakeDst(&::"core-0_0_0"::panic::const#0, &<::"core-0_0_0"::panic::#0::NoPayload/*S*/ as ::"core-0_0_0"::any::Any>::vtable#)
	var11._0 = var15;
	var11._1 = var17;
	var11._2 = var16;	// _11 = Struct(::"core-0_0_0"::panic::PanicInfo<'#local2,>, {_15, _17, _16})
	var13 = & var11;	// _13 = Borrow(Shared, _11)
	ZRG3cE9core0_0_09panickingB_010panic_impl0g( var13 );
	// ^ Call( _14 = ::"core-0_0_0"::panicking::#0::panic_impl<'#local3,>( _13, ), bb4, bb4)
bb4: _Unwind_Resume(); // Diverge
bb5:
	/* ZST assign */
	rv.DATA.TAG = 0;	// retval = Variant(::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,> #0, {_6})
	// ^ drop(a0)
	return rv;
	// ^ Return
bb6:
	/* ZST assign */
	rv.DATA.TAG = 1;	// retval = Variant(::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,> #1, {_7})
	// ^ drop(a0)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::realloc<'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g7realloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g rv;
	struct s_ZRG1cM17alloc_system0_0_06System0g *var0;	// &'M0 ::"alloc_system-0_0_0"::System/*S*/
	uint8_t *var1;	// *mut u8
	struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa var2;	// ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_05alloc8AllocErr0g var3 = {0};	// ::"core-0_0_0"::alloc::AllocErr/*S*/
	uint8_t *var4;	// *mut u8
	var0 = arg0;	// _0 = Borrow(Shared, a0*)
	var4 = (uint8_t *)arg1._0._0;	// _4 = Cast(a1.0.0 as *mut u8)
	var1 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g7realloc0g( var0, var4, arg2, arg3 );
	// ^ Call( _1 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::realloc<'M0,>( _0, _4, a2, a3, ), bb1, bb4)
	var2 = ZRIG2cE9core0_0_03ptr7NonNull1gCa3new0g( var1 );
	// ^ Call( _2 = <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/ /*- <u8,>*/>::new( _1, ), bb2, bb4)
	/* ZST assign */
	{
		struct s_ZRG2cE9core0_0_05alloc8AllocErr0g zarg1 = {0};
		rv = ZRIG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa5ok_or1gG2c_A5alloc8AllocErr0g( var2, zarg1 );
	}
	// ^ Call( retval = <::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>*/>::ok_or<::"core-0_0_0"::alloc::AllocErr/*S*/,>( _2, _3, ), bb3, bb4)
	// ^ drop(a0)
	return rv;
	// ^ Return
bb4: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::realloc_excess<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g14realloc_excess0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g rv;
	TUP_2_ZRTCu_ZRTCu var0;	// (usize, usize, )
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g var1;	// ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
	TUP_2_ZRTCu_ZRTCu *var2;	// &'#ivar1 (usize, usize, )
	struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_00g var3;	// ::"core-0_0_0"::alloc::closure#realloc_excess_0<'#local2,>/*S*/
	;
	var0._0 = arg3;
	var0._1 = arg3;	// _0 = Tuple(a3, a3)
	var1 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g7realloc0g( arg0, arg1, arg2, arg3 );
	// ^ Call( _1 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::realloc<'#omitted,>( a0, a1, a2, a3, ), bb1, bb3)
	var2 = & var0;	// _2 = Borrow(Shared, _0)
	var3._0 = var2;	// _3 = Struct(::"core-0_0_0"::alloc::closure#realloc_excess_0<'#local2,>, {_2})
	rv = ZRIG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g3map2gG2c_A_F6Excess0gG2c_A_FH23closurereal$83ff099e8a2adbb( var1, var3 );
	// ^ Call( retval = <::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>*/>::map<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::closure#realloc_excess_0<'#local2,>/*S*/,>( _1, _3, ), bb2, bb3)
	return rv;
	// ^ Return
bb3: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::shrink_in_place<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g15shrink_in_place0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g rv;
	RUST_BOOL var0;	// bool
	t_ZRTfQBsCy2cE9core0_0_03fmt7Display0g_B0g var1 = {0};	// fn{<&'static str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>}
	t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g var2;	// for<'elided#0,'elided#1,> extern "Rust" fn(&'static &'static str, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g var3;	// ::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/
	t_ZRTA1G2cE9core0_0_03fmt10ArgumentV10g var4;	// [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/; 1]
	t_ZRTA1G2cE9core0_0_03fmt10ArgumentV10g *var5;	// &'#local1 [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/; 1]
	tUNIT var6 = {0};	// ()
	struct s_ZRG2cE9core0_0_05alloc20CannotReallocInPlace0g var7 = {0};	// ::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/
	struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g var8;	// ::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>/*E*/
	SLICE_PTR var9;	// &'static [&'static str]
	SLICE_PTR var10;	// &'#local1 [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/]
	struct s_ZRG2cE9core0_0_05panic9PanicInfo0g var11;	// ::"core-0_0_0"::panic::PanicInfo<'#local2,>/*S*/
	struct s_ZRG2cE9core0_0_03fmt9Arguments0g *var12;	// &'#local0 ::"core-0_0_0"::fmt::Arguments<'#local1,>/*S*/
	struct s_ZRG2cE9core0_0_05panic9PanicInfo0g *var13;	// &'#local1 ::"core-0_0_0"::panic::PanicInfo<'#local2,>/*S*/
	tBANG var14 = {0};	// !
	TRAITOBJ_PTR var15;	// &'#local2 dyn (::"core-0_0_0"::any::Any+::"core-0_0_0"::marker::Send)
	struct s_ZRG2cE9core0_0_05panic8Location0g var16;	// ::"core-0_0_0"::panic::Location<'static,>/*S*/
	struct e_ZRG2cE9core0_0_06option6Option1gBsG2c_A3fmt9Arguments0g var17;	// ::"core-0_0_0"::option::Option<&'#local0 ::"core-0_0_0"::fmt::Arguments<'#local1,>/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_03fmt9Arguments0g var18;	// ::"core-0_0_0"::fmt::Arguments<'#local1,>/*S*/
	var0 = arg3 <= arg2._0;	// _0 = BinOp(a3 LE a2.0)
	if(var0) goto bb1; else goto bb2;
	// ^ If( _0 : 1, 2)
bb1:
	var0 = arg2._0 <= arg3;	// _0 = BinOp(a2.0 LE a3)
	if(var0) goto bb5; else goto bb6;
	// ^ If( _0 : 5, 6)
bb2:
	var9 = make_sliceptr(&ZRG3cE9core0_0_05allocB_59FRAGMENTS0g.val, 0x2ull);	// _9 = MakeDst(&::"core-0_0_0"::alloc::#5::FRAGMENTS, 0x2 usize)
	/* ZST assign */
	var2 = ZRQBsCy2cE9core0_0_03fmt7Display0g_B0g;	// _2 = Cast(_1 as for<'elided#0,'elided#1,> extern "Rust" fn(&'static &'static str, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/)
	var3 = ZRIG2cE9core0_0_03fmt10ArgumentV10g3new1gBsCy( &ZRG2cE9core0_0_05allocF6const20g.val, var2 );
	// ^ Call( _3 = <::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/ /*- <'static,>*/>::new<'static,&'static str,>( &::"core-0_0_0"::alloc::const#2, _2, ), bb3, bb4)
	var4.DATA[0] = var3;	// _4 = Array(_3)
	var5 = & var4;	// _5 = Borrow(Shared, _4)
	var10 = make_sliceptr(var5, 0x1ull);	// _10 = MakeDst(_5, 0x1 usize)
	memset(&var8, 0, sizeof(struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g ));	// _8 = Variant(::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],> #0, {})
	var18._0 = var9;
	var18._1 = var8;
	var18._2 = var10;	// _18 = Struct(::"core-0_0_0"::fmt::Arguments<'#local1,>, {_9, _8, _10})
	var12 = & var18;	// _12 = Borrow(Shared, _18)
	var17.DATA.var_1._0 = var12;	// _17 = Variant(::"core-0_0_0"::option::Option<&'#local0 ::"core-0_0_0"::fmt::Arguments<'#local1,>/*S*/,> #1, {_12})
	var16._0 = ZRG2cE9core0_0_05allocF6const30g.val._0;
	var16._1 = ZRG2cE9core0_0_05allocF6const30g.val._1;
	var16._2 = ZRG2cE9core0_0_05allocF6const30g.val._2;	// _16 = Struct(::"core-0_0_0"::panic::Location<'static,>, {(::"core-0_0_0"::alloc::const#3).0, (::"core-0_0_0"::alloc::const#3).1, (::"core-0_0_0"::alloc::const#3).2})
	var15 = make_traitobjptr(&ZRG2cE9core0_0_05panicF6const00g.val, &ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0gG6vtable0g.val);	// _15 = MakeDst(&::"core-0_0_0"::panic::const#0, &<::"core-0_0_0"::panic::#0::NoPayload/*S*/ as ::"core-0_0_0"::any::Any>::vtable#)
	var11._0 = var15;
	var11._1 = var17;
	var11._2 = var16;	// _11 = Struct(::"core-0_0_0"::panic::PanicInfo<'#local2,>, {_15, _17, _16})
	var13 = & var11;	// _13 = Borrow(Shared, _11)
	ZRG3cE9core0_0_09panickingB_010panic_impl0g( var13 );
	// ^ Call( _14 = ::"core-0_0_0"::panicking::#0::panic_impl<'#local3,>( _13, ), bb4, bb4)
bb4: _Unwind_Resume(); // Diverge
bb5:
	/* ZST assign */
	rv.DATA.TAG = 0;	// retval = Variant(::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,> #0, {_6})
	// ^ drop(a0)
	return rv;
	// ^ Return
bb6:
	/* ZST assign */
	rv.DATA.TAG = 1;	// retval = Variant(::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,> #1, {_7})
	// ^ drop(a0)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::usable_size<'#omitted,'#omitted,>
static TUP_2_ZRTCu_ZRTCu  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g11usable_size0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g *arg1 // &'#omitted ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> (usize, usize, )

{
	TUP_2_ZRTCu_ZRTCu rv;
	struct s_ZRG2cE9core0_0_05alloc6Layout0g *var0;	// &'#omitted ::"core-0_0_0"::alloc::Layout/*S*/
	var0 = arg1;	// _0 = Use(a1)
	;
	rv._0 = var0->_0;
	rv._1 = arg1->_0;	// retval = Tuple(_0*.0, a1*.0)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc<'#omitted,>
uint8_t * ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g_D0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> *mut u8

{
	uint8_t *rv;
	RUST_BOOL var0;	// bool
	struct e_ZRG1cE12libc0_0_0_H46c_void0g *var1;	// *mut ::"libc-0_0_0_H4"::c_void/*E*/
	struct s_ZRG2cE9core0_0_05alloc6Layout0g *var2;	// &'#local0 ::"core-0_0_0"::alloc::Layout/*S*/
	uintptr_t var3;	// usize
	var0 = arg1._1._0._0 <= 0x10ull;	// _0 = BinOp(a1.1.0.0 LE 0x10 usize)
	if(var0) goto bb1; else goto bb2;
	// ^ If( _0 : 1, 2)
bb1:
	var0 = arg1._1._0._0 <= arg1._0;	// _0 = BinOp(a1.1.0.0 LE a1.0)
	if(var0) goto bb7; else goto bb2;
	// ^ If( _0 : 7, 2)
bb2:
	var0 = arg1._1._0._0 > 0x80000000ull;	// _0 = BinOp(a1.1.0.0 GT 0x80000000 usize)
	if(var0) goto bb3; else goto bb4;
	// ^ If( _0 : 3, 4)
bb3:
	var3 = 0x0ull;	// _3 = Constant(0x0 usize)
	rv = (uint8_t *)var3;	// retval = Cast(_3 as *mut u8)
	return rv;
	// ^ Return
bb4:
	var2 = & arg1;	// _2 = Borrow(Shared, a1)
	rv = ZRG2cM17alloc_system0_0_08platform14aligned_malloc0g( var2 );
	// ^ Call( retval = ::"alloc_system-0_0_0"::platform::aligned_malloc<'#local5,>( _2, ), bb5, bb6)
	return rv;
	// ^ Return
bb6: _Unwind_Resume(); // Diverge
bb7:
	var1 = ZRG1cE12libc0_0_0_H46malloc0g( arg1._0 );
	// ^ Call( _1 = ::"libc-0_0_0_H4"::malloc( a1.0, ), bb8, bb6)
	rv = (uint8_t *)var1;	// retval = Cast(_1 as *mut u8)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc_zeroed<'#omitted,>
uint8_t * ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g12alloc_zeroed0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> *mut u8

{
	uint8_t *rv;
	uint8_t *var0;	// *mut u8
	RUST_BOOL var1;	// bool
	struct e_ZRG1cE12libc0_0_0_H46c_void0g *var2;	// *mut ::"libc-0_0_0_H4"::c_void/*E*/
	struct s_ZRG2cE9core0_0_05alloc6Layout0g *var3;	// &'#local0 ::"core-0_0_0"::alloc::Layout/*S*/
	struct s_ZRG2cE9core0_0_05alloc6Layout0g var4;	// ::"core-0_0_0"::alloc::Layout/*S*/
	tUNIT var5 = {0};	// ()
	uint8_t *var6;	// *mut u8
	uintptr_t var7;	// usize
	var1 = arg1._1._0._0 <= 0x10ull;	// _1 = BinOp(a1.1.0.0 LE 0x10 usize)
	if(var1) goto bb1; else goto bb2;
	// ^ If( _1 : 1, 2)
bb1:
	var1 = arg1._1._0._0 <= arg1._0;	// _1 = BinOp(a1.1.0.0 LE a1.0)
	if(var1) goto bb8; else goto bb2;
	// ^ If( _1 : 8, 2)
bb2:
	var3 = & arg1;	// _3 = Borrow(Shared, a1)
	var4 = ZRQG2cE9core0_0_05alloc6Layout0g2c_A5clone5Clone0g_D0g( var3 );
	// ^ Call( _4 = <::"core-0_0_0"::alloc::Layout/*S*/ as ::"core-0_0_0"::clone::Clone>::clone<'#local4,>( _3, ), bb3, bb5)
	var0 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g_D0g( arg0, var4 );
	// ^ Call( _0 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc<'M0,>( a0, _4, ), bb4, bb5)
	var7 = 0x0ull;	// _7 = Constant(0x0 usize)
	var6 = (uint8_t *)var7;	// _6 = Cast(_7 as *mut u8)
	var1 = var0 == var6;	// _1 = BinOp(_0 EQ _6)
	if(var1) goto bb7; else goto bb6;
	// ^ If( _1 : 7, 6)
bb5: _Unwind_Resume(); // Diverge
bb6:
	if( arg1._0 > 0) memset( var0, 0x0, arg1._0 * sizeof(uint8_t ));
	// ^ Call( _5 = "write_bytes"::<u8,>( _0, 0x0 u8, a1.0, ), bb7, bb5)
bb7:
	rv = var0;	// retval = Use(_0)
	return rv;
	// ^ Return
bb8:
	var2 = ZRG1cE12libc0_0_0_H46calloc0g( arg1._0, 0x1ull );
	// ^ Call( _2 = ::"libc-0_0_0_H4"::calloc( a1.0, 0x1 usize, ), bb9, bb5)
	rv = (uint8_t *)var2;	// retval = Cast(_2 as *mut u8)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::dealloc<'#omitted,>
void  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g7dealloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		uint8_t *arg1, // *mut u8
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ()

{
	tUNIT rv;
	struct e_ZRG1cE12libc0_0_0_H46c_void0g *var0;	// *mut ::"libc-0_0_0_H4"::c_void/*E*/
	var0 = (struct e_ZRG1cE12libc0_0_0_H46c_void0g *)arg1;	// _0 = Cast(a1 as *mut ::"libc-0_0_0_H4"::c_void/*E*/)
	ZRG1cE12libc0_0_0_H44free0g( var0 );
	// ^ Call( retval = ::"libc-0_0_0_H4"::free( _0, ), bb1, bb2)
	return ;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::realloc<'#omitted,>
uint8_t * ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g7realloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		uint8_t *arg1, // *mut u8
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> *mut u8

{
	uint8_t *rv;
	RUST_BOOL var0;	// bool
	struct e_ZRG1cE12libc0_0_0_H46c_void0g *var1;	// *mut ::"libc-0_0_0_H4"::c_void/*E*/
	struct e_ZRG1cE12libc0_0_0_H46c_void0g *var2;	// *mut ::"libc-0_0_0_H4"::c_void/*E*/
	var0 = arg2._1._0._0 <= 0x10ull;	// _0 = BinOp(a2.1.0.0 LE 0x10 usize)
	if(var0) goto bb1; else goto bb2;
	// ^ If( _0 : 1, 2)
bb1:
	var0 = arg2._1._0._0 <= arg3;	// _0 = BinOp(a2.1.0.0 LE a3)
	if(var0) goto bb5; else goto bb2;
	// ^ If( _0 : 5, 2)
bb2:
	rv = ZRIG1cM17alloc_system0_0_06System0g16realloc_fallback0g( arg0, arg1, arg2, arg3 );
	// ^ Call( retval = <::"alloc_system-0_0_0"::System/*S*/ /*- */>::realloc_fallback<'M0,>( a0, a1, a2, a3, ), bb3, bb4)
	return rv;
	// ^ Return
bb4: _Unwind_Resume(); // Diverge
bb5:
	var1 = (struct e_ZRG1cE12libc0_0_0_H46c_void0g *)arg1;	// _1 = Cast(a1 as *mut ::"libc-0_0_0_H4"::c_void/*E*/)
	var2 = ZRG1cE12libc0_0_0_H47realloc0g( var1, arg3 );
	// ^ Call( _2 = ::"libc-0_0_0_H4"::realloc( _1, a3, ), bb6, bb4)
	rv = (uint8_t *)var2;	// retval = Cast(_2 as *mut u8)
	return rv;
	// ^ Return
}
// <::"core-0_0_0"::panic::#0::NoPayload/*S*/ as ::"core-0_0_0"::any::Any>::get_type_id<'#omitted,>
static struct s_ZRG2cE9core0_0_03any6TypeId0g  ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0g11get_type_id0g(
		struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g *arg0 // &'#omitted ::"core-0_0_0"::panic::#0::NoPayload/*S*/
		) // -> ::"core-0_0_0"::any::TypeId/*S*/

{
	struct s_ZRG2cE9core0_0_03any6TypeId0g rv;
	uint64_t var0;	// u64
	var0 = (uintptr_t)&__typeid_ZRTG3cE9core0_0_05panicB_09NoPayload0g;
	// ^ Call( _0 = "type_id"::<::"core-0_0_0"::panic::#0::NoPayload/*S*/,>( ), bb1, bb2)
	rv._0 = var0;	// retval = Struct(::"core-0_0_0"::any::TypeId, {_0})
	return rv;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
// <&'static str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  ZRQBsCy2cE9core0_0_03fmt7Display0g_B0g(
		SLICE_PTR *arg0, // &'static &'static str
		struct s_ZRG2cE9core0_0_03fmt9Formatter0g *arg1 // &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g rv;
	SLICE_PTR var0;	// &'static str
	var0 = (*arg0);	// _0 = Borrow(Shared, a0**)
	rv = ZRQCy2cE9core0_0_03fmt7Display0g_B0g( var0, arg1 );
	// ^ Call( retval = <str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>( _0, a1, ), bb1, bb2)
	return rv;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
