/*
 * AUTOGENERATED by mrustc
 */
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>
#include <assert.h>
#include <stdatomic.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <setjmp.h>
typedef uint32_t RUST_CHAR;
typedef uint8_t RUST_BOOL;
typedef struct { void* PTR; size_t META; } SLICE_PTR;
typedef struct { void* PTR; void* META; } TRAITOBJ_PTR;
typedef struct { void (*drop)(void*); size_t size; size_t align; } VTABLE_HDR;
typedef struct { char _d; } tUNIT;
typedef char tBANG;
typedef struct { char _d; } tTYPEID;
static inline size_t ALIGN_TO(size_t s, size_t a) { return (s + a-1) / a * a; }

extern void _Unwind_Resume(void) __attribute__((noreturn));
#define ALIGNOF(t) __alignof__(t)
extern __thread jmp_buf*    mrustc_panic_target;
extern __thread void* mrustc_panic_value;
static inline uint64_t __builtin_clz64(uint64_t v) {
	return ( (v >> 32) != 0 ? __builtin_clz(v>>32) : 32 + __builtin_clz(v));
}
static inline uint64_t __builtin_ctz64(uint64_t v) {
	return ((v&0xFFFFFFFF) == 0 ? __builtin_ctz(v>>32) + 32 : __builtin_ctz(v));
}
static inline uint8_t __mrustc_atomicloop8(volatile uint8_t* slot, uint8_t param, int ordering, uint8_t (*cb)(uint8_t, uint8_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint8_t v = atomic_load_explicit((_Atomic uint8_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint8_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint16_t __mrustc_atomicloop16(volatile uint16_t* slot, uint16_t param, int ordering, uint16_t (*cb)(uint16_t, uint16_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint16_t v = atomic_load_explicit((_Atomic uint16_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint16_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint32_t __mrustc_atomicloop32(volatile uint32_t* slot, uint32_t param, int ordering, uint32_t (*cb)(uint32_t, uint32_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint32_t v = atomic_load_explicit((_Atomic uint32_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint32_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint64_t __mrustc_atomicloop64(volatile uint64_t* slot, uint64_t param, int ordering, uint64_t (*cb)(uint64_t, uint64_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint64_t v = atomic_load_explicit((_Atomic uint64_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint64_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
typedef unsigned __int128 uint128_t;
typedef signed __int128 int128_t;
static inline uint128_t __builtin_bswap128(uint128_t v) {
	uint64_t lo = __builtin_bswap64((uint64_t)v);
	uint64_t hi = __builtin_bswap64((uint64_t)(v>>64));
	return ((uint128_t)lo << 64) | (uint128_t)hi;
}
static inline uint128_t intrinsic_ctlz_u128(uint128_t v) {
	return (v == 0 ? 128 : (v >> 64 != 0 ? __builtin_clz64(v>>64) : 64 + __builtin_clz64(v)));
}
static inline uint128_t intrinsic_cttz_u128(uint128_t v) {
	return (v == 0 ? 128 : ((v&0xFFFFFFFFFFFFFFFF) == 0 ? __builtin_ctz64(v>>64) + 64 : __builtin_ctz64(v)));
}

static inline int slice_cmp(SLICE_PTR l, SLICE_PTR r) {
	int rv = memcmp(l.PTR, r.PTR, l.META < r.META ? l.META : r.META);
	if(rv != 0) return rv;
	if(l.META < r.META) return -1;
	if(l.META > r.META) return 1;
	return 0;
}
static inline SLICE_PTR make_sliceptr(void* ptr, size_t s) { SLICE_PTR rv = { ptr, s }; return rv; }
static inline TRAITOBJ_PTR make_traitobjptr(void* ptr, void* vt) { TRAITOBJ_PTR rv = { ptr, vt }; return rv; }

static inline size_t mrustc_max(size_t a, size_t b) { return a < b ? b : a; }
static inline void noop_drop(tUNIT *p) { }

static inline size_t mrustc_string_search_linear(SLICE_PTR val, size_t count, SLICE_PTR* options) {
	for(size_t i = 0; i < count; i ++) {
		int cmp = slice_cmp(val, options[i]);
		if(cmp < 0) break;
		if(cmp == 0) return i;
	}
	return SIZE_MAX;
}
static const uint8_t __mrustc_revmap[16] = { 0, 8, 4,12, 2,10, 6,14,  1, 9, 5,13, 3, 7,15};
static inline uint8_t __mrustc_bitrev8(uint8_t v) { if(v==0||v==0xFF) return v; return __mrustc_revmap[v>>4]|(__mrustc_revmap[v&15]<<4); }
static inline uint16_t __mrustc_bitrev16(uint16_t v) { if(v==0) return 0; return ((uint16_t)__mrustc_bitrev8(v>>8))|((uint16_t)__mrustc_bitrev8(v)<<8); }
static inline uint32_t __mrustc_bitrev32(uint32_t v) { if(v==0) return 0; return ((uint32_t)__mrustc_bitrev16(v>>16))|((uint32_t)__mrustc_bitrev16(v)<<16); }
static inline uint64_t __mrustc_bitrev64(uint64_t v) { if(v==0) return 0; return ((uint64_t)__mrustc_bitrev32(v>>32))|((uint64_t)__mrustc_bitrev32(v)<<32); }
static inline uint128_t __mrustc_bitrev128(uint128_t v) { if(v==0) return 0; uint128_t rv = ((uint128_t)__mrustc_bitrev64(v>>64))|((uint128_t)__mrustc_bitrev64(v)<<64); return rv; }
static inline uint8_t __mrustc_op_umax8(uint8_t a, uint8_t b) { return (a > b ? a : b); }
static inline uint8_t __mrustc_op_umin8(uint8_t a, uint8_t b) { return (a < b ? a : b); }
static inline uint8_t __mrustc_op_imax8(uint8_t a, uint8_t b) { return ((int8_t)a > (int8_t)b ? a : b); }
static inline uint8_t __mrustc_op_imin8(uint8_t a, uint8_t b) { return ((int8_t)a < (int8_t)b ? a : b); }
static inline uint8_t __mrustc_op_and_not8(uint8_t a, uint8_t b) { return ~(a & b); }
static inline uint16_t __mrustc_op_umax16(uint16_t a, uint16_t b) { return (a > b ? a : b); }
static inline uint16_t __mrustc_op_umin16(uint16_t a, uint16_t b) { return (a < b ? a : b); }
static inline uint16_t __mrustc_op_imax16(uint16_t a, uint16_t b) { return ((int16_t)a > (int16_t)b ? a : b); }
static inline uint16_t __mrustc_op_imin16(uint16_t a, uint16_t b) { return ((int16_t)a < (int16_t)b ? a : b); }
static inline uint16_t __mrustc_op_and_not16(uint16_t a, uint16_t b) { return ~(a & b); }
static inline uint32_t __mrustc_op_umax32(uint32_t a, uint32_t b) { return (a > b ? a : b); }
static inline uint32_t __mrustc_op_umin32(uint32_t a, uint32_t b) { return (a < b ? a : b); }
static inline uint32_t __mrustc_op_imax32(uint32_t a, uint32_t b) { return ((int32_t)a > (int32_t)b ? a : b); }
static inline uint32_t __mrustc_op_imin32(uint32_t a, uint32_t b) { return ((int32_t)a < (int32_t)b ? a : b); }
static inline uint32_t __mrustc_op_and_not32(uint32_t a, uint32_t b) { return ~(a & b); }
static inline uint64_t __mrustc_op_umax64(uint64_t a, uint64_t b) { return (a > b ? a : b); }
static inline uint64_t __mrustc_op_umin64(uint64_t a, uint64_t b) { return (a < b ? a : b); }
static inline uint64_t __mrustc_op_imax64(uint64_t a, uint64_t b) { return ((int64_t)a > (int64_t)b ? a : b); }
static inline uint64_t __mrustc_op_imin64(uint64_t a, uint64_t b) { return ((int64_t)a < (int64_t)b ? a : b); }
static inline uint64_t __mrustc_op_and_not64(uint64_t a, uint64_t b) { return ~(a & b); }
// enum ::"atty-0_2_11"::Stream
struct e_ZRG1cE10atty0_2_116Stream0g {
	int8_t TAG;
};
typedef char sizeof_assert_ZRG1cE10atty0_2_116Stream0g[ (sizeof(struct e_ZRG1cE10atty0_2_116Stream0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Ok<(),::"core-0_0_0"::fmt::Error/*S*/,>
struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ()
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::fmt::Error
struct s_ZRG2cE9core0_0_03fmt5Error0g  {
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG2cE9core0_0_03fmt5Error0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03fmt5Error0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Err<(),::"core-0_0_0"::fmt::Error/*S*/,>
struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ::"core-0_0_0"::fmt::Error/*S*/
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
// enum ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>
struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g {
	union {
		struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g var_0;
		struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g var_1;
		uint8_t TAG;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g[ (sizeof(struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
struct s_ZRG2cE9core0_0_03fmt9Formatter0g;
// enum ::"core-0_0_0"::fmt::rt::v1::Alignment
struct e_ZRG4cE9core0_0_03fmt2rt2v19Alignment0g {
	int8_t TAG;
};
typedef char sizeof_assert_ZRG4cE9core0_0_03fmt2rt2v19Alignment0g[ (sizeof(struct e_ZRG4cE9core0_0_03fmt2rt2v19Alignment0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::option::Option#Some<usize,>
struct s_ZRG2cE9core0_0_06optionG10OptionSome1gCu  {
	/*@0*/uint8_t _1; // u8
	/*@8*/uintptr_t _0; // usize
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gCu[ (sizeof(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gCu) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gCu[ (ALIGNOF(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gCu) == 8) ? 1 : -1 ];
// enum ::"core-0_0_0"::option::Option<usize,>
struct e_ZRG2cE9core0_0_06option6Option1gCu {
	union {
		// ZST: ()
		struct s_ZRG2cE9core0_0_06optionG10OptionSome1gCu var_1;
		uint8_t TAG;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06option6Option1gCu[ (sizeof(struct e_ZRG2cE9core0_0_06option6Option1gCu) == 16) ? 1 : -1 ];
struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g;
// struct ::"core-0_0_0"::marker::PhantomData<&'#omitted ::"core-0_0_0"::fmt::ArgumentV1<'#omitted,>/*S*/,>
struct s_ZRG2cE9core0_0_06marker11PhantomData1gBsG2c_A3fmt10ArgumentV10g  {
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG2cE9core0_0_06marker11PhantomData1gBsG2c_A3fmt10ArgumentV10g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06marker11PhantomData1gBsG2c_A3fmt10ArgumentV10g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::slice::Iter<'#omitted,::"core-0_0_0"::fmt::ArgumentV1<'#omitted,>/*S*/,>
struct s_ZRG2cE9core0_0_05slice4Iter1gG2c_A3fmt10ArgumentV10g  {
	/*@0*/// ZST; // ::"core-0_0_0"::marker::PhantomData<&'#omitted ::"core-0_0_0"::fmt::ArgumentV1<'#omitted,>/*S*/,>/*S*/
	/*@0*/struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g *_0; // *const ::"core-0_0_0"::fmt::ArgumentV1<'#omitted,>/*S*/
	/*@8*/struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g *_1; // *const ::"core-0_0_0"::fmt::ArgumentV1<'#omitted,>/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_05slice4Iter1gG2c_A3fmt10ArgumentV10g[ (sizeof(struct s_ZRG2cE9core0_0_05slice4Iter1gG2c_A3fmt10ArgumentV10g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_05slice4Iter1gG2c_A3fmt10ArgumentV10g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05slice4Iter1gG2c_A3fmt10ArgumentV10g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::fmt::Formatter<'#omitted,>
struct s_ZRG2cE9core0_0_03fmt9Formatter0g  {
	/*@0*/struct e_ZRG4cE9core0_0_03fmt2rt2v19Alignment0g _2; // ::"core-0_0_0"::fmt::rt::v1::Alignment/*E*/
	/*@4*/uint32_t _0; // u32
	/*@8*/RUST_CHAR _1; // char
	/*@16*/struct e_ZRG2cE9core0_0_06option6Option1gCu _3; // ::"core-0_0_0"::option::Option<usize,>/*E*/
	/*@32*/struct e_ZRG2cE9core0_0_06option6Option1gCu _4; // ::"core-0_0_0"::option::Option<usize,>/*E*/
	/*@48*/TRAITOBJ_PTR _5; // &'#omitted mut dyn (::"core-0_0_0"::fmt::Write+'#omitted)
	/*@64*/struct s_ZRG2cE9core0_0_05slice4Iter1gG2c_A3fmt10ArgumentV10g _6; // ::"core-0_0_0"::slice::Iter<'#omitted,::"core-0_0_0"::fmt::ArgumentV1<'#omitted,>/*S*/,>/*S*/
	/*@80*/SLICE_PTR _7; // &'#omitted [::"core-0_0_0"::fmt::ArgumentV1<'#omitted,>/*S*/]
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03fmt9Formatter0g[ (sizeof(struct s_ZRG2cE9core0_0_03fmt9Formatter0g) == 96) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03fmt9Formatter0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03fmt9Formatter0g) == 8) ? 1 : -1 ];
struct s_ZRG2cE9core0_0_05panic9PanicInfo0g;
// PROTO extern "Rust" ::"atty-0_2_11"::is
RUST_BOOL  ZRG1cE10atty0_2_112is0g(
		struct e_ZRG1cE10atty0_2_116Stream0g arg0 // ::"atty-0_2_11"::Stream/*E*/
		) // -> bool
;
// PROTO extern "Rust" ::"atty-0_2_11"::isnt
RUST_BOOL  ZRG1cE10atty0_2_114isnt0g(
		struct e_ZRG1cE10atty0_2_116Stream0g arg0 // ::"atty-0_2_11"::Stream/*E*/
		) // -> bool
;
// PROTO extern "Rust" <::"atty-0_2_11"::Stream/*E*/ as ::"core-0_0_0"::clone::Clone>::clone<'#omitted,>
struct e_ZRG1cE10atty0_2_116Stream0g  ZRQG1cE10atty0_2_116Stream0g2cE9core0_0_05clone5Clone0g_D0g(
		struct e_ZRG1cE10atty0_2_116Stream0g *arg0 // &'#omitted ::"atty-0_2_11"::Stream/*E*/
		) // -> ::"atty-0_2_11"::Stream/*E*/
;
// PROTO extern "Rust" <::"atty-0_2_11"::Stream/*E*/ as ::"core-0_0_0"::clone::Clone>::clone_from<'#omitted,'#omitted,>
static void  ZRQG1cE10atty0_2_116Stream0g2cE9core0_0_05clone5Clone0g10clone_from0g(
		struct e_ZRG1cE10atty0_2_116Stream0g *arg0, // &'#omitted mut ::"atty-0_2_11"::Stream/*E*/
		struct e_ZRG1cE10atty0_2_116Stream0g *arg1 // &'#omitted ::"atty-0_2_11"::Stream/*E*/
		) // -> ()
;
// PROTO extern "Rust" <::"atty-0_2_11"::Stream/*E*/ as ::"core-0_0_0"::fmt::Debug>::fmt<'#omitted,'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  ZRQG1cE10atty0_2_116Stream0g2cE9core0_0_03fmt5Debug0g_D0g(
		struct e_ZRG1cE10atty0_2_116Stream0g *arg0, // &'#omitted ::"atty-0_2_11"::Stream/*E*/
		struct s_ZRG2cE9core0_0_03fmt9Formatter0g *arg1 // &'#omitted mut ::"core-0_0_0"::fmt::Formatter<'#omitted,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
;
// EXTERN extern "C" ::"libc-0_2_42_H1"::unix::isatty
extern int32_t  ZRG2cE13libc0_2_42_H14unix6isatty0g(
		int32_t arg0 // i32
		) // -> i32
 asm("_isatty");
// EXTERN extern "Rust" <::"core-0_0_0"::fmt::Formatter<'static,>/*S*/ /*- <'#omitted,>*/>::write_str<'#omitted,'static,>
extern struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  ZRIG2cE9core0_0_03fmt9Formatter0g9write_str0g(
		struct s_ZRG2cE9core0_0_03fmt9Formatter0g *arg0, // &'#omitted mut ::"core-0_0_0"::fmt::Formatter<'#omitted,>/*S*/
		SLICE_PTR arg1 // &'static str
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
;
// ::"atty-0_2_11"::is
RUST_BOOL  ZRG1cE10atty0_2_112is0g(
		struct e_ZRG1cE10atty0_2_116Stream0g arg0 // ::"atty-0_2_11"::Stream/*E*/
		) // -> bool

{
	RUST_BOOL rv;
	int32_t var0;	// i32
	int32_t var1;	// i32
	switch(arg0.TAG) {
	case 0ll: goto bb1;break;
	case 1ll: goto bb2;break;
	case 2ll: goto bb3;break;
	default: abort();
	}
	// ^ Switch( a0 : 0 => bb1, 1 => bb2, 2 => bb3, )
bb1:
	var0 = 1;	// _0 = Constant(+1 i32)
	goto bb4;
	// ^ Goto(4)
bb2:
	var0 = 2;	// _0 = Constant(+2 i32)
	goto bb4;
	// ^ Goto(4)
bb3:
	var0 = 0;	// _0 = Constant(+0 i32)
	// ^ Goto(4)
bb4:
	var1 = ZRG2cE13libc0_2_42_H14unix6isatty0g( var0 );
	// ^ Call( _1 = ::"libc-0_2_42_H1"::unix::isatty( _0, ), bb5, bb6)
	rv = var1 != 0;	// retval = BinOp(_1 NE +0 i32)
	return rv;
	// ^ Return
bb6: _Unwind_Resume(); // Diverge
}
// ::"atty-0_2_11"::isnt
RUST_BOOL  ZRG1cE10atty0_2_114isnt0g(
		struct e_ZRG1cE10atty0_2_116Stream0g arg0 // ::"atty-0_2_11"::Stream/*E*/
		) // -> bool

{
	RUST_BOOL rv;
	RUST_BOOL var0;	// bool
	var0 = ZRG1cE10atty0_2_112is0g( arg0 );
	// ^ Call( _0 = ::"atty-0_2_11"::is( a0, ), bb1, bb2)
	rv = !var0;	// retval = UniOp(_0 INV)
	return rv;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
// <::"atty-0_2_11"::Stream/*E*/ as ::"core-0_0_0"::clone::Clone>::clone<'#omitted,>
struct e_ZRG1cE10atty0_2_116Stream0g  ZRQG1cE10atty0_2_116Stream0g2cE9core0_0_05clone5Clone0g_D0g(
		struct e_ZRG1cE10atty0_2_116Stream0g *arg0 // &'#omitted ::"atty-0_2_11"::Stream/*E*/
		) // -> ::"atty-0_2_11"::Stream/*E*/

{
	struct e_ZRG1cE10atty0_2_116Stream0g rv;
	switch((*arg0).TAG) {
	case 0ll: goto bb1;break;
	case 1ll: goto bb2;break;
	case 2ll: goto bb3;break;
	default: abort();
	}
	// ^ Switch( a0* : 0 => bb1, 1 => bb2, 2 => bb3, )
bb1:
	rv.TAG = 0ll;	// retval = Variant(::"atty-0_2_11"::Stream #0, {})
	return rv;
	// ^ Return
bb2:
	rv.TAG = 1ll;	// retval = Variant(::"atty-0_2_11"::Stream #1, {})
	return rv;
	// ^ Return
bb3:
	rv.TAG = 2ll;	// retval = Variant(::"atty-0_2_11"::Stream #2, {})
	return rv;
	// ^ Return
}
// <::"atty-0_2_11"::Stream/*E*/ as ::"core-0_0_0"::clone::Clone>::clone_from<'#omitted,'#omitted,>
static void  ZRQG1cE10atty0_2_116Stream0g2cE9core0_0_05clone5Clone0g10clone_from0g(
		struct e_ZRG1cE10atty0_2_116Stream0g *arg0, // &'#omitted mut ::"atty-0_2_11"::Stream/*E*/
		struct e_ZRG1cE10atty0_2_116Stream0g *arg1 // &'#omitted ::"atty-0_2_11"::Stream/*E*/
		) // -> ()

{
	tUNIT rv;
	(*arg0) = ZRQG1cE10atty0_2_116Stream0g2cE9core0_0_05clone5Clone0g_D0g( arg1 );
	// ^ Call( a0* = <::"atty-0_2_11"::Stream/*E*/ as ::"core-0_0_0"::clone::Clone>::clone<'#omitted,>( a1, ), bb1, bb2)
	/* ZST assign */
	// ^ drop(a0)
	return ;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
// <::"atty-0_2_11"::Stream/*E*/ as ::"core-0_0_0"::fmt::Debug>::fmt<'#omitted,'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  ZRQG1cE10atty0_2_116Stream0g2cE9core0_0_03fmt5Debug0g_D0g(
		struct e_ZRG1cE10atty0_2_116Stream0g *arg0, // &'#omitted ::"atty-0_2_11"::Stream/*E*/
		struct s_ZRG2cE9core0_0_03fmt9Formatter0g *arg1 // &'#omitted mut ::"core-0_0_0"::fmt::Formatter<'#omitted,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g rv;
	struct s_ZRG2cE9core0_0_03fmt9Formatter0g *var0;	// &'M1 mut ::"core-0_0_0"::fmt::Formatter<'M1,>/*S*/
	struct s_ZRG2cE9core0_0_03fmt9Formatter0g *var1;	// &'M1 mut ::"core-0_0_0"::fmt::Formatter<'M1,>/*S*/
	struct s_ZRG2cE9core0_0_03fmt9Formatter0g *var2;	// &'M1 mut ::"core-0_0_0"::fmt::Formatter<'M1,>/*S*/
	switch((*arg0).TAG) {
	case 0ll: goto bb1;break;
	case 1ll: goto bb2;break;
	case 2ll: goto bb3;break;
	default: abort();
	}
	// ^ Switch( a0* : 0 => bb1, 1 => bb2, 2 => bb3, )
bb1:
	var0 = arg1;	// _0 = Borrow(Unique, a1*)
	rv = ZRIG2cE9core0_0_03fmt9Formatter0g9write_str0g( var0, make_sliceptr("Stdout", 6) );
	goto bb4;
	// ^ Call( retval = <::"core-0_0_0"::fmt::Formatter<'static,>/*S*/ /*- <'M1,>*/>::write_str<'M1,'static,>( _0, "Stdout", ), bb4, bb5)
bb2:
	var1 = arg1;	// _1 = Borrow(Unique, a1*)
	rv = ZRIG2cE9core0_0_03fmt9Formatter0g9write_str0g( var1, make_sliceptr("Stderr", 6) );
	goto bb4;
	// ^ Call( retval = <::"core-0_0_0"::fmt::Formatter<'static,>/*S*/ /*- <'M1,>*/>::write_str<'M1,'static,>( _1, "Stderr", ), bb4, bb5)
bb3:
	var2 = arg1;	// _2 = Borrow(Unique, a1*)
	rv = ZRIG2cE9core0_0_03fmt9Formatter0g9write_str0g( var2, make_sliceptr("Stdin", 5) );
	// ^ Call( retval = <::"core-0_0_0"::fmt::Formatter<'static,>/*S*/ /*- <'M1,>*/>::write_str<'M1,'static,>( _2, "Stdin", ), bb4, bb5)
bb4:
	// ^ drop(a1)
	return rv;
	// ^ Return
bb5: _Unwind_Resume(); // Diverge
}
