/*
 * AUTOGENERATED by mrustc
 */
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>
#include <assert.h>
#include <stdatomic.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <setjmp.h>
typedef uint32_t RUST_CHAR;
typedef uint8_t RUST_BOOL;
typedef struct { void* PTR; size_t META; } SLICE_PTR;
typedef struct { void* PTR; void* META; } TRAITOBJ_PTR;
typedef struct { void (*drop)(void*); size_t size; size_t align; } VTABLE_HDR;
typedef struct { char _d; } tUNIT;
typedef char tBANG;
typedef struct { char _d; } tTYPEID;
static inline size_t ALIGN_TO(size_t s, size_t a) { return (s + a-1) / a * a; }

extern void _Unwind_Resume(void) __attribute__((noreturn));
#define ALIGNOF(t) __alignof__(t)
extern __thread jmp_buf*    mrustc_panic_target;
extern __thread void* mrustc_panic_value;
static inline uint64_t __builtin_clz64(uint64_t v) {
	return ( (v >> 32) != 0 ? __builtin_clz(v>>32) : 32 + __builtin_clz(v));
}
static inline uint64_t __builtin_ctz64(uint64_t v) {
	return ((v&0xFFFFFFFF) == 0 ? __builtin_ctz(v>>32) + 32 : __builtin_ctz(v));
}
static inline uint8_t __mrustc_atomicloop8(volatile uint8_t* slot, uint8_t param, int ordering, uint8_t (*cb)(uint8_t, uint8_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint8_t v = atomic_load_explicit((_Atomic uint8_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint8_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint16_t __mrustc_atomicloop16(volatile uint16_t* slot, uint16_t param, int ordering, uint16_t (*cb)(uint16_t, uint16_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint16_t v = atomic_load_explicit((_Atomic uint16_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint16_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint32_t __mrustc_atomicloop32(volatile uint32_t* slot, uint32_t param, int ordering, uint32_t (*cb)(uint32_t, uint32_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint32_t v = atomic_load_explicit((_Atomic uint32_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint32_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint64_t __mrustc_atomicloop64(volatile uint64_t* slot, uint64_t param, int ordering, uint64_t (*cb)(uint64_t, uint64_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint64_t v = atomic_load_explicit((_Atomic uint64_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint64_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
typedef unsigned __int128 uint128_t;
typedef signed __int128 int128_t;
static inline uint128_t __builtin_bswap128(uint128_t v) {
	uint64_t lo = __builtin_bswap64((uint64_t)v);
	uint64_t hi = __builtin_bswap64((uint64_t)(v>>64));
	return ((uint128_t)lo << 64) | (uint128_t)hi;
}
static inline uint128_t intrinsic_ctlz_u128(uint128_t v) {
	return (v == 0 ? 128 : (v >> 64 != 0 ? __builtin_clz64(v>>64) : 64 + __builtin_clz64(v)));
}
static inline uint128_t intrinsic_cttz_u128(uint128_t v) {
	return (v == 0 ? 128 : ((v&0xFFFFFFFFFFFFFFFF) == 0 ? __builtin_ctz64(v>>64) + 64 : __builtin_ctz64(v)));
}

static inline int slice_cmp(SLICE_PTR l, SLICE_PTR r) {
	int rv = memcmp(l.PTR, r.PTR, l.META < r.META ? l.META : r.META);
	if(rv != 0) return rv;
	if(l.META < r.META) return -1;
	if(l.META > r.META) return 1;
	return 0;
}
static inline SLICE_PTR make_sliceptr(void* ptr, size_t s) { SLICE_PTR rv = { ptr, s }; return rv; }
static inline TRAITOBJ_PTR make_traitobjptr(void* ptr, void* vt) { TRAITOBJ_PTR rv = { ptr, vt }; return rv; }

static inline size_t mrustc_max(size_t a, size_t b) { return a < b ? b : a; }
static inline void noop_drop(tUNIT *p) { }

static inline size_t mrustc_string_search_linear(SLICE_PTR val, size_t count, SLICE_PTR* options) {
	for(size_t i = 0; i < count; i ++) {
		int cmp = slice_cmp(val, options[i]);
		if(cmp < 0) break;
		if(cmp == 0) return i;
	}
	return SIZE_MAX;
}
static const uint8_t __mrustc_revmap[16] = { 0, 8, 4,12, 2,10, 6,14,  1, 9, 5,13, 3, 7,15};
static inline uint8_t __mrustc_bitrev8(uint8_t v) { if(v==0||v==0xFF) return v; return __mrustc_revmap[v>>4]|(__mrustc_revmap[v&15]<<4); }
static inline uint16_t __mrustc_bitrev16(uint16_t v) { if(v==0) return 0; return ((uint16_t)__mrustc_bitrev8(v>>8))|((uint16_t)__mrustc_bitrev8(v)<<8); }
static inline uint32_t __mrustc_bitrev32(uint32_t v) { if(v==0) return 0; return ((uint32_t)__mrustc_bitrev16(v>>16))|((uint32_t)__mrustc_bitrev16(v)<<16); }
static inline uint64_t __mrustc_bitrev64(uint64_t v) { if(v==0) return 0; return ((uint64_t)__mrustc_bitrev32(v>>32))|((uint64_t)__mrustc_bitrev32(v)<<32); }
static inline uint128_t __mrustc_bitrev128(uint128_t v) { if(v==0) return 0; uint128_t rv = ((uint128_t)__mrustc_bitrev64(v>>64))|((uint128_t)__mrustc_bitrev64(v)<<64); return rv; }
static inline uint8_t __mrustc_op_umax8(uint8_t a, uint8_t b) { return (a > b ? a : b); }
static inline uint8_t __mrustc_op_umin8(uint8_t a, uint8_t b) { return (a < b ? a : b); }
static inline uint8_t __mrustc_op_imax8(uint8_t a, uint8_t b) { return ((int8_t)a > (int8_t)b ? a : b); }
static inline uint8_t __mrustc_op_imin8(uint8_t a, uint8_t b) { return ((int8_t)a < (int8_t)b ? a : b); }
static inline uint8_t __mrustc_op_and_not8(uint8_t a, uint8_t b) { return ~(a & b); }
static inline uint16_t __mrustc_op_umax16(uint16_t a, uint16_t b) { return (a > b ? a : b); }
static inline uint16_t __mrustc_op_umin16(uint16_t a, uint16_t b) { return (a < b ? a : b); }
static inline uint16_t __mrustc_op_imax16(uint16_t a, uint16_t b) { return ((int16_t)a > (int16_t)b ? a : b); }
static inline uint16_t __mrustc_op_imin16(uint16_t a, uint16_t b) { return ((int16_t)a < (int16_t)b ? a : b); }
static inline uint16_t __mrustc_op_and_not16(uint16_t a, uint16_t b) { return ~(a & b); }
static inline uint32_t __mrustc_op_umax32(uint32_t a, uint32_t b) { return (a > b ? a : b); }
static inline uint32_t __mrustc_op_umin32(uint32_t a, uint32_t b) { return (a < b ? a : b); }
static inline uint32_t __mrustc_op_imax32(uint32_t a, uint32_t b) { return ((int32_t)a > (int32_t)b ? a : b); }
static inline uint32_t __mrustc_op_imin32(uint32_t a, uint32_t b) { return ((int32_t)a < (int32_t)b ? a : b); }
static inline uint32_t __mrustc_op_and_not32(uint32_t a, uint32_t b) { return ~(a & b); }
static inline uint64_t __mrustc_op_umax64(uint64_t a, uint64_t b) { return (a > b ? a : b); }
static inline uint64_t __mrustc_op_umin64(uint64_t a, uint64_t b) { return (a < b ? a : b); }
static inline uint64_t __mrustc_op_imax64(uint64_t a, uint64_t b) { return ((int64_t)a > (int64_t)b ? a : b); }
static inline uint64_t __mrustc_op_imin64(uint64_t a, uint64_t b) { return ((int64_t)a < (int64_t)b ? a : b); }
static inline uint64_t __mrustc_op_and_not64(uint64_t a, uint64_t b) { return ~(a & b); }
// struct ::"core-0_0_0"::result::Result#Ok<(),::"core-0_0_0"::fmt::Error/*S*/,>
struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ()
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::fmt::Error
struct s_ZRG2cE9core0_0_03fmt5Error0g  {
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG2cE9core0_0_03fmt5Error0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03fmt5Error0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Err<(),::"core-0_0_0"::fmt::Error/*S*/,>
struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ::"core-0_0_0"::fmt::Error/*S*/
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
// enum ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>
struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g {
	union {
		struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g var_0;
		struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g var_1;
		uint8_t TAG;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g[ (sizeof(struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
struct s_ZRG2cE9core0_0_03fmt9Formatter0g;
struct s_ZRG2cE9core0_0_03fmt4Void0g;
typedef struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  (*t_ZRTF2BsG2cE9core0_0_03fmt4Void0gBuG2c_A_B9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g )( struct s_ZRG2cE9core0_0_03fmt4Void0g *, struct s_ZRG2cE9core0_0_03fmt9Formatter0g * ); // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 ::"core-0_0_0"::fmt::Void/*S*/, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
// struct ::"core-0_0_0"::fmt::ArgumentV1<'static,>
struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  {
	/*@0*/struct s_ZRG2cE9core0_0_03fmt4Void0g *_0; // &'static ::"core-0_0_0"::fmt::Void/*S*/
	/*@8*/t_ZRTF2BsG2cE9core0_0_03fmt4Void0gBuG2c_A_B9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g _1; // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 ::"core-0_0_0"::fmt::Void/*S*/, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03fmt10ArgumentV10g[ (sizeof(struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03fmt10ArgumentV10g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g) == 8) ? 1 : -1 ];
typedef struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  (*t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g )( SLICE_PTR *, struct s_ZRG2cE9core0_0_03fmt9Formatter0g * ); // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 &'static str, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
// struct ::"core-0_0_0"::option::Option#Some<&'#local0 [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>
struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g  {
	/*@0*/SLICE_PTR _0; // &'#local0 [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/]
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g[ (sizeof(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g) == 8) ? 1 : -1 ];
// enum ::"core-0_0_0"::option::Option<&'#local0 [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>
struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g {
	struct {
		struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g var_1;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g[ (sizeof(struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g) == 16) ? 1 : -1 ];
// struct ::"core-0_0_0"::fmt::Arguments<'#local0,>
struct s_ZRG2cE9core0_0_03fmt9Arguments0g  {
	/*@0*/SLICE_PTR _0; // &'#local0 [&'#local0 str]
	/*@16*/struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g _1; // ::"core-0_0_0"::option::Option<&'#local0 [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>/*E*/
	/*@32*/SLICE_PTR _2; // &'#local0 [::"core-0_0_0"::fmt::ArgumentV1<'#local0,>/*S*/]
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03fmt9Arguments0g[ (sizeof(struct s_ZRG2cE9core0_0_03fmt9Arguments0g) == 48) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03fmt9Arguments0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03fmt9Arguments0g) == 8) ? 1 : -1 ];
typedef struct TUP_3_ZRTBsCy_ZRTCe_ZRTCe  TUP_3_ZRTBsCy_ZRTCe_ZRTCe ;
typedef struct t_ZRTfQBsCy2cE9core0_0_03fmt7Display0g_B0g  { char _unused; } t_ZRTfQBsCy2cE9core0_0_03fmt7Display0g_B0g ;
typedef struct t_ZRTA1G2cE9core0_0_03fmt10ArgumentV10g  { struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  DATA[1]; } t_ZRTA1G2cE9core0_0_03fmt10ArgumentV10g ; // [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/; 1]
typedef struct t_ZRTA2BsCy  { SLICE_PTR  DATA[2]; } t_ZRTA2BsCy ; // [&'static str; 2]
 // (&'static str, u32, u32, )
typedef struct TUP_3_ZRTBsCy_ZRTCe_ZRTCe  {
	/*@0*/uint32_t _1; // u32
	/*@4*/uint32_t _2; // u32
	/*@8*/SLICE_PTR _0; // &'#omitted str
} TUP_3_ZRTBsCy_ZRTCe_ZRTCe ;
typedef char sizeof_assert_TUP_3_ZRTBsCy_ZRTCe_ZRTCe [ (sizeof(TUP_3_ZRTBsCy_ZRTCe_ZRTCe ) == 24) ? 1 : -1 ];
// PROTO extern "Rust" ::"nodrop-0_1_12"::imp::debug_assert_unreachable
tBANG  ZRG2cG12nodrop0_1_123imp24debug_assert_unreachable0g(void) // -> !
;
// PROTO extern "Rust" <::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/ /*- <'static,>*/>::new<'static,&'static str,>
static struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  ZRIG2cE9core0_0_03fmt10ArgumentV10g3new1gBsCy(
		SLICE_PTR *arg0, // &'static &'static str
		t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g arg1 // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 &'static str, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
		) // -> ::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/
;
// PROTO extern "Rust" <&'static str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  ZRQBsCy2cE9core0_0_03fmt7Display0g_B0g(
		SLICE_PTR *arg0, // &'static &'static str
		struct s_ZRG2cE9core0_0_03fmt9Formatter0g *arg1 // &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
;
// EXTERN extern "Rust" ::"core-0_0_0"::panicking::panic_fmt<'#local0,'static,>
extern tBANG  ZRG2cE9core0_0_09panicking9panic_fmt0g(
		struct s_ZRG2cE9core0_0_03fmt9Arguments0g arg0, // ::"core-0_0_0"::fmt::Arguments<'#local0,>/*S*/
		TUP_3_ZRTBsCy_ZRTCe_ZRTCe *arg1 // &'static (&'static str, u32, u32, )
		) // -> !
;
// EXTERN extern "Rust" <str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>
extern struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  ZRQCy2cE9core0_0_03fmt7Display0g_B0g(
		SLICE_PTR arg0, // &'static str
		struct s_ZRG2cE9core0_0_03fmt9Formatter0g *arg1 // &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
;
union u_static_ZRG4cG12nodrop0_1_123impB_0B_09FRAGMENTS0g{ t_ZRTA2BsCy val; uintptr_t raw[4]; } ZRG4cG12nodrop0_1_123impB_0B_09FRAGMENTS0g;	// static ::"nodrop-0_1_12"::imp::#0::#0::FRAGMENTS : [&'static str; 2]
union u_static_ZRG2cG12nodrop0_1_123impF6const00g{ SLICE_PTR val; uintptr_t raw[2]; } ZRG2cG12nodrop0_1_123impF6const00g;	// static ::"nodrop-0_1_12"::imp::const#0 : &'static str
union u_static_ZRG2cG12nodrop0_1_123impF6const10g{ TUP_3_ZRTBsCy_ZRTCe_ZRTCe val; uintptr_t raw[3]; } ZRG2cG12nodrop0_1_123impF6const10g;	// static ::"nodrop-0_1_12"::imp::const#1 : (&'static str, u32, u32, )
union u_static_ZRG4cG12nodrop0_1_123impB_0B_09FRAGMENTS0g ZRG4cG12nodrop0_1_123impB_0B_09FRAGMENTS0g = { .raw = {(uintptr_t)"",0x0ull,(uintptr_t)"",0x0ull} };	// static ::"nodrop-0_1_12"::imp::#0::#0::FRAGMENTS : [&'static str; 2] = 0010000000000000 0000000000000000 0010000000000000 0000000000000000{@0x0+8 = "", @0x10+8 = ""}
union u_static_ZRG2cG12nodrop0_1_123impF6const00g ZRG2cG12nodrop0_1_123impF6const00g = { .raw = {(uintptr_t)"Reached unreachable section: this is a bug!",0x2bull} };	// static ::"nodrop-0_1_12"::imp::const#0 : &'static str = 0010000000000000 2B00000000000000{@0x0+8 = "Reached unreachable section: this is a bug!"}
union u_static_ZRG2cG12nodrop0_1_123impF6const10g ZRG2cG12nodrop0_1_123impF6const10g = { .raw = {0x4d00000080ull,(uintptr_t)"rustc-1.29.0-src/src/vendor/nodrop/src/lib.rs",0x2dull} };	// static ::"nodrop-0_1_12"::imp::const#1 : (&'static str, u32, u32, ) = 800000004D000000 0010000000000000 2D00000000000000{@0x8+8 = "rustc-1.29.0-src/src/vendor/nodrop/src/lib.rs"}
// ::"nodrop-0_1_12"::imp::debug_assert_unreachable
tBANG  ZRG2cG12nodrop0_1_123imp24debug_assert_unreachable0g(void) // -> !

{
	tBANG rv;
	t_ZRTfQBsCy2cE9core0_0_03fmt7Display0g_B0g var0 = {0};	// fn{<&'static str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>}
	t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g var1;	// for<'elided#0,'elided#1,> extern "Rust" fn(&'static &'static str, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g var2;	// ::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/
	t_ZRTA1G2cE9core0_0_03fmt10ArgumentV10g var3;	// [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/; 1]
	t_ZRTA1G2cE9core0_0_03fmt10ArgumentV10g *var4;	// &'#local0 [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/; 1]
	tUNIT var5 = {0};	// ()
	struct s_ZRG2cE9core0_0_03fmt9Arguments0g var6;	// ::"core-0_0_0"::fmt::Arguments<'#local0,>/*S*/
	struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g var7;	// ::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>/*E*/
	SLICE_PTR var8;	// &'static [&'static str]
	SLICE_PTR var9;	// &'#local0 [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/]
	var8 = make_sliceptr(&ZRG4cG12nodrop0_1_123impB_0B_09FRAGMENTS0g.val, 0x2ull);	// _8 = MakeDst(&::"nodrop-0_1_12"::imp::#0::#0::FRAGMENTS, 0x2 usize)
	/* ZST assign */
	var1 = ZRQBsCy2cE9core0_0_03fmt7Display0g_B0g;	// _1 = Cast(_0 as for<'elided#0,'elided#1,> extern "Rust" fn(&'static &'static str, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/)
	var2 = ZRIG2cE9core0_0_03fmt10ArgumentV10g3new1gBsCy( &ZRG2cG12nodrop0_1_123impF6const00g.val, var1 );
	// ^ Call( _2 = <::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/ /*- <'static,>*/>::new<'static,&'static str,>( &::"nodrop-0_1_12"::imp::const#0, _1, ), bb1, bb2)
	var3.DATA[0] = var2;	// _3 = Array(_2)
	var4 = & var3;	// _4 = Borrow(Shared, _3)
	var9 = make_sliceptr(var4, 0x1ull);	// _9 = MakeDst(_4, 0x1 usize)
	memset(&var7, 0, sizeof(struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g ));	// _7 = Variant(::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],> #0, {})
	var6._0 = var8;
	var6._1 = var7;
	var6._2 = var9;	// _6 = Struct(::"core-0_0_0"::fmt::Arguments<'#local0,>, {_8, _7, _9})
	ZRG2cE9core0_0_09panicking9panic_fmt0g( var6, &ZRG2cG12nodrop0_1_123impF6const10g.val );
	// ^ Call( _5 = ::"core-0_0_0"::panicking::panic_fmt<'#local0,'static,>( _6, &::"nodrop-0_1_12"::imp::const#1, ), bb2, bb2)
bb2: _Unwind_Resume(); // Diverge
}
// <::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/ /*- <'static,>*/>::new<'static,&'static str,>
static struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  ZRIG2cE9core0_0_03fmt10ArgumentV10g3new1gBsCy(
		SLICE_PTR *arg0, // &'static &'static str
		t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g arg1 // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 &'static str, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
		) // -> ::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/

{
	struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g rv;
	t_ZRTF2BsG2cE9core0_0_03fmt4Void0gBuG2c_A_B9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g var0;	// for<'elided#0,'elided#1,> extern "Rust" fn(&'static ::"core-0_0_0"::fmt::Void/*S*/, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_03fmt4Void0g *var1;	// &'static ::"core-0_0_0"::fmt::Void/*S*/
	memcpy( &var0, &arg1, sizeof(t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g ));
	// ^ Call( _0 = "transmute"::<for<'elided#0,'elided#1,> extern "Rust" fn(&'static &'static str, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/,for<'elided#0,'elided#1,> extern "Rust" fn(&'static ::"core-0_0_0"::fmt::Void/*S*/, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/,>( a1, ), bb1, bb3)
	var1 = (void*)arg0;
	// ^ Call( _1 = "transmute"::<&'static &'static str,&'static ::"core-0_0_0"::fmt::Void/*S*/,>( a0, ), bb2, bb3)
	rv._0 = var1;
	rv._1 = var0;	// retval = Struct(::"core-0_0_0"::fmt::ArgumentV1<'static,>, {_1, _0})
	return rv;
	// ^ Return
bb3: _Unwind_Resume(); // Diverge
}
// <&'static str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  ZRQBsCy2cE9core0_0_03fmt7Display0g_B0g(
		SLICE_PTR *arg0, // &'static &'static str
		struct s_ZRG2cE9core0_0_03fmt9Formatter0g *arg1 // &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g rv;
	SLICE_PTR var0;	// &'static str
	var0 = (*arg0);	// _0 = Borrow(Shared, a0**)
	rv = ZRQCy2cE9core0_0_03fmt7Display0g_B0g( var0, arg1 );
	// ^ Call( retval = <str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>( _0, a1, ), bb1, bb2)
	return rv;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
