/*
 * AUTOGENERATED by mrustc
 */
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>
#include <assert.h>
#include <stdatomic.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <setjmp.h>
typedef uint32_t RUST_CHAR;
typedef uint8_t RUST_BOOL;
typedef struct { void* PTR; size_t META; } SLICE_PTR;
typedef struct { void* PTR; void* META; } TRAITOBJ_PTR;
typedef struct { void (*drop)(void*); size_t size; size_t align; } VTABLE_HDR;
typedef struct { char _d; } tUNIT;
typedef char tBANG;
typedef struct { char _d; } tTYPEID;
static inline size_t ALIGN_TO(size_t s, size_t a) { return (s + a-1) / a * a; }

extern void _Unwind_Resume(void) __attribute__((noreturn));
#define ALIGNOF(t) __alignof__(t)
extern __thread jmp_buf*    mrustc_panic_target;
extern __thread void* mrustc_panic_value;
static inline uint64_t __builtin_clz64(uint64_t v) {
	return ( (v >> 32) != 0 ? __builtin_clz(v>>32) : 32 + __builtin_clz(v));
}
static inline uint64_t __builtin_ctz64(uint64_t v) {
	return ((v&0xFFFFFFFF) == 0 ? __builtin_ctz(v>>32) + 32 : __builtin_ctz(v));
}
static inline uint8_t __mrustc_atomicloop8(volatile uint8_t* slot, uint8_t param, int ordering, uint8_t (*cb)(uint8_t, uint8_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint8_t v = atomic_load_explicit((_Atomic uint8_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint8_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint16_t __mrustc_atomicloop16(volatile uint16_t* slot, uint16_t param, int ordering, uint16_t (*cb)(uint16_t, uint16_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint16_t v = atomic_load_explicit((_Atomic uint16_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint16_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint32_t __mrustc_atomicloop32(volatile uint32_t* slot, uint32_t param, int ordering, uint32_t (*cb)(uint32_t, uint32_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint32_t v = atomic_load_explicit((_Atomic uint32_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint32_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint64_t __mrustc_atomicloop64(volatile uint64_t* slot, uint64_t param, int ordering, uint64_t (*cb)(uint64_t, uint64_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint64_t v = atomic_load_explicit((_Atomic uint64_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint64_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
typedef unsigned __int128 uint128_t;
typedef signed __int128 int128_t;
static inline uint128_t __builtin_bswap128(uint128_t v) {
	uint64_t lo = __builtin_bswap64((uint64_t)v);
	uint64_t hi = __builtin_bswap64((uint64_t)(v>>64));
	return ((uint128_t)lo << 64) | (uint128_t)hi;
}
static inline uint128_t intrinsic_ctlz_u128(uint128_t v) {
	return (v == 0 ? 128 : (v >> 64 != 0 ? __builtin_clz64(v>>64) : 64 + __builtin_clz64(v)));
}
static inline uint128_t intrinsic_cttz_u128(uint128_t v) {
	return (v == 0 ? 128 : ((v&0xFFFFFFFFFFFFFFFF) == 0 ? __builtin_ctz64(v>>64) + 64 : __builtin_ctz64(v)));
}

static inline int slice_cmp(SLICE_PTR l, SLICE_PTR r) {
	int rv = memcmp(l.PTR, r.PTR, l.META < r.META ? l.META : r.META);
	if(rv != 0) return rv;
	if(l.META < r.META) return -1;
	if(l.META > r.META) return 1;
	return 0;
}
static inline SLICE_PTR make_sliceptr(void* ptr, size_t s) { SLICE_PTR rv = { ptr, s }; return rv; }
static inline TRAITOBJ_PTR make_traitobjptr(void* ptr, void* vt) { TRAITOBJ_PTR rv = { ptr, vt }; return rv; }

static inline size_t mrustc_max(size_t a, size_t b) { return a < b ? b : a; }
static inline void noop_drop(tUNIT *p) { }

static inline size_t mrustc_string_search_linear(SLICE_PTR val, size_t count, SLICE_PTR* options) {
	for(size_t i = 0; i < count; i ++) {
		int cmp = slice_cmp(val, options[i]);
		if(cmp < 0) break;
		if(cmp == 0) return i;
	}
	return SIZE_MAX;
}
static const uint8_t __mrustc_revmap[16] = { 0, 8, 4,12, 2,10, 6,14,  1, 9, 5,13, 3, 7,15};
static inline uint8_t __mrustc_bitrev8(uint8_t v) { if(v==0||v==0xFF) return v; return __mrustc_revmap[v>>4]|(__mrustc_revmap[v&15]<<4); }
static inline uint16_t __mrustc_bitrev16(uint16_t v) { if(v==0) return 0; return ((uint16_t)__mrustc_bitrev8(v>>8))|((uint16_t)__mrustc_bitrev8(v)<<8); }
static inline uint32_t __mrustc_bitrev32(uint32_t v) { if(v==0) return 0; return ((uint32_t)__mrustc_bitrev16(v>>16))|((uint32_t)__mrustc_bitrev16(v)<<16); }
static inline uint64_t __mrustc_bitrev64(uint64_t v) { if(v==0) return 0; return ((uint64_t)__mrustc_bitrev32(v>>32))|((uint64_t)__mrustc_bitrev32(v)<<32); }
static inline uint128_t __mrustc_bitrev128(uint128_t v) { if(v==0) return 0; uint128_t rv = ((uint128_t)__mrustc_bitrev64(v>>64))|((uint128_t)__mrustc_bitrev64(v)<<64); return rv; }
static inline uint8_t __mrustc_op_umax8(uint8_t a, uint8_t b) { return (a > b ? a : b); }
static inline uint8_t __mrustc_op_umin8(uint8_t a, uint8_t b) { return (a < b ? a : b); }
static inline uint8_t __mrustc_op_imax8(uint8_t a, uint8_t b) { return ((int8_t)a > (int8_t)b ? a : b); }
static inline uint8_t __mrustc_op_imin8(uint8_t a, uint8_t b) { return ((int8_t)a < (int8_t)b ? a : b); }
static inline uint8_t __mrustc_op_and_not8(uint8_t a, uint8_t b) { return ~(a & b); }
static inline uint16_t __mrustc_op_umax16(uint16_t a, uint16_t b) { return (a > b ? a : b); }
static inline uint16_t __mrustc_op_umin16(uint16_t a, uint16_t b) { return (a < b ? a : b); }
static inline uint16_t __mrustc_op_imax16(uint16_t a, uint16_t b) { return ((int16_t)a > (int16_t)b ? a : b); }
static inline uint16_t __mrustc_op_imin16(uint16_t a, uint16_t b) { return ((int16_t)a < (int16_t)b ? a : b); }
static inline uint16_t __mrustc_op_and_not16(uint16_t a, uint16_t b) { return ~(a & b); }
static inline uint32_t __mrustc_op_umax32(uint32_t a, uint32_t b) { return (a > b ? a : b); }
static inline uint32_t __mrustc_op_umin32(uint32_t a, uint32_t b) { return (a < b ? a : b); }
static inline uint32_t __mrustc_op_imax32(uint32_t a, uint32_t b) { return ((int32_t)a > (int32_t)b ? a : b); }
static inline uint32_t __mrustc_op_imin32(uint32_t a, uint32_t b) { return ((int32_t)a < (int32_t)b ? a : b); }
static inline uint32_t __mrustc_op_and_not32(uint32_t a, uint32_t b) { return ~(a & b); }
static inline uint64_t __mrustc_op_umax64(uint64_t a, uint64_t b) { return (a > b ? a : b); }
static inline uint64_t __mrustc_op_umin64(uint64_t a, uint64_t b) { return (a < b ? a : b); }
static inline uint64_t __mrustc_op_imax64(uint64_t a, uint64_t b) { return ((int64_t)a > (int64_t)b ? a : b); }
static inline uint64_t __mrustc_op_imin64(uint64_t a, uint64_t b) { return ((int64_t)a < (int64_t)b ? a : b); }
static inline uint64_t __mrustc_op_and_not64(uint64_t a, uint64_t b) { return ~(a & b); }
struct s_ZRG3cD8std0_0_03ffi5c_str4CStr0g;
// struct ::"core-0_0_0"::result::Result#Ok<&'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>
struct s_ZRG2cE9core0_0_06resultG8ResultOk2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g  {
	/*@0*/uint8_t _1; // u8
	/*@8*/SLICE_PTR _0; // &'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g) == 24) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g) == 8) ? 1 : -1 ];
// struct ::"std-0_0_0"::ffi::c_str::FromBytesWithNulErrorKind#InteriorNul
struct s_ZRG3cD8std0_0_03ffi5c_strZ36FromBytesWithNulErrorKindInteriorNul0g  {
	/*@0*/uint8_t _1; // u8
	/*@8*/uintptr_t _0; // usize
} ;
typedef char sizeof_assert_ZRG3cD8std0_0_03ffi5c_strZ36FromBytesWithNulErrorKindInteriorNul0g[ (sizeof(struct s_ZRG3cD8std0_0_03ffi5c_strZ36FromBytesWithNulErrorKindInteriorNul0g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG3cD8std0_0_03ffi5c_strZ36FromBytesWithNulErrorKindInteriorNul0g[ (ALIGNOF(struct s_ZRG3cD8std0_0_03ffi5c_strZ36FromBytesWithNulErrorKindInteriorNul0g) == 8) ? 1 : -1 ];
// enum ::"std-0_0_0"::ffi::c_str::FromBytesWithNulErrorKind
struct e_ZRG3cD8std0_0_03ffi5c_str25FromBytesWithNulErrorKind0g {
	union {
		struct s_ZRG3cD8std0_0_03ffi5c_strZ36FromBytesWithNulErrorKindInteriorNul0g var_0;
		// ZST: ()
		uint8_t TAG;
	} DATA;
};
typedef char sizeof_assert_ZRG3cD8std0_0_03ffi5c_str25FromBytesWithNulErrorKind0g[ (sizeof(struct e_ZRG3cD8std0_0_03ffi5c_str25FromBytesWithNulErrorKind0g) == 16) ? 1 : -1 ];
// struct ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError
struct s_ZRG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g  {
	/*@0*/struct e_ZRG3cD8std0_0_03ffi5c_str25FromBytesWithNulErrorKind0g _0; // ::"std-0_0_0"::ffi::c_str::FromBytesWithNulErrorKind/*E*/
} ;
typedef char sizeof_assert_ZRG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g[ (sizeof(struct s_ZRG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g[ (ALIGNOF(struct s_ZRG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Err<&'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>
struct s_ZRG2cE9core0_0_06resultG9ResultErr2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g  {
	/*@0*/uint8_t _1; // u8
	/*@8*/struct s_ZRG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g _0; // ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g) == 24) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g) == 8) ? 1 : -1 ];
// enum ::"core-0_0_0"::result::Result<&'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>
struct e_ZRG2cE9core0_0_06result6Result2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g {
	union {
		struct s_ZRG2cE9core0_0_06resultG8ResultOk2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g var_0;
		struct s_ZRG2cE9core0_0_06resultG9ResultErr2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g var_1;
		uint8_t TAG;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06result6Result2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g[ (sizeof(struct e_ZRG2cE9core0_0_06result6Result2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g) == 24) ? 1 : -1 ];
struct e_ZRG1cE13libc0_2_42_H16c_void0g;
// struct ::"std-0_0_0"::ffi::c_str::CStr
struct s_ZRG3cD8std0_0_03ffi5c_str4CStr0g  {
	/*@0*/int8_t _0[0]; // [i8]
} ;
typedef char alignof_assert_ZRG3cD8std0_0_03ffi5c_str4CStr0g[ (ALIGNOF(struct s_ZRG3cD8std0_0_03ffi5c_str4CStr0g) == 1) ? 1 : -1 ];
struct s_ZRG2cE9core0_0_05panic9PanicInfo0g;
typedef struct t_ZRTfQBsCy2cE9core0_0_03fmt7Display0g_B0g  { char _unused; } t_ZRTfQBsCy2cE9core0_0_03fmt7Display0g_B0g ;
struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g;
struct s_ZRG2cE9core0_0_03fmt9Formatter0g;
typedef struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  (*t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g )( SLICE_PTR *, struct s_ZRG2cE9core0_0_03fmt9Formatter0g * ); // for<'elided#0,'elided#1,> extern "Rust" fn(&'static &'static str, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
struct s_ZRG2cE9core0_0_03fmt4Void0g;
typedef struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  (*t_ZRTF2BsG2cE9core0_0_03fmt4Void0gBuG2c_A_B9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g )( struct s_ZRG2cE9core0_0_03fmt4Void0g *, struct s_ZRG2cE9core0_0_03fmt9Formatter0g * ); // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 ::"core-0_0_0"::fmt::Void/*S*/, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
// struct ::"core-0_0_0"::fmt::ArgumentV1<'#local0,>
struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  {
	/*@0*/struct s_ZRG2cE9core0_0_03fmt4Void0g *_0; // &'#local0 ::"core-0_0_0"::fmt::Void/*S*/
	/*@8*/t_ZRTF2BsG2cE9core0_0_03fmt4Void0gBuG2c_A_B9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g _1; // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 ::"core-0_0_0"::fmt::Void/*S*/, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03fmt10ArgumentV10g[ (sizeof(struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03fmt10ArgumentV10g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g) == 8) ? 1 : -1 ];
typedef struct t_ZRTfQG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g2cE9core0_0_03fmt5Debug0g_F0g  { char _unused; } t_ZRTfQG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g2cE9core0_0_03fmt5Debug0g_F0g ;
typedef struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  (*t_ZRTF2BsG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0gBuG2cE9core0_0_03fmt9Formatter0gG2c_E6result6Result2gT0G2c_E_F5Error0g )( struct s_ZRG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g *, struct s_ZRG2cE9core0_0_03fmt9Formatter0g * ); // for<'elided#0,'elided#1,> extern "Rust" fn(&'static ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
typedef struct t_ZRTA2G2cE9core0_0_03fmt10ArgumentV10g  { struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  DATA[2]; } t_ZRTA2G2cE9core0_0_03fmt10ArgumentV10g ; // [::"core-0_0_0"::fmt::ArgumentV1<'#local3,>/*S*/; 2]
// struct ::"core-0_0_0"::option::Option#Some<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>
struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g  {
	/*@0*/SLICE_PTR _0; // &'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/]
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g[ (sizeof(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g) == 8) ? 1 : -1 ];
// enum ::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>
struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g {
	struct {
		struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g var_1;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g[ (sizeof(struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g) == 16) ? 1 : -1 ];
struct s_ZRG2cE9core0_0_03fmt9Arguments0g;
// struct ::"core-0_0_0"::option::Option#Some<&'#local2 ::"core-0_0_0"::fmt::Arguments<'#local2,>/*S*/,>
struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsG2c_A3fmt9Arguments0g  {
	/*@0*/struct s_ZRG2cE9core0_0_03fmt9Arguments0g *_0; // &'#local2 ::"core-0_0_0"::fmt::Arguments<'#local2,>/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gBsG2c_A3fmt9Arguments0g[ (sizeof(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsG2c_A3fmt9Arguments0g) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gBsG2c_A3fmt9Arguments0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsG2c_A3fmt9Arguments0g) == 8) ? 1 : -1 ];
// enum ::"core-0_0_0"::option::Option<&'#local2 ::"core-0_0_0"::fmt::Arguments<'#local2,>/*S*/,>
struct e_ZRG2cE9core0_0_06option6Option1gBsG2c_A3fmt9Arguments0g {
	struct {
		struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsG2c_A3fmt9Arguments0g var_1;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06option6Option1gBsG2c_A3fmt9Arguments0g[ (sizeof(struct e_ZRG2cE9core0_0_06option6Option1gBsG2c_A3fmt9Arguments0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::panic::Location<'#local2,>
struct s_ZRG2cE9core0_0_05panic8Location0g  {
	/*@0*/uint32_t _1; // u32
	/*@4*/uint32_t _2; // u32
	/*@8*/SLICE_PTR _0; // &'#local2 str
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_05panic8Location0g[ (sizeof(struct s_ZRG2cE9core0_0_05panic8Location0g) == 24) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_05panic8Location0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05panic8Location0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::panic::PanicInfo<'#local2,>
struct s_ZRG2cE9core0_0_05panic9PanicInfo0g  {
	/*@0*/struct e_ZRG2cE9core0_0_06option6Option1gBsG2c_A3fmt9Arguments0g _1; // ::"core-0_0_0"::option::Option<&'#local2 ::"core-0_0_0"::fmt::Arguments<'#local2,>/*S*/,>/*E*/
	/*@8*/TRAITOBJ_PTR _0; // &'#local2 dyn (::"core-0_0_0"::any::Any+::"core-0_0_0"::marker::Send)
	/*@24*/struct s_ZRG2cE9core0_0_05panic8Location0g _2; // ::"core-0_0_0"::panic::Location<'#local2,>/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_05panic9PanicInfo0g[ (sizeof(struct s_ZRG2cE9core0_0_05panic9PanicInfo0g) == 48) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_05panic9PanicInfo0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05panic9PanicInfo0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::fmt::Arguments<'#local4,>
struct s_ZRG2cE9core0_0_03fmt9Arguments0g  {
	/*@0*/SLICE_PTR _0; // &'#local4 [&'#local4 str]
	/*@16*/struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g _1; // ::"core-0_0_0"::option::Option<&'#local4 [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>/*E*/
	/*@32*/SLICE_PTR _2; // &'#local4 [::"core-0_0_0"::fmt::ArgumentV1<'#local4,>/*S*/]
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03fmt9Arguments0g[ (sizeof(struct s_ZRG2cE9core0_0_03fmt9Arguments0g) == 48) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03fmt9Arguments0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03fmt9Arguments0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Ok<(),::"core-0_0_0"::fmt::Error/*S*/,>
struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ()
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::fmt::Error
struct s_ZRG2cE9core0_0_03fmt5Error0g  {
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG2cE9core0_0_03fmt5Error0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03fmt5Error0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Err<(),::"core-0_0_0"::fmt::Error/*S*/,>
struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ::"core-0_0_0"::fmt::Error/*S*/
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
// enum ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>
struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g {
	union {
		struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A3fmt5Error0g var_0;
		struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A3fmt5Error0g var_1;
		uint8_t TAG;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g[ (sizeof(struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::any::TypeId
struct s_ZRG2cE9core0_0_03any6TypeId0g  {
	/*@0*/uint64_t _0; // u64
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03any6TypeId0g[ (sizeof(struct s_ZRG2cE9core0_0_03any6TypeId0g) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03any6TypeId0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03any6TypeId0g) == 8) ? 1 : -1 ];
struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g;
// struct ::"core-0_0_0"::panic::#0::NoPayload
struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g  {
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG3cE9core0_0_05panicB_09NoPayload0g[ (ALIGNOF(struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g) == 1) ? 1 : -1 ];
typedef struct t_ZRTA3BsCy  { SLICE_PTR  DATA[3]; } t_ZRTA3BsCy ; // [&'static str; 3]
 // (&'static str, u32, u32, )
typedef struct TUP_3_ZRTBsCy_ZRTCe_ZRTCe  {
	/*@0*/uint32_t _1; // u32
	/*@4*/uint32_t _2; // u32
	/*@8*/SLICE_PTR _0; // &'static str
} TUP_3_ZRTBsCy_ZRTCe_ZRTCe ;
typedef char sizeof_assert_TUP_3_ZRTBsCy_ZRTCe_ZRTCe [ (sizeof(TUP_3_ZRTBsCy_ZRTCe_ZRTCe ) == 24) ? 1 : -1 ];
typedef void (*t_ZRTF1PoT0T0 )( tUNIT * ); // extern "Rust" fn(*move (), ) -> ()
typedef struct s_ZRG2cE9core0_0_03any6TypeId0g  (*t_ZRTF1BsT0G2cE9core0_0_03any6TypeId0g )( tUNIT * ); // for<'elided#0,> extern "Rust" fn(&'H0 (), ) -> ::"core-0_0_0"::any::TypeId/*S*/
// struct ::"core-0_0_0"::any::Any#vtable
struct s_ZRG2cE9core0_0_03anyD9Anyvtable0g  {
	/*@0*/t_ZRTF1PoT0T0 _0; // extern "Rust" fn(*move (), ) -> ()
	/*@8*/uintptr_t _1; // usize
	/*@16*/uintptr_t _2; // usize
	/*@24*/t_ZRTF1BsT0G2cE9core0_0_03any6TypeId0g _3; // for<'elided#0,> extern "Rust" fn(&'H0 (), ) -> ::"core-0_0_0"::any::TypeId/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03anyD9Anyvtable0g[ (sizeof(struct s_ZRG2cE9core0_0_03anyD9Anyvtable0g) == 32) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03anyD9Anyvtable0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03anyD9Anyvtable0g) == 8) ? 1 : -1 ];
tTYPEID __typeid_ZRTG3cE9core0_0_05panicB_09NoPayload0g __attribute__((weak));
// PROTO extern "Rust" ::"core-0_0_0"::result::unwrap_failed<'static,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>
static tBANG  ZRG2cE9core0_0_06result13unwrap_failed1gG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g(
		SLICE_PTR arg0, // &'static str
		struct s_ZRG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g arg1 // ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/
		) // -> !
;
// PROTO extern "Rust" ::"num_cpus-1_8_0"::get_num_cpus
uintptr_t  ZRG1cI13num_cpus1_8_012get_num_cpus0g(void) // -> usize
;
// PROTO extern "Rust" ::"num_cpus-1_8_0"::get_num_physical_cpus
uintptr_t  ZRG1cI13num_cpus1_8_021get_num_physical_cpus0g(void) // -> usize
;
// PROTO extern "Rust" <::"core-0_0_0"::fmt::ArgumentV1<'#local0,>/*S*/ /*- <'static,>*/>::new<'#local1,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>
static struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  ZRIG2cE9core0_0_03fmt10ArgumentV10g3new1gG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g(
		struct s_ZRG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g *arg0, // &'#local1 ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/
		t_ZRTF2BsG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0gBuG2cE9core0_0_03fmt9Formatter0gG2c_E6result6Result2gT0G2c_E_F5Error0g arg1 // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
		) // -> ::"core-0_0_0"::fmt::ArgumentV1<'#local1,>/*S*/
;
// PROTO extern "Rust" <::"core-0_0_0"::fmt::ArgumentV1<'#local0,>/*S*/ /*- <'static,>*/>::new<'#local0,&'static str,>
static struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  ZRIG2cE9core0_0_03fmt10ArgumentV10g3new1gBsCy(
		SLICE_PTR *arg0, // &'#local0 &'static str
		t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g arg1 // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 &'static str, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
		) // -> ::"core-0_0_0"::fmt::ArgumentV1<'#local0,>/*S*/
;
// PROTO extern "Rust" <::"core-0_0_0"::panic::#0::NoPayload/*S*/ /*- */>::#drop_glue
static void  ZRIG3cE9core0_0_05panicB_09NoPayload0gA9drop_glue0g(
		struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g *arg0 // &'#omitted move ::"core-0_0_0"::panic::#0::NoPayload/*S*/
		) // -> ()
;
// PROTO extern "Rust" <::"core-0_0_0"::result::Result<&'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>/*E*/ /*- <&'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>*/>::expect<'static,>
static SLICE_PTR  ZRIG2cE9core0_0_06result6Result2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g6expect0g(
		struct e_ZRG2cE9core0_0_06result6Result2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g arg0, // ::"core-0_0_0"::result::Result<&'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>/*E*/
		SLICE_PTR arg1 // &'static str
		) // -> &'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/
;
// PROTO extern "Rust" <::"core-0_0_0"::panic::#0::NoPayload/*S*/ as ::"core-0_0_0"::any::Any>::get_type_id<'#omitted,>
static struct s_ZRG2cE9core0_0_03any6TypeId0g  ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0g11get_type_id0g(
		struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g *arg0 // &'#omitted ::"core-0_0_0"::panic::#0::NoPayload/*S*/
		) // -> ::"core-0_0_0"::any::TypeId/*S*/
;
// PROTO extern "Rust" <&'static str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  ZRQBsCy2cE9core0_0_03fmt7Display0g_B0g(
		SLICE_PTR *arg0, // &'static &'static str
		struct s_ZRG2cE9core0_0_03fmt9Formatter0g *arg1 // &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
;
// EXTERN extern "Rust" ::"core-0_0_0"::panicking::#0::panic_impl<'#local3,>
extern tBANG  ZRG3cE9core0_0_09panickingB_010panic_impl0g(
		struct s_ZRG2cE9core0_0_05panic9PanicInfo0g *arg0 // &'#local3 ::"core-0_0_0"::panic::PanicInfo<'#local3,>/*S*/
		) // -> !
 asm("_panic_impl");
// EXTERN extern "C" ::"libc-0_2_42_H1"::unix::bsd::apple::sysctlbyname
extern int32_t  ZRG4cE13libc0_2_42_H14unix3bsd5apple12sysctlbyname0g(
		int8_t *arg0, // *const i8
		struct e_ZRG1cE13libc0_2_42_H16c_void0g *arg1, // *mut ::"libc-0_2_42_H1"::c_void/*E*/
		uintptr_t *arg2, // *mut usize
		struct e_ZRG1cE13libc0_2_42_H16c_void0g *arg3, // *mut ::"libc-0_2_42_H1"::c_void/*E*/
		uintptr_t arg4 // usize
		) // -> i32
 asm("_sysctlbyname");
// EXTERN extern "C" ::"libc-0_2_42_H1"::unix::sysconf
extern int64_t  ZRG2cE13libc0_2_42_H14unix7sysconf0g(
		int32_t arg0 // i32
		) // -> i64
 asm("_sysconf");
// EXTERN extern "Rust" <::"std-0_0_0"::ffi::c_str::CStr/*S*/ /*- */>::from_bytes_with_nul<'static,>
extern struct e_ZRG2cE9core0_0_06result6Result2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g  ZRIG3cD8std0_0_03ffi5c_str4CStr0g19from_bytes_with_nul0g(
		SLICE_PTR arg0 // &'static [u8]
		) // -> ::"core-0_0_0"::result::Result<&'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>/*E*/
;
// EXTERN extern "Rust" <str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>
extern struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  ZRQCy2cE9core0_0_03fmt7Display0g_B0g(
		SLICE_PTR arg0, // &'static str
		struct s_ZRG2cE9core0_0_03fmt9Formatter0g *arg1 // &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
;
// EXTERN extern "Rust" <::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/ as ::"core-0_0_0"::fmt::Debug>::fmt<'static,'static,>
extern struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  ZRQG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g2cE9core0_0_03fmt5Debug0g_F0g(
		struct s_ZRG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g *arg0, // &'static ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/
		struct s_ZRG2cE9core0_0_03fmt9Formatter0g *arg1 // &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
;
extern union u_static_ZRG2cE9core0_0_05panicF6const00g{ struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g val; uint8_t raw[0]; } ZRG2cE9core0_0_05panicF6const00g;	// static ::"core-0_0_0"::panic::const#0 : ::"core-0_0_0"::panic::#0::NoPayload/*S*/
extern union u_static_ZRG3cE9core0_0_06resultB_19FRAGMENTS0g{ t_ZRTA3BsCy val; uintptr_t raw[6]; } ZRG3cE9core0_0_06resultB_19FRAGMENTS0g;	// static ::"core-0_0_0"::result::#1::FRAGMENTS : [&'static str; 3]
extern union u_static_ZRG2cE9core0_0_06resultF6const00g{ TUP_3_ZRTBsCy_ZRTCe_ZRTCe val; uintptr_t raw[3]; } ZRG2cE9core0_0_06resultF6const00g;	// static ::"core-0_0_0"::result::const#0 : (&'static str, u32, u32, )
__attribute__((weak)) union u_static_ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0gG6vtable0g{ struct s_ZRG2cE9core0_0_03anyD9Anyvtable0g val; uintptr_t raw[4]; } ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0gG6vtable0g;	// static <::"core-0_0_0"::panic::#0::NoPayload/*S*/ as ::"core-0_0_0"::any::Any>::vtable# : ::"core-0_0_0"::any::Any#vtable/*S*/
union u_static_ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0gG6vtable0g ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0gG6vtable0g = { .raw = {(uintptr_t)&ZRIG3cE9core0_0_05panicB_09NoPayload0gA9drop_glue0g,0x0ull,0x1ull,(uintptr_t)&ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0g11get_type_id0g} };	// static <::"core-0_0_0"::panic::#0::NoPayload/*S*/ as ::"core-0_0_0"::any::Any>::vtable# : ::"core-0_0_0"::any::Any#vtable/*S*/ = 0010000000000000 0000000000000000 0100000000000000 0010000000000000{@0x0+8 = &<::"core-0_0_0"::panic::#0::NoPayload/*S*/ /*- */>::#drop_glue, @0x18+8 = &<::"core-0_0_0"::panic::#0::NoPayload/*S*/ as ::"core-0_0_0"::any::Any>::get_type_id}
// ::"core-0_0_0"::result::unwrap_failed<'static,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>
static tBANG  ZRG2cE9core0_0_06result13unwrap_failed1gG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g(
		SLICE_PTR arg0, // &'static str
		struct s_ZRG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g arg1 // ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/
		) // -> !

{
	tBANG rv;
	SLICE_PTR *var0;	// &'#local0 &'static str
	t_ZRTfQBsCy2cE9core0_0_03fmt7Display0g_B0g var1 = {0};	// fn{<&'static str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>}
	t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g var2;	// for<'elided#0,'elided#1,> extern "Rust" fn(&'static &'static str, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g var3;	// ::"core-0_0_0"::fmt::ArgumentV1<'#local0,>/*S*/
	t_ZRTfQG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g2cE9core0_0_03fmt5Debug0g_F0g var4 = {0};	// fn{<::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/ as ::"core-0_0_0"::fmt::Debug>::fmt<'static,'static,>}
	t_ZRTF2BsG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0gBuG2cE9core0_0_03fmt9Formatter0gG2c_E6result6Result2gT0G2c_E_F5Error0g var5;	// for<'elided#0,'elided#1,> extern "Rust" fn(&'static ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g var6;	// ::"core-0_0_0"::fmt::ArgumentV1<'#local0,>/*S*/
	t_ZRTA2G2cE9core0_0_03fmt10ArgumentV10g var7;	// [::"core-0_0_0"::fmt::ArgumentV1<'#local3,>/*S*/; 2]
	t_ZRTA2G2cE9core0_0_03fmt10ArgumentV10g *var8;	// &'#local2 [::"core-0_0_0"::fmt::ArgumentV1<'#local3,>/*S*/; 2]
	struct s_ZRG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g *var9;	// &'#local1 ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/
	struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g var10;	// ::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>/*E*/
	SLICE_PTR var11;	// &'static [&'static str]
	SLICE_PTR var12;	// &'#local2 [::"core-0_0_0"::fmt::ArgumentV1<'#local3,>/*S*/]
	struct s_ZRG2cE9core0_0_05panic9PanicInfo0g var13;	// ::"core-0_0_0"::panic::PanicInfo<'#local2,>/*S*/
	struct s_ZRG2cE9core0_0_03fmt9Arguments0g *var14;	// &'#local0 ::"core-0_0_0"::fmt::Arguments<'#local4,>/*S*/
	struct s_ZRG2cE9core0_0_05panic9PanicInfo0g *var15;	// &'#local1 ::"core-0_0_0"::panic::PanicInfo<'#local2,>/*S*/
	tBANG var16 = {0};	// !
	TRAITOBJ_PTR var17;	// &'#local2 dyn (::"core-0_0_0"::any::Any+::"core-0_0_0"::marker::Send)
	struct s_ZRG2cE9core0_0_05panic8Location0g var18;	// ::"core-0_0_0"::panic::Location<'static,>/*S*/
	struct e_ZRG2cE9core0_0_06option6Option1gBsG2c_A3fmt9Arguments0g var19;	// ::"core-0_0_0"::option::Option<&'#local0 ::"core-0_0_0"::fmt::Arguments<'#local4,>/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_03fmt9Arguments0g var20;	// ::"core-0_0_0"::fmt::Arguments<'#local4,>/*S*/
	var0 = & arg0;	// _0 = Borrow(Shared, a0)
	var9 = & arg1;	// _9 = Borrow(Shared, a1)
	var11 = make_sliceptr(&ZRG3cE9core0_0_06resultB_19FRAGMENTS0g.val, 0x3ull);	// _11 = MakeDst(&::"core-0_0_0"::result::#1::FRAGMENTS, 0x3 usize)
	/* ZST assign */
	var2 = ZRQBsCy2cE9core0_0_03fmt7Display0g_B0g;	// _2 = Cast(_1 as for<'elided#0,'elided#1,> extern "Rust" fn(&'static &'static str, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/)
	var3 = ZRIG2cE9core0_0_03fmt10ArgumentV10g3new1gBsCy( var0, var2 );
	// ^ Call( _3 = <::"core-0_0_0"::fmt::ArgumentV1<'#local0,>/*S*/ /*- <'static,>*/>::new<'#local0,&'static str,>( _0, _2, ), bb1, bb3)
	/* ZST assign */
	var5 = ZRQG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g2cE9core0_0_03fmt5Debug0g_F0g;	// _5 = Cast(_4 as for<'elided#0,'elided#1,> extern "Rust" fn(&'static ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/)
	var6 = ZRIG2cE9core0_0_03fmt10ArgumentV10g3new1gG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g( var9, var5 );
	// ^ Call( _6 = <::"core-0_0_0"::fmt::ArgumentV1<'#local0,>/*S*/ /*- <'static,>*/>::new<'#local1,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>( _9, _5, ), bb2, bb3)
	var7.DATA[0] = var3;
	var7.DATA[1] = var6;	// _7 = Array(_3, _6)
	var8 = & var7;	// _8 = Borrow(Shared, _7)
	var12 = make_sliceptr(var8, 0x2ull);	// _12 = MakeDst(_8, 0x2 usize)
	memset(&var10, 0, sizeof(struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g ));	// _10 = Variant(::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],> #0, {})
	var20._0 = var11;
	var20._1 = var10;
	var20._2 = var12;	// _20 = Struct(::"core-0_0_0"::fmt::Arguments<'#local4,>, {_11, _10, _12})
	var14 = & var20;	// _14 = Borrow(Shared, _20)
	var19.DATA.var_1._0 = var14;	// _19 = Variant(::"core-0_0_0"::option::Option<&'#local0 ::"core-0_0_0"::fmt::Arguments<'#local4,>/*S*/,> #1, {_14})
	var18._0 = ZRG2cE9core0_0_06resultF6const00g.val._0;
	var18._1 = ZRG2cE9core0_0_06resultF6const00g.val._1;
	var18._2 = ZRG2cE9core0_0_06resultF6const00g.val._2;	// _18 = Struct(::"core-0_0_0"::panic::Location<'static,>, {(::"core-0_0_0"::result::const#0).0, (::"core-0_0_0"::result::const#0).1, (::"core-0_0_0"::result::const#0).2})
	var17 = make_traitobjptr(&ZRG2cE9core0_0_05panicF6const00g.val, &ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0gG6vtable0g.val);	// _17 = MakeDst(&::"core-0_0_0"::panic::const#0, &<::"core-0_0_0"::panic::#0::NoPayload/*S*/ as ::"core-0_0_0"::any::Any>::vtable#)
	var13._0 = var17;
	var13._1 = var19;
	var13._2 = var18;	// _13 = Struct(::"core-0_0_0"::panic::PanicInfo<'#local2,>, {_17, _19, _18})
	var15 = & var13;	// _15 = Borrow(Shared, _13)
	ZRG3cE9core0_0_09panickingB_010panic_impl0g( var15 );
	// ^ Call( _16 = ::"core-0_0_0"::panicking::#0::panic_impl<'#local3,>( _15, ), bb3, bb3)
bb3: _Unwind_Resume(); // Diverge
}
// ::"num_cpus-1_8_0"::get_num_cpus
uintptr_t  ZRG1cI13num_cpus1_8_012get_num_cpus0g(void) // -> usize

{
	uintptr_t rv;
	int64_t var0;	// i64
	RUST_BOOL var1;	// bool
	var0 = ZRG2cE13libc0_2_42_H14unix7sysconf0g( 57 );
	// ^ Call( _0 = ::"libc-0_2_42_H1"::unix::sysconf( +57 i32, ), bb1, bb2)
	var1 = var0 < 1ll;	// _1 = BinOp(_0 LT +1 i64)
	if(var1) goto bb3; else goto bb4;
	// ^ If( _1 : 3, 4)
bb2: _Unwind_Resume(); // Diverge
bb3:
	rv = 0x1ull;	// retval = Constant(0x1 usize)
	return rv;
	// ^ Return
bb4:
	rv = (uintptr_t )var0;	// retval = Cast(_0 as usize)
	return rv;
	// ^ Return
}
// ::"num_cpus-1_8_0"::get_num_physical_cpus
uintptr_t  ZRG1cI13num_cpus1_8_021get_num_physical_cpus0g(void) // -> usize

{
	uintptr_t rv;
	int32_t var0;	// i32
	uintptr_t var1;	// usize
	RUST_BOOL var2;	// bool
	SLICE_PTR var3;	// &'static [u8]
	struct e_ZRG2cE9core0_0_06result6Result2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g var4;	// ::"core-0_0_0"::result::Result<&'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>/*E*/
	int8_t *var5;	// *const i8
	int32_t *var6;	// &'#local1 mut i32
	int32_t *var7;	// *mut i32
	struct e_ZRG1cE13libc0_2_42_H16c_void0g *var8;	// *mut ::"libc-0_2_42_H1"::c_void/*E*/
	uintptr_t *var9;	// &'#local2 mut usize
	uintptr_t *var10;	// *mut usize
	int32_t var11;	// i32
	SLICE_PTR var12;	// *const [i8]
	SLICE_PTR var13;	// &'static [i8]
	SLICE_PTR var14;	// &'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/
	struct e_ZRG1cE13libc0_2_42_H16c_void0g *var15;	// *mut ::"libc-0_2_42_H1"::c_void/*E*/
	uintptr_t var16;	// usize
	var0 = 0;	// _0 = Constant(+0 i32)
	var1 = 0x4ull;	// _1 = Constant(0x4 usize)
	var3 = make_sliceptr((void*)"hw.physicalcpu\x00", 0xfull);	// _3 = MakeDst(b"hw.physicalcpu\x00", 0xf usize)
	var4 = ZRIG3cD8std0_0_03ffi5c_str4CStr0g19from_bytes_with_nul0g( var3 );
	// ^ Call( _4 = <::"std-0_0_0"::ffi::c_str::CStr/*S*/ /*- */>::from_bytes_with_nul<'static,>( _3, ), bb1, bb4)
	var14 = ZRIG2cE9core0_0_06result6Result2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g6expect0g( var4, make_sliceptr("byte literal is missing NUL", 27) );
	// ^ Call( _14 = <::"core-0_0_0"::result::Result<&'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>/*E*/ /*- <&'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>*/>::expect<'static,>( _4, "byte literal is missing NUL", ), bb2, bb4)
	var13 = make_sliceptr(&((struct s_ZRG3cD8std0_0_03ffi5c_str4CStr0g *)var14.PTR)->_0, var14.META);	// _13 = Borrow(Shared, _14*.0)
	var12 = var13;	// _12 = Cast(_13 as *const [i8])
	var5 = (int8_t *)var12.PTR;	// _5 = Cast(_12 as *const i8)
	var6 = & var0;	// _6 = Borrow(Unique, _0)
	var7 = (int32_t *)var6;	// _7 = Cast(_6 as *mut i32)
	var8 = (struct e_ZRG1cE13libc0_2_42_H16c_void0g *)var7;	// _8 = Cast(_7 as *mut ::"libc-0_2_42_H1"::c_void/*E*/)
	var9 = & var1;	// _9 = Borrow(Unique, _1)
	var10 = (uintptr_t *)var9;	// _10 = Cast(_9 as *mut usize)
	var16 = 0x0ull;	// _16 = Constant(0x0 usize)
	var15 = (struct e_ZRG1cE13libc0_2_42_H16c_void0g *)var16;	// _15 = Cast(_16 as *mut ::"libc-0_2_42_H1"::c_void/*E*/)
	var11 = ZRG4cE13libc0_2_42_H14unix3bsd5apple12sysctlbyname0g( var5, var8, var10, var15, 0x0ull );
	// ^ Call( _11 = ::"libc-0_2_42_H1"::unix::bsd::apple::sysctlbyname( _5, _8, _10, _15, 0x0 usize, ), bb3, bb4)
	var2 = 0 != var11;	// _2 = BinOp(+0 i32 NE _11)
	if(var2) goto bb5; else goto bb7;
	// ^ If( _2 : 5, 7)
bb4: _Unwind_Resume(); // Diverge
bb5:
	rv = ZRG1cI13num_cpus1_8_012get_num_cpus0g( );
	// ^ Call( retval = ::"num_cpus-1_8_0"::get_num_cpus( ), bb6, bb4)
	return rv;
	// ^ Return
bb7:
	rv = (uintptr_t )var0;	// retval = Cast(_0 as usize)
	return rv;
	// ^ Return
}
// <::"core-0_0_0"::fmt::ArgumentV1<'#local0,>/*S*/ /*- <'static,>*/>::new<'#local1,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>
static struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  ZRIG2cE9core0_0_03fmt10ArgumentV10g3new1gG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g(
		struct s_ZRG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g *arg0, // &'#local1 ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/
		t_ZRTF2BsG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0gBuG2cE9core0_0_03fmt9Formatter0gG2c_E6result6Result2gT0G2c_E_F5Error0g arg1 // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
		) // -> ::"core-0_0_0"::fmt::ArgumentV1<'#local1,>/*S*/

{
	struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g rv;
	t_ZRTF2BsG2cE9core0_0_03fmt4Void0gBuG2c_A_B9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g var0;	// for<'elided#0,'elided#1,> extern "Rust" fn(&'static ::"core-0_0_0"::fmt::Void/*S*/, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_03fmt4Void0g *var1;	// &'#local1 ::"core-0_0_0"::fmt::Void/*S*/
	memcpy( &var0, &arg1, sizeof(t_ZRTF2BsG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0gBuG2cE9core0_0_03fmt9Formatter0gG2c_E6result6Result2gT0G2c_E_F5Error0g ));
	// ^ Call( _0 = "transmute"::<for<'elided#0,'elided#1,> extern "Rust" fn(&'static ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/,for<'elided#0,'elided#1,> extern "Rust" fn(&'static ::"core-0_0_0"::fmt::Void/*S*/, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/,>( a1, ), bb1, bb3)
	var1 = (void*)arg0;
	// ^ Call( _1 = "transmute"::<&'#local1 ::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,&'#local1 ::"core-0_0_0"::fmt::Void/*S*/,>( a0, ), bb2, bb3)
	rv._0 = var1;
	rv._1 = var0;	// retval = Struct(::"core-0_0_0"::fmt::ArgumentV1<'#local1,>, {_1, _0})
	return rv;
	// ^ Return
bb3: _Unwind_Resume(); // Diverge
}
// <::"core-0_0_0"::fmt::ArgumentV1<'#local0,>/*S*/ /*- <'static,>*/>::new<'#local0,&'static str,>
static struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  ZRIG2cE9core0_0_03fmt10ArgumentV10g3new1gBsCy(
		SLICE_PTR *arg0, // &'#local0 &'static str
		t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g arg1 // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 &'static str, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
		) // -> ::"core-0_0_0"::fmt::ArgumentV1<'#local0,>/*S*/

{
	struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g rv;
	t_ZRTF2BsG2cE9core0_0_03fmt4Void0gBuG2c_A_B9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g var0;	// for<'elided#0,'elided#1,> extern "Rust" fn(&'static ::"core-0_0_0"::fmt::Void/*S*/, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_03fmt4Void0g *var1;	// &'#local0 ::"core-0_0_0"::fmt::Void/*S*/
	memcpy( &var0, &arg1, sizeof(t_ZRTF2BsBsCyBuG2cE9core0_0_03fmt9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g ));
	// ^ Call( _0 = "transmute"::<for<'elided#0,'elided#1,> extern "Rust" fn(&'static &'static str, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/,for<'elided#0,'elided#1,> extern "Rust" fn(&'static ::"core-0_0_0"::fmt::Void/*S*/, &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/,>( a1, ), bb1, bb3)
	var1 = (void*)arg0;
	// ^ Call( _1 = "transmute"::<&'#local0 &'static str,&'#local0 ::"core-0_0_0"::fmt::Void/*S*/,>( a0, ), bb2, bb3)
	rv._0 = var1;
	rv._1 = var0;	// retval = Struct(::"core-0_0_0"::fmt::ArgumentV1<'#local0,>, {_1, _0})
	return rv;
	// ^ Return
bb3: _Unwind_Resume(); // Diverge
}
// <::"core-0_0_0"::panic::#0::NoPayload/*S*/ /*- */>::#drop_glue
static void  ZRIG3cE9core0_0_05panicB_09NoPayload0gA9drop_glue0g(
		struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g *arg0 // &'#omitted move ::"core-0_0_0"::panic::#0::NoPayload/*S*/
		) // -> ()

{
	tUNIT rv;
	/* ZST assign */
	return ;
	// ^ Return
}
// <::"core-0_0_0"::result::Result<&'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>/*E*/ /*- <&'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>*/>::expect<'static,>
static SLICE_PTR  ZRIG2cE9core0_0_06result6Result2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g6expect0g(
		struct e_ZRG2cE9core0_0_06result6Result2gBsG3cD8std0_0_03ffi5c_str4CStr0gG3c_D_E_F21FromBytesWithNulError0g arg0, // ::"core-0_0_0"::result::Result<&'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>/*E*/
		SLICE_PTR arg1 // &'static str
		) // -> &'static ::"std-0_0_0"::ffi::c_str::CStr/*S*/

{
	SLICE_PTR rv;
	tBANG var0 = {0};	// !
	if( arg0.DATA.TAG == 0) {goto bb1;} else {goto bb2;}
	// ^ Switch( a0 : 0 => bb1, 1 => bb2, )
bb1:
	rv = arg0.DATA.var_0._0;	// retval = Use(a0#0.0)
	return rv;
	// ^ Return
bb2:
	ZRG2cE9core0_0_06result13unwrap_failed1gG3cD8std0_0_03ffi5c_str21FromBytesWithNulError0g( arg1, arg0.DATA.var_1._0 );
	// ^ Call( _0 = ::"core-0_0_0"::result::unwrap_failed<'static,::"std-0_0_0"::ffi::c_str::FromBytesWithNulError/*S*/,>( a1, a0#1.0, ), bb3, bb3)
bb3: _Unwind_Resume(); // Diverge
}
// <::"core-0_0_0"::panic::#0::NoPayload/*S*/ as ::"core-0_0_0"::any::Any>::get_type_id<'#omitted,>
static struct s_ZRG2cE9core0_0_03any6TypeId0g  ZRQG3cE9core0_0_05panicB_09NoPayload0g2c_A3any3Any0g11get_type_id0g(
		struct s_ZRG3cE9core0_0_05panicB_09NoPayload0g *arg0 // &'#omitted ::"core-0_0_0"::panic::#0::NoPayload/*S*/
		) // -> ::"core-0_0_0"::any::TypeId/*S*/

{
	struct s_ZRG2cE9core0_0_03any6TypeId0g rv;
	uint64_t var0;	// u64
	var0 = (uintptr_t)&__typeid_ZRTG3cE9core0_0_05panicB_09NoPayload0g;
	// ^ Call( _0 = "type_id"::<::"core-0_0_0"::panic::#0::NoPayload/*S*/,>( ), bb1, bb2)
	rv._0 = var0;	// retval = Struct(::"core-0_0_0"::any::TypeId, {_0})
	return rv;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
// <&'static str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  ZRQBsCy2cE9core0_0_03fmt7Display0g_B0g(
		SLICE_PTR *arg0, // &'static &'static str
		struct s_ZRG2cE9core0_0_03fmt9Formatter0g *arg1 // &'static mut ::"core-0_0_0"::fmt::Formatter<'static,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g rv;
	SLICE_PTR var0;	// &'static str
	var0 = (*arg0);	// _0 = Borrow(Shared, a0**)
	rv = ZRQCy2cE9core0_0_03fmt7Display0g_B0g( var0, arg1 );
	// ^ Call( retval = <str as ::"core-0_0_0"::fmt::Display>::fmt<'static,'static,>( _0, a1, ), bb1, bb2)
	return rv;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
