/*
 * AUTOGENERATED by mrustc
 */
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>
#include <assert.h>
#include <stdatomic.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <setjmp.h>
typedef uint32_t RUST_CHAR;
typedef uint8_t RUST_BOOL;
typedef struct { void* PTR; size_t META; } SLICE_PTR;
typedef struct { void* PTR; void* META; } TRAITOBJ_PTR;
typedef struct { void (*drop)(void*); size_t size; size_t align; } VTABLE_HDR;
typedef struct { char _d; } tUNIT;
typedef char tBANG;
typedef struct { char _d; } tTYPEID;
static inline size_t ALIGN_TO(size_t s, size_t a) { return (s + a-1) / a * a; }

extern void _Unwind_Resume(void) __attribute__((noreturn));
#define ALIGNOF(t) __alignof__(t)
extern __thread jmp_buf*    mrustc_panic_target;
extern __thread void* mrustc_panic_value;
static inline uint64_t __builtin_clz64(uint64_t v) {
	return ( (v >> 32) != 0 ? __builtin_clz(v>>32) : 32 + __builtin_clz(v));
}
static inline uint64_t __builtin_ctz64(uint64_t v) {
	return ((v&0xFFFFFFFF) == 0 ? __builtin_ctz(v>>32) + 32 : __builtin_ctz(v));
}
static inline uint8_t __mrustc_atomicloop8(volatile uint8_t* slot, uint8_t param, int ordering, uint8_t (*cb)(uint8_t, uint8_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint8_t v = atomic_load_explicit((_Atomic uint8_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint8_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint16_t __mrustc_atomicloop16(volatile uint16_t* slot, uint16_t param, int ordering, uint16_t (*cb)(uint16_t, uint16_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint16_t v = atomic_load_explicit((_Atomic uint16_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint16_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint32_t __mrustc_atomicloop32(volatile uint32_t* slot, uint32_t param, int ordering, uint32_t (*cb)(uint32_t, uint32_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint32_t v = atomic_load_explicit((_Atomic uint32_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint32_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint64_t __mrustc_atomicloop64(volatile uint64_t* slot, uint64_t param, int ordering, uint64_t (*cb)(uint64_t, uint64_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint64_t v = atomic_load_explicit((_Atomic uint64_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint64_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
typedef struct { uint64_t lo, hi; } uint128_t;
typedef struct { uint64_t lo, hi; } int128_t;
static inline uint128_t intrinsic_ctlz_u128(uint128_t v);
static inline uint128_t shl128(uint128_t a, uint32_t b);
static inline uint128_t shr128(uint128_t a, uint32_t b);
static inline float make_float(int is_neg, int exp, uint32_t mantissa_bits) { float rv; uint32_t vi=(mantissa_bits&((1<<23)-1))|((exp+127)<<23);if(is_neg)vi|=1<<31; memcpy(&rv, &vi, 4); return rv; }
static inline double make_double(int is_neg, int exp, uint32_t mantissa_bits) { double rv; uint64_t vi=(mantissa_bits&((1ull<<52)-1))|((uint64_t)(exp+1023)<<52);if(is_neg)vi|=1ull<<63; memcpy(&rv, &vi, 4); return rv; }
static inline uint128_t make128_raw(uint64_t hi, uint64_t lo) { uint128_t rv = { lo, hi }; return rv; }
static inline uint128_t make128(uint64_t v) { uint128_t rv = { v, 0 }; return rv; }
static inline float cast128_float(uint128_t v) { int n = intrinsic_ctlz_u128(v).lo; uint128_t y = shl128(v, n); uint64_t a = (y.hi >> ((128-(23+1))-64)); uint64_t b = shr128(y, (64-(23+1))).lo | (y.lo & 0xFFFFFFFFFF); uint64_t m = a + ((b - ((b >> 63) & ~a)) >> 63); uint64_t e = (v.lo == 0 && v.hi == 0) ? 0 : (127 - n)+127-1; uint32_t vi = (e << 23) + m; float rv; memcpy(&rv, &vi, sizeof(rv)); return rv; }
static inline double cast128_double(uint128_t v) { int n = intrinsic_ctlz_u128(v).lo; uint128_t y = shl128(v, n); uint64_t a = (y.hi >> ((128-(52+1))-64)); uint64_t b = shr128(y, (64-(52+1))).lo | (y.lo & 0x7FF); uint64_t m = a + ((b - (b >> 63 & ~a)) >> 63); uint64_t e = (v.lo == 0 && v.hi == 0) ? 0 : (127 - n)+1023-1; uint64_t vi = (e << 52) + m; double rv; memcpy(&rv, &vi, sizeof(rv)); return rv; }
static inline int cmp128(uint128_t a, uint128_t b) { if(a.hi != b.hi) return a.hi < b.hi ? -1 : 1; if(a.lo != b.lo) return a.lo < b.lo ? -1 : 1; return 0; }
static inline bool add128_o(uint128_t a, uint128_t b, uint128_t* o) { o->lo = a.lo + b.lo; o->hi = a.hi + b.hi + (o->lo < a.lo ? 1 : 0); return (o->hi < a.hi); }
static inline bool sub128_o(uint128_t a, uint128_t b, uint128_t* o) { o->lo = a.lo - b.lo; o->hi = a.hi - b.hi - (a.lo < b.lo ? 1 : 0); return (o->hi > a.hi); }
static inline bool mul128_o(uint128_t a, uint128_t b, uint128_t* o) { bool of = false; o->hi = 0; o->lo = 0; for(int i=0;i<128;i++){ uint64_t m = (1ull << (i % 64)); if(a.hi==0&&a.lo<m)   break; if(i>=64&&a.hi<m) break; if( m & (i >= 64 ? a.hi : a.lo) ) of |= add128_o(*o, b, o); b.hi = (b.hi << 1) | (b.lo >> 63); b.lo = (b.lo << 1); } return of;}
static inline bool div128_o(uint128_t a, uint128_t b, uint128_t* q, uint128_t* r) { if(a.hi == 0 && b.hi == 0) { if(q) { q->hi=0; q->lo = a.lo / b.lo; } if(r) { r->hi=0; r->lo = a.lo % b.lo; } return false; } if(cmp128(a, b) < 0) { if(q) { q->hi=0; q->lo=0; } if(r) *r = a; return false; } uint128_t a_div_2 = {(a.lo>>1)|(a.hi << 63), a.hi>>1}; int shift = 0; while( cmp128(a_div_2, b) >= 0 && shift < 128 ) { shift += 1; b.hi = (b.hi<<1)|(b.lo>>63); b.lo <<= 1; } if(shift == 128) return true; uint128_t mask = { /*lo=*/(shift >= 64 ? 0 : (1ull << shift)), /*hi=*/(shift < 64 ? 0 : 1ull << (shift-64)) }; shift ++; if(q) { q->hi = 0; q->lo = 0; } while(shift--) { if( cmp128(a, b) >= 0 ) { if(q) add128_o(*q, mask, q); sub128_o(a, b, &a); } mask.lo = (mask.lo >> 1) | (mask.hi << 63); mask.hi >>= 1; b.lo = (b.lo >> 1) | (b.hi << 63); b.hi >>= 1; } if(r) *r = a; return false;}
static inline uint128_t add128(uint128_t a, uint128_t b) { uint128_t v; add128_o(a, b, &v); return v; }
static inline uint128_t sub128(uint128_t a, uint128_t b) { uint128_t v; sub128_o(a, b, &v); return v; }
static inline uint128_t mul128(uint128_t a, uint128_t b) { uint128_t v; mul128_o(a, b, &v); return v; }
static inline uint128_t div128(uint128_t a, uint128_t b) { uint128_t v; div128_o(a, b, &v, NULL); return v; }
static inline uint128_t mod128(uint128_t a, uint128_t b) { uint128_t v; div128_o(a, b, NULL, &v); return v;}
static inline uint128_t and128(uint128_t a, uint128_t b) { uint128_t v = { a.lo & b.lo, a.hi & b.hi }; return v; }
static inline uint128_t or128 (uint128_t a, uint128_t b) { uint128_t v = { a.lo | b.lo, a.hi | b.hi }; return v; }
static inline uint128_t xor128(uint128_t a, uint128_t b) { uint128_t v = { a.lo ^ b.lo, a.hi ^ b.hi }; return v; }
static inline uint128_t shl128(uint128_t a, uint32_t b) { uint128_t v; if(b == 0) { return a; } else if(b < 64) { v.lo = a.lo << b; v.hi = (a.hi << b) | (a.lo >> (64 - b)); } else { v.hi = a.lo << (b - 64); v.lo = 0; } return v; }
static inline uint128_t shr128(uint128_t a, uint32_t b) { uint128_t v; if(b == 0) { return a; } else if(b < 64) { v.lo = (a.lo >> b)|(a.hi << (64 - b)); v.hi = a.hi >> b; } else { v.lo = a.hi >> (b - 64); v.hi = 0; } return v; }
static inline uint128_t popcount128(uint128_t a) { uint128_t v = { __builtin_popcountll(a.lo) + __builtin_popcountll(a.hi), 0 }; return v; }
static inline uint128_t __builtin_bswap128(uint128_t v) { uint128_t rv = { __builtin_bswap64(v.hi), __builtin_bswap64(v.lo) }; return rv; }
static inline uint128_t intrinsic_ctlz_u128(uint128_t v) {
	uint128_t rv = { (v.hi != 0 ? __builtin_clz64(v.hi) : (v.lo != 0 ? 64 + __builtin_clz64(v.lo) : 128)), 0 };
	return rv;
}
static inline uint128_t intrinsic_cttz_u128(uint128_t v) {
	uint128_t rv = { (v.lo == 0 ? (v.hi == 0 ? 128 : __builtin_ctz64(v.hi) + 64) : __builtin_ctz64(v.lo)), 0 };
	return rv;
}
static inline int128_t make128s_raw(uint64_t hi, uint64_t lo) { int128_t rv = { lo, hi }; return rv; }
static inline int128_t make128s(int64_t v) { int128_t rv = { v, (v < 0 ? -1 : 0) }; return rv; }
static inline int128_t neg128s(int128_t v) { int128_t rv = { ~v.lo+1, ~v.hi + (v.lo == 0) }; return rv; }
static inline float cast128s_float(int128_t v) { int sgn = (v.hi >> 63); int128_t abs = sgn ? neg128s(v) : v; return (sgn ? -1.0 : 1.0) * cast128_float(make128_raw(v.hi,v.lo)); }
static inline double cast128s_double(int128_t v) { int sgn = (v.hi >> 63); int128_t abs = sgn ? neg128s(v) : v; return (sgn ? -1.0 : 1.0) * cast128_double(make128_raw(v.hi,v.lo)); }
static inline int cmp128s(int128_t a, int128_t b) { if(a.hi != b.hi) return (int64_t)a.hi < (int64_t)b.hi ? -1 : 1; if(a.lo != b.lo) return a.lo < b.lo ? -1 : 1; return 0; }
static inline bool add128s_o(int128_t a, int128_t b, int128_t* o) { bool sgna=a.hi>>63; bool sgnb=b.hi>>63; add128_o(*(uint128_t*)&a, *(uint128_t*)&b, (uint128_t*)o); bool sgno = o->hi>>63; return (sgna==sgnb && sgno != sgna); }
static inline bool sub128s_o(int128_t a, int128_t b, int128_t* o) { bool sgna=a.hi>>63; bool sgnb=b.hi>>63; sub128_o(*(uint128_t*)&a, *(uint128_t*)&b, (uint128_t*)o); bool sgno = o->hi>>63; return (sgna!=sgnb && sgno != sgna); }
static inline bool mul128s_o(int128_t a, int128_t b, int128_t* o) { bool sgna = (a.hi >> 63); bool sgnb = (b.hi >> 63); if(sgna) a = neg128s(a); if(sgnb) b = neg128s(b); bool rv = mul128_o(*(uint128_t*)&a, *(uint128_t*)&b, (uint128_t*)o); if(sgna != sgnb) *o = neg128s(*o); return rv; }
static inline bool div128s_o(int128_t a, int128_t b, int128_t* q, int128_t* r) { bool sgna = (a.hi >> 63) != 0; bool sgnb = (b.hi >> 63) != 0; if(sgna) a = neg128s(a); if(sgnb) b = neg128s(b); bool rv = div128_o(*(uint128_t*)&a, *(uint128_t*)&b, (uint128_t*)q, (uint128_t*)r); if(sgna != sgnb && q) *q = neg128s(*q); if(sgna && r) *r = neg128s(*r); return rv; }
static inline int128_t add128s(int128_t a, int128_t b) { int128_t v; add128s_o(a, b, &v); return v; }
static inline int128_t sub128s(int128_t a, int128_t b) { int128_t v; sub128s_o(a, b, &v); return v; }
static inline int128_t mul128s(int128_t a, int128_t b) { int128_t v; mul128s_o(a, b, &v); return v; }
static inline int128_t div128s(int128_t a, int128_t b) { int128_t v; div128s_o(a, b, &v, NULL); return v; }
static inline int128_t mod128s(int128_t a, int128_t b) { int128_t v; div128s_o(a, b, NULL, &v); return v; }
static inline int128_t and128s(int128_t a, int128_t b) { int128_t v = { a.lo & b.lo, a.hi & b.hi }; return v; }
static inline int128_t or128s (int128_t a, int128_t b) { int128_t v = { a.lo | b.lo, a.hi | b.hi }; return v; }
static inline int128_t xor128s(int128_t a, int128_t b) { int128_t v = { a.lo ^ b.lo, a.hi ^ b.hi }; return v; }
static inline int128_t shl128s(int128_t a, uint32_t b) { int128_t v; if(b == 0) { return a; } else if(b < 64) { v.lo = a.lo << b; v.hi = (a.hi << b) | (a.lo >> (64 - b)); } else { v.hi = a.lo << (b - 64); v.lo = 0; } return v; }
static inline int128_t shr128s(int128_t a, uint32_t b) { int128_t v; if(b == 0) { return a; } else if(b < 64) { v.lo = (a.lo >> b)|(a.hi << (64 - b)); v.hi = (int64_t)a.hi >> b; } else { v.lo = (int64_t)a.hi >> (b - 64); v.hi = (int64_t)a.hi < 0 ? -1 : 0; } return v; }

static inline int slice_cmp(SLICE_PTR l, SLICE_PTR r) {
	int rv = memcmp(l.PTR, r.PTR, l.META < r.META ? l.META : r.META);
	if(rv != 0) return rv;
	if(l.META < r.META) return -1;
	if(l.META > r.META) return 1;
	return 0;
}
static inline SLICE_PTR make_sliceptr(void* ptr, size_t s) { SLICE_PTR rv = { ptr, s }; return rv; }
static inline TRAITOBJ_PTR make_traitobjptr(void* ptr, void* vt) { TRAITOBJ_PTR rv = { ptr, vt }; return rv; }

static inline size_t mrustc_max(size_t a, size_t b) { return a < b ? b : a; }
static inline void noop_drop(tUNIT *p) { }

static inline size_t mrustc_string_search_linear(SLICE_PTR val, size_t count, SLICE_PTR* options) {
	for(size_t i = 0; i < count; i ++) {
		int cmp = slice_cmp(val, options[i]);
		if(cmp < 0) break;
		if(cmp == 0) return i;
	}
	return SIZE_MAX;
}
static const uint8_t __mrustc_revmap[16] = { 0, 8, 4,12, 2,10, 6,14,  1, 9, 5,13, 3, 7,15};
static inline uint8_t __mrustc_bitrev8(uint8_t v) { if(v==0||v==0xFF) return v; return __mrustc_revmap[v>>4]|(__mrustc_revmap[v&15]<<4); }
static inline uint16_t __mrustc_bitrev16(uint16_t v) { if(v==0) return 0; return ((uint16_t)__mrustc_bitrev8(v>>8))|((uint16_t)__mrustc_bitrev8(v)<<8); }
static inline uint32_t __mrustc_bitrev32(uint32_t v) { if(v==0) return 0; return ((uint32_t)__mrustc_bitrev16(v>>16))|((uint32_t)__mrustc_bitrev16(v)<<16); }
static inline uint64_t __mrustc_bitrev64(uint64_t v) { if(v==0) return 0; return ((uint64_t)__mrustc_bitrev32(v>>32))|((uint64_t)__mrustc_bitrev32(v)<<32); }
static inline uint128_t __mrustc_bitrev128(uint128_t v) { uint128_t rv = { __mrustc_bitrev64(v.hi), __mrustc_bitrev64(v.lo) }; return rv; }
static inline uint8_t __mrustc_op_umax8(uint8_t a, uint8_t b) { return (a > b ? a : b); }
static inline uint8_t __mrustc_op_umin8(uint8_t a, uint8_t b) { return (a < b ? a : b); }
static inline uint8_t __mrustc_op_imax8(uint8_t a, uint8_t b) { return ((int8_t)a > (int8_t)b ? a : b); }
static inline uint8_t __mrustc_op_imin8(uint8_t a, uint8_t b) { return ((int8_t)a < (int8_t)b ? a : b); }
static inline uint8_t __mrustc_op_and_not8(uint8_t a, uint8_t b) { return ~(a & b); }
static inline uint16_t __mrustc_op_umax16(uint16_t a, uint16_t b) { return (a > b ? a : b); }
static inline uint16_t __mrustc_op_umin16(uint16_t a, uint16_t b) { return (a < b ? a : b); }
static inline uint16_t __mrustc_op_imax16(uint16_t a, uint16_t b) { return ((int16_t)a > (int16_t)b ? a : b); }
static inline uint16_t __mrustc_op_imin16(uint16_t a, uint16_t b) { return ((int16_t)a < (int16_t)b ? a : b); }
static inline uint16_t __mrustc_op_and_not16(uint16_t a, uint16_t b) { return ~(a & b); }
static inline uint32_t __mrustc_op_umax32(uint32_t a, uint32_t b) { return (a > b ? a : b); }
static inline uint32_t __mrustc_op_umin32(uint32_t a, uint32_t b) { return (a < b ? a : b); }
static inline uint32_t __mrustc_op_imax32(uint32_t a, uint32_t b) { return ((int32_t)a > (int32_t)b ? a : b); }
static inline uint32_t __mrustc_op_imin32(uint32_t a, uint32_t b) { return ((int32_t)a < (int32_t)b ? a : b); }
static inline uint32_t __mrustc_op_and_not32(uint32_t a, uint32_t b) { return ~(a & b); }
static inline uint64_t __mrustc_op_umax64(uint64_t a, uint64_t b) { return (a > b ? a : b); }
static inline uint64_t __mrustc_op_umin64(uint64_t a, uint64_t b) { return (a < b ? a : b); }
static inline uint64_t __mrustc_op_imax64(uint64_t a, uint64_t b) { return ((int64_t)a > (int64_t)b ? a : b); }
static inline uint64_t __mrustc_op_imin64(uint64_t a, uint64_t b) { return ((int64_t)a < (int64_t)b ? a : b); }
static inline uint64_t __mrustc_op_and_not64(uint64_t a, uint64_t b) { return ~(a & b); }
struct s_ZRG2cE9core0_0_05alloc6Layout0g;
struct e_ZRG1cE12libc0_0_0_H16c_void0g;
// struct ::"core-0_0_0"::nonzero::NonZero<usize,>
struct s_ZRG2cE9core0_0_07nonzero7NonZero1gCu  {
	/*@0*/uintptr_t _0; // usize
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_07nonzero7NonZero1gCu[ (sizeof(struct s_ZRG2cE9core0_0_07nonzero7NonZero1gCu) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_07nonzero7NonZero1gCu[ (ALIGNOF(struct s_ZRG2cE9core0_0_07nonzero7NonZero1gCu) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::num::NonZeroUsize
struct s_ZRG2cE9core0_0_03num12NonZeroUsize0g  {
	/*@0*/struct s_ZRG2cE9core0_0_07nonzero7NonZero1gCu _0; // ::"core-0_0_0"::nonzero::NonZero<usize,>/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03num12NonZeroUsize0g[ (sizeof(struct s_ZRG2cE9core0_0_03num12NonZeroUsize0g) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03num12NonZeroUsize0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03num12NonZeroUsize0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::alloc::Layout
struct s_ZRG2cE9core0_0_05alloc6Layout0g  {
	/*@0*/uintptr_t _0; // usize
	/*@8*/struct s_ZRG2cE9core0_0_03num12NonZeroUsize0g _1; // ::"core-0_0_0"::num::NonZeroUsize/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_05alloc6Layout0g[ (sizeof(struct s_ZRG2cE9core0_0_05alloc6Layout0g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_05alloc6Layout0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05alloc6Layout0g) == 8) ? 1 : -1 ];
struct s_ZRG1cM17alloc_system0_0_06System0g;
// struct ::"core-0_0_0"::nonzero::NonZero<*const u8,>
struct s_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa  {
	/*@0*/uint8_t *_0; // *const u8
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa[ (sizeof(struct s_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa[ (ALIGNOF(struct s_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::ptr::NonNull<u8,>
struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa  {
	/*@0*/struct s_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa _0; // ::"core-0_0_0"::nonzero::NonZero<*const u8,>/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03ptr7NonNull1gCa[ (sizeof(struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03ptr7NonNull1gCa[ (ALIGNOF(struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::alloc::Excess
struct s_ZRG2cE9core0_0_05alloc6Excess0g  {
	/*@0*/struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa _0; // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
	/*@8*/uintptr_t _1; // usize
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_05alloc6Excess0g[ (sizeof(struct s_ZRG2cE9core0_0_05alloc6Excess0g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_05alloc6Excess0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05alloc6Excess0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Ok<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>
struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  {
	/*@0*/uint8_t _1; // u8
	/*@8*/struct s_ZRG2cE9core0_0_05alloc6Excess0g _0; // ::"core-0_0_0"::alloc::Excess/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g) == 24) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::alloc::AllocErr
struct s_ZRG2cE9core0_0_05alloc8AllocErr0g  {
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG2cE9core0_0_05alloc8AllocErr0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05alloc8AllocErr0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Err<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>
struct s_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ::"core-0_0_0"::alloc::AllocErr/*S*/
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g) == 1) ? 1 : -1 ];
// enum ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g {
	union {
		struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g var_0;
		struct s_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g var_1;
		uint8_t TAG;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g[ (sizeof(struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g) == 24) ? 1 : -1 ];
 // (usize, usize, )
typedef struct TUP_2_ZRTCu_ZRTCu  {
	/*@0*/uintptr_t _0; // usize
	/*@8*/uintptr_t _1; // usize
} TUP_2_ZRTCu_ZRTCu ;
typedef char sizeof_assert_TUP_2_ZRTCu_ZRTCu [ (sizeof(TUP_2_ZRTCu_ZRTCu ) == 16) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Ok<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>
struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  {
	/*@0*/uint8_t _1; // u8
	/*@8*/struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa _0; // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Err<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>
struct s_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ::"core-0_0_0"::alloc::AllocErr/*S*/
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g) == 1) ? 1 : -1 ];
// enum ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g {
	union {
		struct s_ZRG2cE9core0_0_06resultG8ResultOk2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g var_0;
		struct s_ZRG2cE9core0_0_06resultG9ResultErr2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g var_1;
		uint8_t TAG;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g[ (sizeof(struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g) == 16) ? 1 : -1 ];
// struct ::"core-0_0_0"::alloc::closure#alloc_excess_0<'#ivar1,>
struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_00g  {
	/*@0*/TUP_2_ZRTCu_ZRTCu *_0; // &'#ivar1 (usize, usize, )
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_05allocH21closurealloc_excess_00g[ (sizeof(struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_00g) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_05allocH21closurealloc_excess_00g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_00g) == 8) ? 1 : -1 ];
// struct ::"alloc_system-0_0_0"::System
struct s_ZRG1cM17alloc_system0_0_06System0g  {
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG1cM17alloc_system0_0_06System0g[ (ALIGNOF(struct s_ZRG1cM17alloc_system0_0_06System0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::option::Option#Some<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>
struct s_ZRG2cE9core0_0_06optionG10OptionSome1gG2c_A3ptr7NonNull1gCa  {
	/*@0*/struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa _0; // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gG2c_A3ptr7NonNull1gCa[ (sizeof(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gG2c_A3ptr7NonNull1gCa) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gG2c_A3ptr7NonNull1gCa[ (ALIGNOF(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gG2c_A3ptr7NonNull1gCa) == 8) ? 1 : -1 ];
// enum ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>
struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa {
	struct {
		struct s_ZRG2cE9core0_0_06optionG10OptionSome1gG2c_A3ptr7NonNull1gCa var_1;
	} DATA;};
typedef char sizeof_assert_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa[ (sizeof(struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::alloc::closure#realloc_excess_1<'#ivar1,>
struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_10g  {
	/*@0*/TUP_2_ZRTCu_ZRTCu *_0; // &'#ivar1 (usize, usize, )
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_05allocH23closurerealloc_excess_10g[ (sizeof(struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_10g) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_05allocH23closurerealloc_excess_10g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_10g) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Ok<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>
struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A5alloc20CannotReallocInPlace0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ()
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A5alloc20CannotReallocInPlace0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A5alloc20CannotReallocInPlace0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A5alloc20CannotReallocInPlace0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A5alloc20CannotReallocInPlace0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::alloc::CannotReallocInPlace
struct s_ZRG2cE9core0_0_05alloc20CannotReallocInPlace0g  {
	char _d;
} __attribute__((__aligned__(1),)) ;
typedef char alignof_assert_ZRG2cE9core0_0_05alloc20CannotReallocInPlace0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_05alloc20CannotReallocInPlace0g) == 1) ? 1 : -1 ];
// struct ::"core-0_0_0"::result::Result#Err<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>
struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A5alloc20CannotReallocInPlace0g  {
	/*@0*/uint8_t _1; // u8
	/*@1*/// ZST; // ::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/
} __attribute__((__aligned__(1),)) ;
typedef char sizeof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A5alloc20CannotReallocInPlace0g[ (sizeof(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A5alloc20CannotReallocInPlace0g) == 1) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A5alloc20CannotReallocInPlace0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A5alloc20CannotReallocInPlace0g) == 1) ? 1 : -1 ];
// enum ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>
struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g {
	union {
		struct s_ZRG2cE9core0_0_06resultG8ResultOk2gT0G2c_A5alloc20CannotReallocInPlace0g var_0;
		struct s_ZRG2cE9core0_0_06resultG9ResultErr2gT0G2c_A5alloc20CannotReallocInPlace0g var_1;
		uint8_t TAG;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g[ (sizeof(struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g) == 1) ? 1 : -1 ];
 // (::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, )
typedef struct TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa  {
	/*@0*/struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa _0; // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
} TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa ;
typedef char sizeof_assert_TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa [ (sizeof(TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa ) == 8) ? 1 : -1 ];
typedef struct TUP_4_ZRTBsCy_ZRTBsCy_ZRTCe_ZRTCe  TUP_4_ZRTBsCy_ZRTBsCy_ZRTCe_ZRTCe ;
 // (&'static str, &'static str, u32, u32, )
typedef struct TUP_4_ZRTBsCy_ZRTBsCy_ZRTCe_ZRTCe  {
	/*@0*/uint32_t _2; // u32
	/*@4*/uint32_t _3; // u32
	/*@8*/SLICE_PTR _0; // &'static str
	/*@24*/SLICE_PTR _1; // &'static str
} TUP_4_ZRTBsCy_ZRTBsCy_ZRTCe_ZRTCe ;
typedef char sizeof_assert_TUP_4_ZRTBsCy_ZRTBsCy_ZRTCe_ZRTCe [ (sizeof(TUP_4_ZRTBsCy_ZRTBsCy_ZRTCe_ZRTCe ) == 40) ? 1 : -1 ];
// PROTO extern "Rust" ::"alloc_system-0_0_0"::platform::aligned_malloc
uint8_t * ZRG2cM17alloc_system0_0_08platform14aligned_malloc0g(
		struct s_ZRG2cE9core0_0_05alloc6Layout0g *arg0 // &'#omitted ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> *mut u8
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ /*- */>::realloc_fallback
uint8_t * ZRIG1cM17alloc_system0_0_06System0g16realloc_fallback0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		uint8_t *arg1, // *mut u8
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> *mut u8
;
// PROTO extern "Rust" <::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>*/>::ok_or<::"core-0_0_0"::alloc::AllocErr/*S*/,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRIG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa5ok_or1gG2c_A5alloc8AllocErr0g(
		struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa arg0, // ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/
		struct s_ZRG2cE9core0_0_05alloc8AllocErr0g arg1 // ::"core-0_0_0"::alloc::AllocErr/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/ /*- <u8,>*/>::new
static struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa  ZRIG2cE9core0_0_03ptr7NonNull1gCa3new0g(
		uint8_t *arg0 // *mut u8
		) // -> ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>*/>::map<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::closure#alloc_excess_0<'#ivar1,>/*S*/,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRIG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g3map2gG2c_A_F6Excess0gG2c_A_FH21closureallo$fbcbd5cde7b530b0(
		struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g arg0, // ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
		struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_00g arg1 // ::"core-0_0_0"::alloc::closure#alloc_excess_0<'#ivar1,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>*/>::map<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::closure#realloc_excess_1<'#ivar1,>/*S*/,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRIG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g3map2gG2c_A_F6Excess0gG2c_A_FH23closurereal$39531164ba4c18f5(
		struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g arg0, // ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
		struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_10g arg1 // ::"core-0_0_0"::alloc::closure#realloc_excess_1<'#ivar1,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <usize as ::"core-0_0_0"::cmp::Ord>::min
static uintptr_t  ZRQCu2cE9core0_0_03cmp3Ord0g3min0g(
		uintptr_t arg0, // usize
		uintptr_t arg1 // usize
		) // -> usize
;
// PROTO extern "Rust" <usize as ::"core-0_0_0"::cmp::PartialOrd<usize,>>::le<'#omitted,'#omitted,>
static RUST_BOOL  ZRQCu2cE9core0_0_03cmp10PartialOrd1gCu2le0g(
		uintptr_t *arg0, // &'#omitted usize
		uintptr_t *arg1 // &'#omitted usize
		) // -> bool
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc<'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g_D0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc_excess<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g12alloc_excess0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc_zeroed<'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g12alloc_zeroed0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::dealloc<'#omitted,>
void  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g7dealloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ()
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::grow_in_place<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g13grow_in_place0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::realloc<'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g7realloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::realloc_excess<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g14realloc_excess0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::shrink_in_place<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g15shrink_in_place0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>/*E*/
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::usable_size<'#omitted,'#omitted,>
static TUP_2_ZRTCu_ZRTCu  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g11usable_size0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g *arg1 // &'#omitted ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> (usize, usize, )
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc<'#omitted,>
uint8_t * ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g_D0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> *mut u8
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc_zeroed<'#omitted,>
uint8_t * ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g12alloc_zeroed0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> *mut u8
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::dealloc<'#omitted,>
void  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g7dealloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		uint8_t *arg1, // *mut u8
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ()
;
// PROTO extern "Rust" <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::realloc<'#omitted,>
uint8_t * ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g7realloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		uint8_t *arg1, // *mut u8
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> *mut u8
;
// EXTERN extern "Rust" ::"core-0_0_0"::panicking::panic<'static,>
extern tBANG  ZRG2cE9core0_0_09panicking5panic0g(
		TUP_4_ZRTBsCy_ZRTBsCy_ZRTCe_ZRTCe *arg0 // &'static (&'static str, &'static str, u32, u32, )
		) // -> !
;
// EXTERN extern "C" ::"libc-0_0_0_H1"::calloc
extern struct e_ZRG1cE12libc0_0_0_H16c_void0g * ZRG1cE12libc0_0_0_H16calloc0g(
		uintptr_t arg0, // usize
		uintptr_t arg1 // usize
		) // -> *mut ::"libc-0_0_0_H1"::c_void/*E*/
 asm("calloc");
// EXTERN extern "C" ::"libc-0_0_0_H1"::free
extern void  ZRG1cE12libc0_0_0_H14free0g(
		struct e_ZRG1cE12libc0_0_0_H16c_void0g *arg0 // *mut ::"libc-0_0_0_H1"::c_void/*E*/
		) // -> ()
 asm("free");
// EXTERN extern "C" ::"libc-0_0_0_H1"::malloc
extern struct e_ZRG1cE12libc0_0_0_H16c_void0g * ZRG1cE12libc0_0_0_H16malloc0g(
		uintptr_t arg0 // usize
		) // -> *mut ::"libc-0_0_0_H1"::c_void/*E*/
 asm("malloc");
// EXTERN extern "C" ::"libc-0_0_0_H1"::realloc
extern struct e_ZRG1cE12libc0_0_0_H16c_void0g * ZRG1cE12libc0_0_0_H17realloc0g(
		struct e_ZRG1cE12libc0_0_0_H16c_void0g *arg0, // *mut ::"libc-0_0_0_H1"::c_void/*E*/
		uintptr_t arg1 // usize
		) // -> *mut ::"libc-0_0_0_H1"::c_void/*E*/
 asm("realloc");
// EXTERN extern "C" ::"libc-0_0_0_H1"::unix::posix_memalign
extern int32_t  ZRG2cE12libc0_0_0_H14unix14posix_memalign0g(
		struct e_ZRG1cE12libc0_0_0_H16c_void0g **arg0, // *mut *mut ::"libc-0_0_0_H1"::c_void/*E*/
		uintptr_t arg1, // usize
		uintptr_t arg2 // usize
		) // -> i32
 asm("posix_memalign");
// EXTERN extern "Rust" <::"core-0_0_0"::alloc::Layout/*S*/ as ::"core-0_0_0"::clone::Clone>::clone<'#local4,>
extern struct s_ZRG2cE9core0_0_05alloc6Layout0g  ZRQG2cE9core0_0_05alloc6Layout0g2c_A5clone5Clone0g_D0g(
		struct s_ZRG2cE9core0_0_05alloc6Layout0g *arg0 // &'#local4 ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::alloc::Layout/*S*/
;
// EXTERN extern "Rust" <::"core-0_0_0"::alloc::closure#alloc_excess_0<'#ivar1,>/*S*/ as ::"core-0_0_0"::ops::function::FnOnce<(::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, ),>>::call_once
extern struct s_ZRG2cE9core0_0_05alloc6Excess0g  ZRQG2cE9core0_0_05allocH21closurealloc_excess_00g3c_A3ops8function6FnOnce1gT1G2c_A3ptr7NonNull1gCa9call_once0g(
		struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_00g arg0, // ::"core-0_0_0"::alloc::closure#alloc_excess_0<'#ivar1,>/*S*/
		TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa arg1 // (::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, )
		) // -> ::"core-0_0_0"::alloc::Excess/*S*/
;
// EXTERN extern "Rust" <::"core-0_0_0"::alloc::closure#realloc_excess_1<'#ivar1,>/*S*/ as ::"core-0_0_0"::ops::function::FnOnce<(::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, ),>>::call_once
extern struct s_ZRG2cE9core0_0_05alloc6Excess0g  ZRQG2cE9core0_0_05allocH23closurerealloc_excess_10g3c_A3ops8function6FnOnce1gT1G2c_A3ptr7NonNull1gCa9call_once0g(
		struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_10g arg0, // ::"core-0_0_0"::alloc::closure#realloc_excess_1<'#ivar1,>/*S*/
		TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa arg1 // (::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, )
		) // -> ::"core-0_0_0"::alloc::Excess/*S*/
;
extern union u_static_ZRG2cE9core0_0_05allocG7lifted00g{ TUP_4_ZRTBsCy_ZRTBsCy_ZRTCe_ZRTCe val; uintptr_t raw[5]; } ZRG2cE9core0_0_05allocG7lifted00g;	// static ::"core-0_0_0"::alloc::lifted#0 : (&'static str, &'static str, u32, u32, )
extern union u_static_ZRG2cE9core0_0_05allocG7lifted10g{ TUP_4_ZRTBsCy_ZRTBsCy_ZRTCe_ZRTCe val; uintptr_t raw[5]; } ZRG2cE9core0_0_05allocG7lifted10g;	// static ::"core-0_0_0"::alloc::lifted#1 : (&'static str, &'static str, u32, u32, )
// ::"alloc_system-0_0_0"::platform::aligned_malloc
uint8_t * ZRG2cM17alloc_system0_0_08platform14aligned_malloc0g(
		struct s_ZRG2cE9core0_0_05alloc6Layout0g *arg0 // &'#omitted ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> *mut u8

{
	uint8_t *rv;
	struct e_ZRG1cE12libc0_0_0_H16c_void0g *var0;	// *mut ::"libc-0_0_0_H1"::c_void/*E*/
	int32_t var1;	// i32
	RUST_BOOL var2;	// bool
	struct e_ZRG1cE12libc0_0_0_H16c_void0g **var3;	// &'#local0 mut *mut ::"libc-0_0_0_H1"::c_void/*E*/
	struct e_ZRG1cE12libc0_0_0_H16c_void0g **var4;	// *mut *mut ::"libc-0_0_0_H1"::c_void/*E*/
	uintptr_t var5;	// usize
	struct s_ZRG2cE9core0_0_03num12NonZeroUsize0g var6;	// ::"core-0_0_0"::num::NonZeroUsize/*S*/
	uintptr_t var7;	// usize
	var5 = 0x0ull;	// _5 = Constant(0x0 usize)
	var0 = (struct e_ZRG1cE12libc0_0_0_H16c_void0g *)var5;	// _0 = Cast(_5 as *mut ::"libc-0_0_0_H1"::c_void/*E*/)
	var3 = & var0;	// _3 = Borrow(Unique, _0)
	var4 = (struct e_ZRG1cE12libc0_0_0_H16c_void0g **)var3;	// _4 = Cast(_3 as *mut *mut ::"libc-0_0_0_H1"::c_void/*E*/)
	var6 = arg0->_1;	// _6 = Use(a0*.1)
	var1 = ZRG2cE12libc0_0_0_H14unix14posix_memalign0g( var4, var6._0._0, arg0->_0 );
	// ^ Call( _1 = ::"libc-0_0_0_H1"::unix::posix_memalign( _4, _6.0.0, a0*.0, ), bb1, bb2)
	var2 = var1 != 0;	// _2 = BinOp(_1 NE +0 i32)
	if(var2) goto bb3; else goto bb4;
	// ^ If( _2 : 3, 4)
bb2: _Unwind_Resume(); // Diverge
bb3:
	var7 = 0x0ull;	// _7 = Constant(0x0 usize)
	rv = (uint8_t *)var7;	// retval = Cast(_7 as *mut u8)
	return rv;
	// ^ Return
bb4:
	rv = (uint8_t *)var0;	// retval = Cast(_0 as *mut u8)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ /*- */>::realloc_fallback
uint8_t * ZRIG1cM17alloc_system0_0_06System0g16realloc_fallback0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		uint8_t *arg1, // *mut u8
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> *mut u8

{
	uint8_t *rv;
	uint8_t *var0;	// *mut u8
	RUST_BOOL var1;	// bool
	uint8_t *var2;	// *const u8
	tUNIT var3 = {0};	// ()
	tUNIT var4 = {0};	// ()
	struct s_ZRG2cE9core0_0_05alloc6Layout0g var5;	// ::"core-0_0_0"::alloc::Layout/*S*/
	struct s_ZRG2cE9core0_0_03num12NonZeroUsize0g var6;	// ::"core-0_0_0"::num::NonZeroUsize/*S*/
	struct s_ZRG2cE9core0_0_07nonzero7NonZero1gCu var7;	// ::"core-0_0_0"::nonzero::NonZero<usize,>/*S*/
	uint8_t *var8;	// *mut u8
	uintptr_t var9;	// usize
	uintptr_t var10;	// usize
	struct e_ZRG1cE12libc0_0_0_H16c_void0g *var11;	// *mut ::"libc-0_0_0_H1"::c_void/*E*/
	var7._0 = arg2._1._0._0;	// _7 = Struct(::"core-0_0_0"::nonzero::NonZero<usize,>, {a2.1.0.0})
	var6._0 = var7;	// _6 = Struct(::"core-0_0_0"::num::NonZeroUsize, {_7})
	var5._0 = arg3;
	var5._1 = var6;	// _5 = Struct(::"core-0_0_0"::alloc::Layout, {a3, _6})
	var0 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g_D0g( arg0, var5 );
	// ^ Call( _0 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc<'M0,>( a0, _5, ), bb1, bb2)
	var9 = 0x0ull;	// _9 = Constant(0x0 usize)
	var8 = (uint8_t *)var9;	// _8 = Cast(_9 as *mut u8)
	var1 = var0 == var8;	// _1 = BinOp(_0 EQ _8)
	if(var1) goto bb6; else goto bb3;
	// ^ If( _1 : 6, 3)
bb2: _Unwind_Resume(); // Diverge
bb3:
	var10 = ZRQCu2cE9core0_0_03cmp3Ord0g3min0g( arg2._0, arg3 );
	// ^ Call( _10 = <usize as ::"core-0_0_0"::cmp::Ord>::min( a2.0, a3, ), bb4, bb2)
	var2 = (uint8_t *)arg1;	// _2 = Cast(a1 as *const u8)
	memcpy( var0, var2, var10 * sizeof(uint8_t ));
	// ^ Call( _3 = "copy_nonoverlapping"::<u8,>( _2, _0, _10, ), bb5, bb2)
	var11 = (struct e_ZRG1cE12libc0_0_0_H16c_void0g *)arg1;	// _11 = Cast(a1 as *mut ::"libc-0_0_0_H1"::c_void/*E*/)
	ZRG1cE12libc0_0_0_H14free0g( var11 );
	// ^ Call( _4 = ::"libc-0_0_0_H1"::free( _11, ), bb6, bb2)
bb6:
	rv = var0;	// retval = Use(_0)
	return rv;
	// ^ Return
}
// <::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>*/>::ok_or<::"core-0_0_0"::alloc::AllocErr/*S*/,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRIG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa5ok_or1gG2c_A5alloc8AllocErr0g(
		struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa arg0, // ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/
		struct s_ZRG2cE9core0_0_05alloc8AllocErr0g arg1 // ::"core-0_0_0"::alloc::AllocErr/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g rv;
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g var0;	// ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
	bool df0 = 1;
	if( arg0.DATA.var_1._0._0._0 != 0 )
		goto bb2;
	else
		goto bb1;
	// ^ Switch( a0 : 0 => bb1, 1 => bb2, )
bb1:
	var0.DATA.TAG = 1;	// _0 = Variant(::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,> #1, {a1})
	df0 = 0;
	goto bb3;
	// ^ Goto(3)
bb2:
	var0.DATA.TAG = 0;
	var0.DATA.var_0._0 = arg0.DATA.var_1._0;	// _0 = Variant(::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,> #0, {a0#1.0})
	// ^ Goto(3)
bb3:
	rv = var0;	// retval = Use(_0)
	if( df0 ) {
	}
	// ^ drop(a1 IF df$0)
	return rv;
	// ^ Return
}
// <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/ /*- <u8,>*/>::new
static struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa  ZRIG2cE9core0_0_03ptr7NonNull1gCa3new0g(
		uint8_t *arg0 // *mut u8
		) // -> ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa rv;
	RUST_BOOL var0;	// bool
	uint8_t *var1;	// *const u8
	struct s_ZRG2cE9core0_0_07nonzero7NonZero1gPsCa var2;	// ::"core-0_0_0"::nonzero::NonZero<*const u8,>/*S*/
	struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa var3;	// ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
	uint8_t *var4;	// *mut u8
	uintptr_t var5;	// usize
	var5 = 0x0ull;	// _5 = Constant(0x0 usize)
	var4 = (uint8_t *)var5;	// _4 = Cast(_5 as *mut u8)
	var0 = arg0 == var4;	// _0 = BinOp(a0 EQ _4)
	if(var0) goto bb1; else goto bb2;
	// ^ If( _0 : 1, 2)
bb1:
	memset(&rv, 0, sizeof(struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa ));	// retval = Variant(::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,> #0, {})
	return rv;
	// ^ Return
bb2:
	var1 = (uint8_t *)arg0;	// _1 = Cast(a0 as *const u8)
	var2._0 = var1;	// _2 = Struct(::"core-0_0_0"::nonzero::NonZero<*const u8,>, {_1})
	var3._0 = var2;	// _3 = Struct(::"core-0_0_0"::ptr::NonNull<u8,>, {_2})
	rv.DATA.var_1._0 = var3;	// retval = Variant(::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,> #1, {_3})
	return rv;
	// ^ Return
}
// <::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>*/>::map<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::closure#alloc_excess_0<'#ivar1,>/*S*/,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRIG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g3map2gG2c_A_F6Excess0gG2c_A_FH21closureallo$fbcbd5cde7b530b0(
		struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g arg0, // ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
		struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_00g arg1 // ::"core-0_0_0"::alloc::closure#alloc_excess_0<'#ivar1,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g rv;
	TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa var0;	// (::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, )
	struct s_ZRG2cE9core0_0_05alloc6Excess0g var1;	// ::"core-0_0_0"::alloc::Excess/*S*/
	if( arg0.DATA.TAG == 0) {goto bb1;} else {goto bb3;}
	// ^ Switch( a0 : 0 => bb1, 1 => bb3, )
bb1:
	;
	var0._0 = arg0.DATA.var_0._0;	// _0 = Tuple(a0#0.0)
	var1 = ZRQG2cE9core0_0_05allocH21closurealloc_excess_00g3c_A3ops8function6FnOnce1gT1G2c_A3ptr7NonNull1gCa9call_once0g( arg1, var0 );
	// ^ Call( _1 = <::"core-0_0_0"::alloc::closure#alloc_excess_0<'#ivar1,>/*S*/ as ::"core-0_0_0"::ops::function::FnOnce<(::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, ),>>::call_once( a1, _0, ), bb2, bb4)
	rv.DATA.TAG = 0;
	rv.DATA.var_0._0 = var1;	// retval = Variant(::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,> #0, {_1})
	return rv;
	// ^ Return
bb3:
	rv.DATA.TAG = 1;	// retval = Variant(::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,> #1, {a0#1.0})
	return rv;
	// ^ Return
bb4: _Unwind_Resume(); // Diverge
}
// <::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>*/>::map<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::closure#realloc_excess_1<'#ivar1,>/*S*/,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRIG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g3map2gG2c_A_F6Excess0gG2c_A_FH23closurereal$39531164ba4c18f5(
		struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g arg0, // ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
		struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_10g arg1 // ::"core-0_0_0"::alloc::closure#realloc_excess_1<'#ivar1,>/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g rv;
	TUP_1_ZRTG2cE9core0_0_03ptr7NonNull1gCa var0;	// (::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, )
	struct s_ZRG2cE9core0_0_05alloc6Excess0g var1;	// ::"core-0_0_0"::alloc::Excess/*S*/
	if( arg0.DATA.TAG == 0) {goto bb1;} else {goto bb3;}
	// ^ Switch( a0 : 0 => bb1, 1 => bb3, )
bb1:
	;
	var0._0 = arg0.DATA.var_0._0;	// _0 = Tuple(a0#0.0)
	var1 = ZRQG2cE9core0_0_05allocH23closurerealloc_excess_10g3c_A3ops8function6FnOnce1gT1G2c_A3ptr7NonNull1gCa9call_once0g( arg1, var0 );
	// ^ Call( _1 = <::"core-0_0_0"::alloc::closure#realloc_excess_1<'#ivar1,>/*S*/ as ::"core-0_0_0"::ops::function::FnOnce<(::"core-0_0_0"::ptr::NonNull<u8,>/*S*/, ),>>::call_once( a1, _0, ), bb2, bb4)
	rv.DATA.TAG = 0;
	rv.DATA.var_0._0 = var1;	// retval = Variant(::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,> #0, {_1})
	return rv;
	// ^ Return
bb3:
	rv.DATA.TAG = 1;	// retval = Variant(::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,> #1, {a0#1.0})
	return rv;
	// ^ Return
bb4: _Unwind_Resume(); // Diverge
}
// <usize as ::"core-0_0_0"::cmp::Ord>::min
static uintptr_t  ZRQCu2cE9core0_0_03cmp3Ord0g3min0g(
		uintptr_t arg0, // usize
		uintptr_t arg1 // usize
		) // -> usize

{
	uintptr_t rv;
	RUST_BOOL var0;	// bool
	var0 = arg0 <= arg1;	// _0 = BinOp(a0 LE a1)
	if(var0) goto bb1; else goto bb2;
	// ^ If( _0 : 1, 2)
bb1:
	rv = arg0;	// retval = Use(a0)
	return rv;
	// ^ Return
bb2:
	rv = arg1;	// retval = Use(a1)
	return rv;
	// ^ Return
}
// <usize as ::"core-0_0_0"::cmp::PartialOrd<usize,>>::le<'#omitted,'#omitted,>
static RUST_BOOL  ZRQCu2cE9core0_0_03cmp10PartialOrd1gCu2le0g(
		uintptr_t *arg0, // &'#omitted usize
		uintptr_t *arg1 // &'#omitted usize
		) // -> bool

{
	RUST_BOOL rv;
	rv = (*arg0) <= (*arg1);	// retval = BinOp(a0* LE a1*)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc<'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g_D0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g rv;
	struct s_ZRG1cM17alloc_system0_0_06System0g *var0;	// &'M0 ::"alloc_system-0_0_0"::System/*S*/
	uint8_t *var1;	// *mut u8
	struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa var2;	// ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_05alloc8AllocErr0g var3 = {0};	// ::"core-0_0_0"::alloc::AllocErr/*S*/
	var0 = arg0;	// _0 = Borrow(Shared, a0*)
	var1 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g_D0g( var0, arg1 );
	// ^ Call( _1 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc<'M0,>( _0, a1, ), bb1, bb4)
	var2 = ZRIG2cE9core0_0_03ptr7NonNull1gCa3new0g( var1 );
	// ^ Call( _2 = <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/ /*- <u8,>*/>::new( _1, ), bb2, bb4)
	/* ZST assign */
	{
		struct s_ZRG2cE9core0_0_05alloc8AllocErr0g zarg1 = {0};
		rv = ZRIG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa5ok_or1gG2c_A5alloc8AllocErr0g( var2, zarg1 );
	}
	// ^ Call( retval = <::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>*/>::ok_or<::"core-0_0_0"::alloc::AllocErr/*S*/,>( _2, _3, ), bb3, bb4)
	// ^ drop(a0)
	return rv;
	// ^ Return
bb4: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc_excess<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g12alloc_excess0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g rv;
	TUP_2_ZRTCu_ZRTCu var0;	// (usize, usize, )
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g var1;	// ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
	TUP_2_ZRTCu_ZRTCu *var2;	// &'#ivar1 (usize, usize, )
	struct s_ZRG2cE9core0_0_05allocH21closurealloc_excess_00g var3;	// ::"core-0_0_0"::alloc::closure#alloc_excess_0<'#ivar1,>/*S*/
	struct s_ZRG2cE9core0_0_05alloc6Layout0g *var4;	// &'#local0 ::"core-0_0_0"::alloc::Layout/*S*/
	var4 = & arg1;	// _4 = Borrow(Shared, a1)
	;
	var0._0 = var4->_0;
	var0._1 = arg1._0;	// _0 = Tuple(_4*.0, a1.0)
	var1 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g_D0g( arg0, arg1 );
	// ^ Call( _1 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc<'#omitted,>( a0, a1, ), bb1, bb3)
	var2 = & var0;	// _2 = Borrow(Shared, _0)
	var3._0 = var2;	// _3 = Struct(::"core-0_0_0"::alloc::closure#alloc_excess_0<'#ivar1,>, {_2})
	rv = ZRIG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g3map2gG2c_A_F6Excess0gG2c_A_FH21closureallo$fbcbd5cde7b530b0( var1, var3 );
	// ^ Call( retval = <::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>*/>::map<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::closure#alloc_excess_0<'#ivar1,>/*S*/,>( _1, _3, ), bb2, bb3)
	return rv;
	// ^ Return
bb3: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::alloc_zeroed<'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g12alloc_zeroed0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g rv;
	struct s_ZRG1cM17alloc_system0_0_06System0g *var0;	// &'M0 ::"alloc_system-0_0_0"::System/*S*/
	uint8_t *var1;	// *mut u8
	struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa var2;	// ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_05alloc8AllocErr0g var3 = {0};	// ::"core-0_0_0"::alloc::AllocErr/*S*/
	var0 = arg0;	// _0 = Borrow(Shared, a0*)
	var1 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g12alloc_zeroed0g( var0, arg1 );
	// ^ Call( _1 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc_zeroed<'M0,>( _0, a1, ), bb1, bb4)
	var2 = ZRIG2cE9core0_0_03ptr7NonNull1gCa3new0g( var1 );
	// ^ Call( _2 = <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/ /*- <u8,>*/>::new( _1, ), bb2, bb4)
	/* ZST assign */
	{
		struct s_ZRG2cE9core0_0_05alloc8AllocErr0g zarg1 = {0};
		rv = ZRIG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa5ok_or1gG2c_A5alloc8AllocErr0g( var2, zarg1 );
	}
	// ^ Call( retval = <::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>*/>::ok_or<::"core-0_0_0"::alloc::AllocErr/*S*/,>( _2, _3, ), bb3, bb4)
	// ^ drop(a0)
	return rv;
	// ^ Return
bb4: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::dealloc<'#omitted,>
void  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g7dealloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ()

{
	tUNIT rv;
	struct e_ZRG1cE12libc0_0_0_H16c_void0g *var0;	// *mut ::"libc-0_0_0_H1"::c_void/*E*/
	uint8_t *var1;	// *mut u8
	var1 = (uint8_t *)arg1._0._0;	// _1 = Cast(a1.0.0 as *mut u8)
	var0 = (struct e_ZRG1cE12libc0_0_0_H16c_void0g *)var1;	// _0 = Cast(_1 as *mut ::"libc-0_0_0_H1"::c_void/*E*/)
	ZRG1cE12libc0_0_0_H14free0g( var0 );
	// ^ Call( retval = ::"libc-0_0_0_H1"::free( _0, ), bb1, bb2)
	// ^ drop(a0)
	return ;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::grow_in_place<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g13grow_in_place0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g rv;
	RUST_BOOL var0;	// bool
	tUNIT var1 = {0};	// ()
	tUNIT var2 = {0};	// ()
	struct s_ZRG2cE9core0_0_05alloc20CannotReallocInPlace0g var3 = {0};	// ::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/
	var0 = arg3 >= arg2._0;	// _0 = BinOp(a3 GE a2.0)
	if(var0) goto bb1; else goto bb2;
	// ^ If( _0 : 1, 2)
bb1:
	var0 = arg3 <= arg2._0;	// _0 = BinOp(a3 LE a2.0)
	if(var0) goto bb4; else goto bb5;
	// ^ If( _0 : 4, 5)
bb2:
	ZRG2cE9core0_0_09panicking5panic0g( &ZRG2cE9core0_0_05allocG7lifted00g.val );
	// ^ Call( _1 = ::"core-0_0_0"::panicking::panic<'static,>( &::"core-0_0_0"::alloc::lifted#0, ), bb3, bb3)
bb3: _Unwind_Resume(); // Diverge
bb4:
	/* ZST assign */
	rv.DATA.TAG = 0;	// retval = Variant(::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,> #0, {_2})
	// ^ drop(a0)
	return rv;
	// ^ Return
bb5:
	/* ZST assign */
	rv.DATA.TAG = 1;	// retval = Variant(::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,> #1, {_3})
	// ^ drop(a0)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::realloc<'#omitted,>
struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g7realloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g rv;
	struct s_ZRG1cM17alloc_system0_0_06System0g *var0;	// &'M0 ::"alloc_system-0_0_0"::System/*S*/
	uint8_t *var1;	// *mut u8
	struct e_ZRG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa var2;	// ::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/
	struct s_ZRG2cE9core0_0_05alloc8AllocErr0g var3 = {0};	// ::"core-0_0_0"::alloc::AllocErr/*S*/
	uint8_t *var4;	// *mut u8
	var0 = arg0;	// _0 = Borrow(Shared, a0*)
	var4 = (uint8_t *)arg1._0._0;	// _4 = Cast(a1.0.0 as *mut u8)
	var1 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g7realloc0g( var0, var4, arg2, arg3 );
	// ^ Call( _1 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::realloc<'M0,>( _0, _4, a2, a3, ), bb1, bb4)
	var2 = ZRIG2cE9core0_0_03ptr7NonNull1gCa3new0g( var1 );
	// ^ Call( _2 = <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/ /*- <u8,>*/>::new( _1, ), bb2, bb4)
	/* ZST assign */
	{
		struct s_ZRG2cE9core0_0_05alloc8AllocErr0g zarg1 = {0};
		rv = ZRIG2cE9core0_0_06option6Option1gG2c_A3ptr7NonNull1gCa5ok_or1gG2c_A5alloc8AllocErr0g( var2, zarg1 );
	}
	// ^ Call( retval = <::"core-0_0_0"::option::Option<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,>*/>::ok_or<::"core-0_0_0"::alloc::AllocErr/*S*/,>( _2, _3, ), bb3, bb4)
	// ^ drop(a0)
	return rv;
	// ^ Return
bb4: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::realloc_excess<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g14realloc_excess0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A5alloc6Excess0gG2c_A_D8AllocErr0g rv;
	struct s_ZRG2cE9core0_0_05alloc6Layout0g var0;	// ::"core-0_0_0"::alloc::Layout/*S*/
	TUP_2_ZRTCu_ZRTCu var1;	// (usize, usize, )
	struct e_ZRG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g var2;	// ::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/
	TUP_2_ZRTCu_ZRTCu *var3;	// &'#ivar1 (usize, usize, )
	struct s_ZRG2cE9core0_0_05allocH23closurerealloc_excess_10g var4;	// ::"core-0_0_0"::alloc::closure#realloc_excess_1<'#ivar1,>/*S*/
	struct s_ZRG2cE9core0_0_03num12NonZeroUsize0g var5;	// ::"core-0_0_0"::num::NonZeroUsize/*S*/
	struct s_ZRG2cE9core0_0_07nonzero7NonZero1gCu var6;	// ::"core-0_0_0"::nonzero::NonZero<usize,>/*S*/
	struct s_ZRG2cE9core0_0_05alloc6Layout0g *var7;	// &'#local0 ::"core-0_0_0"::alloc::Layout/*S*/
	var6._0 = arg2._1._0._0;	// _6 = Struct(::"core-0_0_0"::nonzero::NonZero<usize,>, {a2.1.0.0})
	var5._0 = var6;	// _5 = Struct(::"core-0_0_0"::num::NonZeroUsize, {_6})
	var0._0 = arg3;
	var0._1 = var5;	// _0 = Struct(::"core-0_0_0"::alloc::Layout, {a3, _5})
	var7 = & var0;	// _7 = Borrow(Shared, _0)
	;
	var1._0 = var7->_0;
	var1._1 = var0._0;	// _1 = Tuple(_7*.0, _0.0)
	var2 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g7realloc0g( arg0, arg1, arg2, arg3 );
	// ^ Call( _2 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::realloc<'#omitted,>( a0, a1, a2, a3, ), bb1, bb3)
	var3 = & var1;	// _3 = Borrow(Shared, _1)
	var4._0 = var3;	// _4 = Struct(::"core-0_0_0"::alloc::closure#realloc_excess_1<'#ivar1,>, {_3})
	rv = ZRIG2cE9core0_0_06result6Result2gG2c_A3ptr7NonNull1gCaG2c_A5alloc8AllocErr0g3map2gG2c_A_F6Excess0gG2c_A_FH23closurereal$39531164ba4c18f5( var2, var4 );
	// ^ Call( retval = <::"core-0_0_0"::result::Result<::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>/*E*/ /*- <::"core-0_0_0"::ptr::NonNull<u8,>/*S*/,::"core-0_0_0"::alloc::AllocErr/*S*/,>*/>::map<::"core-0_0_0"::alloc::Excess/*S*/,::"core-0_0_0"::alloc::closure#realloc_excess_1<'#ivar1,>/*S*/,>( _2, _4, ), bb2, bb3)
	return rv;
	// ^ Return
bb3: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::shrink_in_place<'#omitted,>
static struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g15shrink_in_place0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted mut ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_03ptr7NonNull1gCa arg1, // ::"core-0_0_0"::ptr::NonNull<u8,>/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,>/*E*/

{
	struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A5alloc20CannotReallocInPlace0g rv;
	RUST_BOOL var0;	// bool
	tUNIT var1 = {0};	// ()
	tUNIT var2 = {0};	// ()
	struct s_ZRG2cE9core0_0_05alloc20CannotReallocInPlace0g var3 = {0};	// ::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/
	var0 = arg3 <= arg2._0;	// _0 = BinOp(a3 LE a2.0)
	if(var0) goto bb1; else goto bb2;
	// ^ If( _0 : 1, 2)
bb1:
	var0 = arg2._0 <= arg3;	// _0 = BinOp(a2.0 LE a3)
	if(var0) goto bb4; else goto bb5;
	// ^ If( _0 : 4, 5)
bb2:
	ZRG2cE9core0_0_09panicking5panic0g( &ZRG2cE9core0_0_05allocG7lifted10g.val );
	// ^ Call( _1 = ::"core-0_0_0"::panicking::panic<'static,>( &::"core-0_0_0"::alloc::lifted#1, ), bb3, bb3)
bb3: _Unwind_Resume(); // Diverge
bb4:
	/* ZST assign */
	rv.DATA.TAG = 0;	// retval = Variant(::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,> #0, {_2})
	// ^ drop(a0)
	return rv;
	// ^ Return
bb5:
	/* ZST assign */
	rv.DATA.TAG = 1;	// retval = Variant(::"core-0_0_0"::result::Result<(),::"core-0_0_0"::alloc::CannotReallocInPlace/*S*/,> #1, {_3})
	// ^ drop(a0)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::Alloc>::usable_size<'#omitted,'#omitted,>
static TUP_2_ZRTCu_ZRTCu  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc5Alloc0g11usable_size0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g *arg1 // &'#omitted ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> (usize, usize, )

{
	TUP_2_ZRTCu_ZRTCu rv;
	struct s_ZRG2cE9core0_0_05alloc6Layout0g *var0;	// &'#omitted ::"core-0_0_0"::alloc::Layout/*S*/
	var0 = arg1;	// _0 = Use(a1)
	;
	rv._0 = var0->_0;
	rv._1 = arg1->_0;	// retval = Tuple(_0*.0, a1*.0)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc<'#omitted,>
uint8_t * ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g_D0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> *mut u8

{
	uint8_t *rv;
	RUST_BOOL var0;	// bool
	struct e_ZRG1cE12libc0_0_0_H16c_void0g *var1;	// *mut ::"libc-0_0_0_H1"::c_void/*E*/
	struct s_ZRG2cE9core0_0_05alloc6Layout0g *var2;	// &'#local0 ::"core-0_0_0"::alloc::Layout/*S*/
	var0 = arg1._1._0._0 <= 0x10ull;	// _0 = BinOp(a1.1.0.0 LE 0x10 usize)
	if(var0) goto bb1; else goto bb2;
	// ^ If( _0 : 1, 2)
bb1:
	var0 = arg1._1._0._0 <= arg1._0;	// _0 = BinOp(a1.1.0.0 LE a1.0)
	if(var0) goto bb5; else goto bb2;
	// ^ If( _0 : 5, 2)
bb2:
	var2 = & arg1;	// _2 = Borrow(Shared, a1)
	rv = ZRG2cM17alloc_system0_0_08platform14aligned_malloc0g( var2 );
	// ^ Call( retval = ::"alloc_system-0_0_0"::platform::aligned_malloc<'#local4,>( _2, ), bb3, bb4)
	return rv;
	// ^ Return
bb4: _Unwind_Resume(); // Diverge
bb5:
	var1 = ZRG1cE12libc0_0_0_H16malloc0g( arg1._0 );
	// ^ Call( _1 = ::"libc-0_0_0_H1"::malloc( a1.0, ), bb6, bb4)
	rv = (uint8_t *)var1;	// retval = Cast(_1 as *mut u8)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc_zeroed<'#omitted,>
uint8_t * ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g12alloc_zeroed0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg1 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> *mut u8

{
	uint8_t *rv;
	uint8_t *var0;	// *mut u8
	RUST_BOOL var1;	// bool
	struct e_ZRG1cE12libc0_0_0_H16c_void0g *var2;	// *mut ::"libc-0_0_0_H1"::c_void/*E*/
	struct s_ZRG2cE9core0_0_05alloc6Layout0g *var3;	// &'#local0 ::"core-0_0_0"::alloc::Layout/*S*/
	struct s_ZRG2cE9core0_0_05alloc6Layout0g var4;	// ::"core-0_0_0"::alloc::Layout/*S*/
	tUNIT var5 = {0};	// ()
	uint8_t *var6;	// *mut u8
	uintptr_t var7;	// usize
	var1 = arg1._1._0._0 <= 0x10ull;	// _1 = BinOp(a1.1.0.0 LE 0x10 usize)
	if(var1) goto bb1; else goto bb2;
	// ^ If( _1 : 1, 2)
bb1:
	var1 = arg1._1._0._0 <= arg1._0;	// _1 = BinOp(a1.1.0.0 LE a1.0)
	if(var1) goto bb8; else goto bb2;
	// ^ If( _1 : 8, 2)
bb2:
	var3 = & arg1;	// _3 = Borrow(Shared, a1)
	var4 = ZRQG2cE9core0_0_05alloc6Layout0g2c_A5clone5Clone0g_D0g( var3 );
	// ^ Call( _4 = <::"core-0_0_0"::alloc::Layout/*S*/ as ::"core-0_0_0"::clone::Clone>::clone<'#local4,>( _3, ), bb3, bb5)
	var0 = ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g_D0g( arg0, var4 );
	// ^ Call( _0 = <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::alloc<'M0,>( a0, _4, ), bb4, bb5)
	var7 = 0x0ull;	// _7 = Constant(0x0 usize)
	var6 = (uint8_t *)var7;	// _6 = Cast(_7 as *mut u8)
	var1 = var0 == var6;	// _1 = BinOp(_0 EQ _6)
	if(var1) goto bb7; else goto bb6;
	// ^ If( _1 : 7, 6)
bb5: _Unwind_Resume(); // Diverge
bb6:
	if( arg1._0 > 0) memset( var0, 0x0, arg1._0 * sizeof(uint8_t ));
	// ^ Call( _5 = "write_bytes"::<u8,>( _0, 0x0 u8, a1.0, ), bb7, bb5)
bb7:
	rv = var0;	// retval = Use(_0)
	return rv;
	// ^ Return
bb8:
	var2 = ZRG1cE12libc0_0_0_H16calloc0g( arg1._0, 0x1ull );
	// ^ Call( _2 = ::"libc-0_0_0_H1"::calloc( a1.0, 0x1 usize, ), bb9, bb5)
	rv = (uint8_t *)var2;	// retval = Cast(_2 as *mut u8)
	return rv;
	// ^ Return
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::dealloc<'#omitted,>
void  ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g7dealloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		uint8_t *arg1, // *mut u8
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2 // ::"core-0_0_0"::alloc::Layout/*S*/
		) // -> ()

{
	tUNIT rv;
	struct e_ZRG1cE12libc0_0_0_H16c_void0g *var0;	// *mut ::"libc-0_0_0_H1"::c_void/*E*/
	var0 = (struct e_ZRG1cE12libc0_0_0_H16c_void0g *)arg1;	// _0 = Cast(a1 as *mut ::"libc-0_0_0_H1"::c_void/*E*/)
	ZRG1cE12libc0_0_0_H14free0g( var0 );
	// ^ Call( retval = ::"libc-0_0_0_H1"::free( _0, ), bb1, bb2)
	return ;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
// <::"alloc_system-0_0_0"::System/*S*/ as ::"core-0_0_0"::alloc::GlobalAlloc>::realloc<'#omitted,>
uint8_t * ZRQG1cM17alloc_system0_0_06System0g2cE9core0_0_05alloc11GlobalAlloc0g7realloc0g(
		struct s_ZRG1cM17alloc_system0_0_06System0g *arg0, // &'#omitted ::"alloc_system-0_0_0"::System/*S*/
		uint8_t *arg1, // *mut u8
		struct s_ZRG2cE9core0_0_05alloc6Layout0g arg2, // ::"core-0_0_0"::alloc::Layout/*S*/
		uintptr_t arg3 // usize
		) // -> *mut u8

{
	uint8_t *rv;
	RUST_BOOL var0;	// bool
	struct e_ZRG1cE12libc0_0_0_H16c_void0g *var1;	// *mut ::"libc-0_0_0_H1"::c_void/*E*/
	struct e_ZRG1cE12libc0_0_0_H16c_void0g *var2;	// *mut ::"libc-0_0_0_H1"::c_void/*E*/
	var0 = arg2._1._0._0 <= 0x10ull;	// _0 = BinOp(a2.1.0.0 LE 0x10 usize)
	if(var0) goto bb1; else goto bb2;
	// ^ If( _0 : 1, 2)
bb1:
	var0 = arg2._1._0._0 <= arg3;	// _0 = BinOp(a2.1.0.0 LE a3)
	if(var0) goto bb5; else goto bb2;
	// ^ If( _0 : 5, 2)
bb2:
	rv = ZRIG1cM17alloc_system0_0_06System0g16realloc_fallback0g( arg0, arg1, arg2, arg3 );
	// ^ Call( retval = <::"alloc_system-0_0_0"::System/*S*/ /*- */>::realloc_fallback<'M0,>( a0, a1, a2, a3, ), bb3, bb4)
	return rv;
	// ^ Return
bb4: _Unwind_Resume(); // Diverge
bb5:
	var1 = (struct e_ZRG1cE12libc0_0_0_H16c_void0g *)arg1;	// _1 = Cast(a1 as *mut ::"libc-0_0_0_H1"::c_void/*E*/)
	var2 = ZRG1cE12libc0_0_0_H17realloc0g( var1, arg3 );
	// ^ Call( _2 = ::"libc-0_0_0_H1"::realloc( _1, a3, ), bb6, bb4)
	rv = (uint8_t *)var2;	// retval = Cast(_2 as *mut u8)
	return rv;
	// ^ Return
}
